// Phase 7K-Cleanup offline artifact mapper/select helpers.
import type {
  OfflineArtifactQuarantineReviewRecord,
  OfflineArtifactReviewBinderRecord,
  OfflineArtifactReviewBinderGovernanceSignoffRecord,
  OfflineArtifactGovernanceSignoffArchivePackRecord,
  OfflineArtifactArchivePackRetentionPolicyEvidenceRecord,
  OfflineArtifactRetentionEvidenceGovernanceReviewRecord,
  OfflineArtifactRetentionGovernanceReviewArchiveRecord,
  OfflineArtifactGovernanceArchiveChainFinalizationRecord,
  OfflineArtifactFinalizationChainAuditSnapshotRecord,
  OfflineArtifactAuditSnapshotGovernanceSignoffRecord,
  OfflineArtifactAuditSnapshotGovernanceArchiveRecord,
  OfflineArtifactRecord,
} from "../../../../intelligence/artifacts/artifactIntakeTypes";

export const toBoolean = (value: unknown): boolean => Number(value) === 1;

export const parseJson = <T>(value: unknown, fallback: T): T => {
  if (typeof value !== "string" || value.trim().length === 0) return fallback;
  try {
    return JSON.parse(value) as T;
  } catch (_err) {
    return fallback;
  }
};


export const mapLatestReviewRow = (row: Record<string, unknown> | undefined): OfflineArtifactQuarantineReviewRecord | null => {
  if (!row) return null;
  return {
    id: Number(row.id),
    artifactId: Number(row.artifactId),
    artifactSha256: String(row.artifactSha256 || ""),
    modelKey: String(row.modelKey || ""),
    modelVersion: String(row.modelVersion || ""),
    reviewDecision: String(row.reviewDecision || ""),
    reviewStatus: String(row.reviewStatus || ""),
    reviewerNotes: String(row.reviewerNotes || ""),
    rejectionReason: row.rejectionReason == null ? null : String(row.rejectionReason),
    validationFindingsJson: parseJson<Record<string, unknown>>(row.validationFindingsJson, {}),
    lineageComparisonJson: parseJson<Record<string, unknown>>(row.lineageComparisonJson, {}),
    evidenceJson: parseJson<Record<string, unknown>>(row.evidenceJson, {}),
    safetyNotes: parseJson<string[]>(row.safetyNotesJson, []),
    signedReviewHash: String(row.signedReviewHash || ""),
    artifactExecutionAllowed: toBoolean(row.artifactExecutionAllowed),
    artifactAutoActivationAllowed: toBoolean(row.artifactAutoActivationAllowed),
    modelExecutionAllowed: toBoolean(row.modelExecutionAllowed),
    inferenceEndpointExposed: toBoolean(row.inferenceEndpointExposed),
    productionIntegrationAllowed: toBoolean(row.productionIntegrationAllowed),
    canMutateBusinessRecords: toBoolean(row.canMutateBusinessRecords),
    reviewerUserId: row.reviewerUserId as string | number | null,
    reviewerDisplayName: row.reviewerDisplayName == null ? null : String(row.reviewerDisplayName),
    createdAt: String(row.createdAt || ""),
  };
};


export const mapLatestBinderRow = (row: Record<string, unknown> | undefined): OfflineArtifactReviewBinderRecord | null => {
  if (!row) return null;
  return {
    id: Number(row.id),
    artifactId: Number(row.artifactId),
    artifactSha256: String(row.artifactSha256 || ""),
    modelKey: String(row.modelKey || ""),
    modelVersion: String(row.modelVersion || ""),
    latestReviewId: row.latestReviewId == null ? null : Number(row.latestReviewId),
    latestReviewHash: row.latestReviewHash == null ? null : String(row.latestReviewHash),
    binderStatus: String(row.binderStatus || ""),
    binderPurpose: String(row.binderPurpose || ""),
    binderManifestJson: parseJson<Record<string, unknown>>(row.binderManifestJson, {}),
    traceabilityManifestJson: parseJson<Record<string, unknown>>(row.traceabilityManifestJson, {}),
    evidenceIndexJson: parseJson<Record<string, unknown>>(row.evidenceIndexJson, {}),
    exportReadinessNotesJson: parseJson<Record<string, unknown>>(row.exportReadinessNotesJson, {}),
    safetyNotes: parseJson<string[]>(row.safetyNotesJson, []),
    signedBinderHash: String(row.signedBinderHash || ""),
    artifactExecutionAllowed: toBoolean(row.artifactExecutionAllowed),
    artifactAutoActivationAllowed: toBoolean(row.artifactAutoActivationAllowed),
    modelExecutionAllowed: toBoolean(row.modelExecutionAllowed),
    inferenceEndpointExposed: toBoolean(row.inferenceEndpointExposed),
    productionIntegrationAllowed: toBoolean(row.productionIntegrationAllowed),
    canMutateBusinessRecords: toBoolean(row.canMutateBusinessRecords),
    exportFileCreated: toBoolean(row.exportFileCreated),
    artifactBytesIncluded: toBoolean(row.artifactBytesIncluded),
    createdByUserId: row.createdByUserId as string | number | null,
    createdAt: String(row.createdAt || ""),
  };
};

export const mapLatestGovernanceSignoffRow = (row: Record<string, unknown> | undefined): OfflineArtifactReviewBinderGovernanceSignoffRecord | null => {
  if (!row) return null;
  return {
    id: Number(row.id),
    binderId: Number(row.binderId),
    artifactId: Number(row.artifactId),
    artifactSha256: String(row.artifactSha256 || ""),
    modelKey: String(row.modelKey || ""),
    modelVersion: String(row.modelVersion || ""),
    signedBinderHash: String(row.signedBinderHash || ""),
    signoffDecision: String(row.signoffDecision || ""),
    signoffStatus: String(row.signoffStatus || ""),
    signerNotes: String(row.signerNotes || ""),
    rejectionReason: row.rejectionReason == null ? null : String(row.rejectionReason),
    governanceFindingsJson: parseJson<Record<string, unknown>>(row.governanceFindingsJson, {}),
    evidenceCompletenessJson: parseJson<Record<string, unknown>>(row.evidenceCompletenessJson, {}),
    riskAcceptanceJson: parseJson<Record<string, unknown>>(row.riskAcceptanceJson, {}),
    safetyNotes: parseJson<string[]>(row.safetyNotesJson, []),
    signedGovernanceHash: String(row.signedGovernanceHash || ""),
    artifactExecutionAllowed: toBoolean(row.artifactExecutionAllowed),
    artifactAutoActivationAllowed: toBoolean(row.artifactAutoActivationAllowed),
    modelExecutionAllowed: toBoolean(row.modelExecutionAllowed),
    inferenceEndpointExposed: toBoolean(row.inferenceEndpointExposed),
    productionIntegrationAllowed: toBoolean(row.productionIntegrationAllowed),
    canMutateBusinessRecords: toBoolean(row.canMutateBusinessRecords),
    exportFileCreated: toBoolean(row.exportFileCreated),
    artifactBytesIncluded: toBoolean(row.artifactBytesIncluded),
    binderActivationAllowed: toBoolean(row.binderActivationAllowed),
    signerUserId: row.signerUserId as string | number | null,
    signerDisplayName: row.signerDisplayName == null ? null : String(row.signerDisplayName),
    createdAt: String(row.createdAt || ""),
  };
};

export const mapOfflineArtifactRow = (row: Record<string, unknown> | undefined): OfflineArtifactRecord | null => {
  if (!row) return null;
  return {
    id: Number(row.id),
    artifactName: String(row.artifactName || ""),
    artifactKind: String(row.artifactKind || ""),
    modelKey: String(row.modelKey || ""),
    modelVersion: String(row.modelVersion || ""),
    source: String(row.source || ""),
    declaredFormat: String(row.declaredFormat || ""),
    declaredPurpose: String(row.declaredPurpose || ""),
    relatedModelImportId: row.relatedModelImportId as string | number | null,
    sha256: String(row.sha256 || ""),
    sizeBytes: Number(row.sizeBytes || 0),
    metadataJson: parseJson<Record<string, unknown>>(row.metadataJson, {}),
    artifactPayloadJson: parseJson<Record<string, unknown> | null>(row.artifactPayloadJson, null),
    validationMessages: parseJson<string[]>(row.validationMessagesJson, []),
    safetyNotes: parseJson<string[]>(row.safetyNotesJson, []),
    intakeStatus: String(row.intakeStatus || "needs_review"),
    quarantineStatus: String(row.quarantineStatus || "quarantined"),
    artifactExecutionAllowed: toBoolean(row.artifactExecutionAllowed),
    artifactAutoActivationAllowed: toBoolean(row.artifactAutoActivationAllowed),
    modelExecutionAllowed: toBoolean(row.modelExecutionAllowed),
    inferenceEndpointExposed: toBoolean(row.inferenceEndpointExposed),
    productionIntegrationAllowed: toBoolean(row.productionIntegrationAllowed),
    canMutateBusinessRecords: toBoolean(row.canMutateBusinessRecords),
    createdAt: String(row.createdAt || ""),
    createdByUserId: row.createdByUserId as string | number | null,
    updatedAt: String(row.updatedAt || ""),
  };
};



export const mapLatestArchivePackRow = (row: Record<string, unknown> | undefined): OfflineArtifactGovernanceSignoffArchivePackRecord | null => {
  if (!row) return null;
  return {
    id: Number(row.id),
    signoffId: Number(row.signoffId),
    binderId: Number(row.binderId),
    artifactId: Number(row.artifactId),
    artifactSha256: String(row.artifactSha256 || ""),
    modelKey: String(row.modelKey || ""),
    modelVersion: String(row.modelVersion || ""),
    signedGovernanceHash: String(row.signedGovernanceHash || ""),
    archivePackDecision: String(row.archivePackDecision || ""),
    archivePackStatus: String(row.archivePackStatus || ""),
    archivePackPurpose: String(row.archivePackPurpose || ""),
    archivistNotes: String(row.archivistNotes || ""),
    rejectionReason: row.rejectionReason == null ? null : String(row.rejectionReason),
    archiveManifestJson: parseJson<Record<string, unknown>>(row.archiveManifestJson, {}),
    retentionManifestJson: parseJson<Record<string, unknown>>(row.retentionManifestJson, {}),
    evidenceIndexJson: parseJson<Record<string, unknown>>(row.evidenceIndexJson, {}),
    archiveReadinessNotesJson: parseJson<Record<string, unknown>>(row.archiveReadinessNotesJson, {}),
    safetyNotes: parseJson<string[]>(row.safetyNotesJson, []),
    signedArchivePackHash: String(row.signedArchivePackHash || ""),
    archiveFileCreated: toBoolean(row.archiveFileCreated),
    artifactBytesIncluded: toBoolean(row.artifactBytesIncluded),
    retentionJobScheduled: toBoolean(row.retentionJobScheduled),
    deletionOrPurgeAllowed: toBoolean(row.deletionOrPurgeAllowed),
    artifactExecutionAllowed: toBoolean(row.artifactExecutionAllowed),
    artifactAutoActivationAllowed: toBoolean(row.artifactAutoActivationAllowed),
    modelExecutionAllowed: toBoolean(row.modelExecutionAllowed),
    inferenceEndpointExposed: toBoolean(row.inferenceEndpointExposed),
    productionIntegrationAllowed: toBoolean(row.productionIntegrationAllowed),
    canMutateBusinessRecords: toBoolean(row.canMutateBusinessRecords),
    createdByUserId: row.createdByUserId as string | number | null,
    archivistDisplayName: row.archivistDisplayName == null ? null : String(row.archivistDisplayName),
    createdAt: String(row.createdAt || ""),
  };
};


export const mapLatestRetentionPolicyEvidenceRow = (row: Record<string, unknown> | undefined): OfflineArtifactArchivePackRetentionPolicyEvidenceRecord | null => {
  if (!row) return null;
  return {
    id: Number(row.id),
    archivePackId: Number(row.archivePackId),
    signoffId: Number(row.signoffId),
    binderId: Number(row.binderId),
    artifactId: Number(row.artifactId),
    artifactSha256: String(row.artifactSha256 || ""),
    modelKey: String(row.modelKey || ""),
    modelVersion: String(row.modelVersion || ""),
    signedArchivePackHash: String(row.signedArchivePackHash || ""),
    retentionDecision: String(row.retentionDecision || ""),
    retentionStatus: String(row.retentionStatus || ""),
    retentionPolicyPurpose: String(row.retentionPolicyPurpose || ""),
    retentionWindowDays: row.retentionWindowDays == null ? null : Number(row.retentionWindowDays),
    retainUntil: row.retainUntil == null ? null : String(row.retainUntil),
    legalHoldReason: row.legalHoldReason == null ? null : String(row.legalHoldReason),
    policyNotes: String(row.policyNotes || ""),
    rejectionReason: row.rejectionReason == null ? null : String(row.rejectionReason),
    retentionPolicyManifestJson: parseJson<Record<string, unknown>>(row.retentionPolicyManifestJson, {}),
    holdEvidenceJson: parseJson<Record<string, unknown>>(row.holdEvidenceJson, {}),
    expiryMetadataJson: parseJson<Record<string, unknown>>(row.expiryMetadataJson, {}),
    purgeProhibitionEvidenceJson: parseJson<Record<string, unknown>>(row.purgeProhibitionEvidenceJson, {}),
    safetyNotes: parseJson<string[]>(row.safetyNotesJson, []),
    signedRetentionPolicyHash: String(row.signedRetentionPolicyHash || ""),
    retentionJobScheduled: toBoolean(row.retentionJobScheduled),
    deletionOrPurgeAllowed: toBoolean(row.deletionOrPurgeAllowed),
    archiveFileCreated: toBoolean(row.archiveFileCreated),
    artifactBytesIncluded: toBoolean(row.artifactBytesIncluded),
    artifactExecutionAllowed: toBoolean(row.artifactExecutionAllowed),
    artifactAutoActivationAllowed: toBoolean(row.artifactAutoActivationAllowed),
    modelExecutionAllowed: toBoolean(row.modelExecutionAllowed),
    inferenceEndpointExposed: toBoolean(row.inferenceEndpointExposed),
    productionIntegrationAllowed: toBoolean(row.productionIntegrationAllowed),
    canMutateBusinessRecords: toBoolean(row.canMutateBusinessRecords),
    createdByUserId: row.createdByUserId as string | number | null,
    policyReviewerDisplayName: row.policyReviewerDisplayName == null ? null : String(row.policyReviewerDisplayName),
    createdAt: String(row.createdAt || ""),
  };
};



export const mapLatestRetentionGovernanceReviewRow = (row: Record<string, unknown> | undefined): OfflineArtifactRetentionEvidenceGovernanceReviewRecord | null => {
  if (!row) return null;
  return {
    id: Number(row.id),
    retentionPolicyEvidenceId: Number(row.retentionPolicyEvidenceId),
    archivePackId: Number(row.archivePackId),
    signoffId: Number(row.signoffId),
    binderId: Number(row.binderId),
    artifactId: Number(row.artifactId),
    artifactSha256: String(row.artifactSha256 || ""),
    modelKey: String(row.modelKey || ""),
    modelVersion: String(row.modelVersion || ""),
    signedRetentionPolicyHash: String(row.signedRetentionPolicyHash || ""),
    governanceReviewDecision: String(row.governanceReviewDecision || ""),
    governanceReviewStatus: String(row.governanceReviewStatus || ""),
    governanceReviewPurpose: String(row.governanceReviewPurpose || ""),
    reviewerNotes: String(row.reviewerNotes || ""),
    rejectionReason: row.rejectionReason == null ? null : String(row.rejectionReason),
    riskConfirmationJson: parseJson<Record<string, unknown>>(row.riskConfirmationJson, {}),
    holdConfirmationJson: parseJson<Record<string, unknown>>(row.holdConfirmationJson, {}),
    purgeProhibitionReviewJson: parseJson<Record<string, unknown>>(row.purgeProhibitionReviewJson, {}),
    evidenceCompletenessJson: parseJson<Record<string, unknown>>(row.evidenceCompletenessJson, {}),
    safetyNotes: parseJson<string[]>(row.safetyNotesJson, []),
    signedRetentionGovernanceHash: String(row.signedRetentionGovernanceHash || ""),
    retentionJobScheduled: toBoolean(row.retentionJobScheduled),
    deletionOrPurgeAllowed: toBoolean(row.deletionOrPurgeAllowed),
    archiveFileCreated: toBoolean(row.archiveFileCreated),
    artifactBytesIncluded: toBoolean(row.artifactBytesIncluded),
    artifactExecutionAllowed: toBoolean(row.artifactExecutionAllowed),
    artifactAutoActivationAllowed: toBoolean(row.artifactAutoActivationAllowed),
    modelExecutionAllowed: toBoolean(row.modelExecutionAllowed),
    inferenceEndpointExposed: toBoolean(row.inferenceEndpointExposed),
    productionIntegrationAllowed: toBoolean(row.productionIntegrationAllowed),
    canMutateBusinessRecords: toBoolean(row.canMutateBusinessRecords),
    createdByUserId: row.createdByUserId as string | number | null,
    governanceReviewerDisplayName: row.governanceReviewerDisplayName == null ? null : String(row.governanceReviewerDisplayName),
    createdAt: String(row.createdAt || ""),
  };
};

export const mapLatestRetentionGovernanceArchiveRow = (row: Record<string, unknown> | undefined): OfflineArtifactRetentionGovernanceReviewArchiveRecord | null => {
  if (!row) return null;
  return {
    id: Number(row.id),
    retentionGovernanceReviewId: Number(row.retentionGovernanceReviewId),
    retentionPolicyEvidenceId: Number(row.retentionPolicyEvidenceId),
    archivePackId: Number(row.archivePackId),
    signoffId: Number(row.signoffId),
    binderId: Number(row.binderId),
    artifactId: Number(row.artifactId),
    artifactSha256: String(row.artifactSha256 || ""),
    modelKey: String(row.modelKey || ""),
    modelVersion: String(row.modelVersion || ""),
    signedRetentionGovernanceHash: String(row.signedRetentionGovernanceHash || ""),
    archiveDecision: String(row.archiveDecision || ""),
    archiveStatus: String(row.archiveStatus || ""),
    archivePurpose: String(row.archivePurpose || ""),
    archivistNotes: String(row.archivistNotes || ""),
    rejectionReason: row.rejectionReason == null ? null : String(row.rejectionReason),
    archiveManifestJson: parseJson<Record<string, unknown>>(row.archiveManifestJson, {}),
    reviewerTrailJson: parseJson<Record<string, unknown>>(row.reviewerTrailJson, {}),
    retentionGovernanceChainJson: parseJson<Record<string, unknown>>(row.retentionGovernanceChainJson, {}),
    evidenceIndexJson: parseJson<Record<string, unknown>>(row.evidenceIndexJson, {}),
    safetyNotes: parseJson<string[]>(row.safetyNotesJson, []),
    signedArchiveReadinessHash: String(row.signedArchiveReadinessHash || ""),
    retentionJobScheduled: toBoolean(row.retentionJobScheduled),
    deletionOrPurgeAllowed: toBoolean(row.deletionOrPurgeAllowed),
    archiveFileCreated: toBoolean(row.archiveFileCreated),
    artifactBytesIncluded: toBoolean(row.artifactBytesIncluded),
    artifactExecutionAllowed: toBoolean(row.artifactExecutionAllowed),
    artifactAutoActivationAllowed: toBoolean(row.artifactAutoActivationAllowed),
    modelExecutionAllowed: toBoolean(row.modelExecutionAllowed),
    inferenceEndpointExposed: toBoolean(row.inferenceEndpointExposed),
    productionIntegrationAllowed: toBoolean(row.productionIntegrationAllowed),
    canMutateBusinessRecords: toBoolean(row.canMutateBusinessRecords),
    createdByUserId: row.createdByUserId as string | number | null,
    archivistDisplayName: row.archivistDisplayName == null ? null : String(row.archivistDisplayName),
    createdAt: String(row.createdAt || ""),
  };
};


export const mapLatestFinalizationRow = (row: Record<string, unknown> | undefined): OfflineArtifactGovernanceArchiveChainFinalizationRecord | null => {
  if (!row) return null;
  return {
    id: Number(row.id),
    retentionGovernanceArchiveId: Number(row.retentionGovernanceArchiveId),
    retentionGovernanceReviewId: Number(row.retentionGovernanceReviewId),
    retentionPolicyEvidenceId: Number(row.retentionPolicyEvidenceId),
    archivePackId: Number(row.archivePackId),
    signoffId: Number(row.signoffId),
    binderId: Number(row.binderId),
    artifactId: Number(row.artifactId),
    artifactSha256: String(row.artifactSha256 || ""),
    modelKey: String(row.modelKey || ""),
    modelVersion: String(row.modelVersion || ""),
    signedArchiveReadinessHash: String(row.signedArchiveReadinessHash || ""),
    finalizationDecision: String(row.finalizationDecision || ""),
    finalizationStatus: String(row.finalizationStatus || ""),
    finalizationPurpose: String(row.finalizationPurpose || ""),
    finalReviewerNotes: String(row.finalReviewerNotes || ""),
    rejectionReason: row.rejectionReason == null ? null : String(row.rejectionReason),
    chainCompletenessJson: parseJson<Record<string, unknown>>(row.chainCompletenessJson, {}),
    finalReviewerAcknowledgementJson: parseJson<Record<string, unknown>>(row.finalReviewerAcknowledgementJson, {}),
    immutableEvidenceSummaryJson: parseJson<Record<string, unknown>>(row.immutableEvidenceSummaryJson, {}),
    evidenceIndexJson: parseJson<Record<string, unknown>>(row.evidenceIndexJson, {}),
    safetyNotes: parseJson<string[]>(row.safetyNotesJson, []),
    signedFinalizationReadinessHash: String(row.signedFinalizationReadinessHash || ""),
    retentionJobScheduled: toBoolean(row.retentionJobScheduled),
    deletionOrPurgeAllowed: toBoolean(row.deletionOrPurgeAllowed),
    archiveFileCreated: toBoolean(row.archiveFileCreated),
    artifactBytesIncluded: toBoolean(row.artifactBytesIncluded),
    artifactExecutionAllowed: toBoolean(row.artifactExecutionAllowed),
    artifactAutoActivationAllowed: toBoolean(row.artifactAutoActivationAllowed),
    modelExecutionAllowed: toBoolean(row.modelExecutionAllowed),
    inferenceEndpointExposed: toBoolean(row.inferenceEndpointExposed),
    productionIntegrationAllowed: toBoolean(row.productionIntegrationAllowed),
    canMutateBusinessRecords: toBoolean(row.canMutateBusinessRecords),
    createdByUserId: row.createdByUserId as string | number | null,
    finalReviewerDisplayName: row.finalReviewerDisplayName == null ? null : String(row.finalReviewerDisplayName),
    createdAt: String(row.createdAt || ""),
  };
};


export const mapLatestAuditSnapshotRow = (row: Record<string, unknown> | undefined): OfflineArtifactFinalizationChainAuditSnapshotRecord | null => {
  if (!row) return null;
  return {
    id: Number(row.id),
    finalizationId: Number(row.finalizationId),
    retentionGovernanceArchiveId: Number(row.retentionGovernanceArchiveId),
    retentionGovernanceReviewId: Number(row.retentionGovernanceReviewId),
    retentionPolicyEvidenceId: Number(row.retentionPolicyEvidenceId),
    archivePackId: Number(row.archivePackId),
    signoffId: Number(row.signoffId),
    binderId: Number(row.binderId),
    artifactId: Number(row.artifactId),
    artifactSha256: String(row.artifactSha256 || ""),
    modelKey: String(row.modelKey || ""),
    modelVersion: String(row.modelVersion || ""),
    signedFinalizationReadinessHash: String(row.signedFinalizationReadinessHash || ""),
    auditSnapshotDecision: String(row.auditSnapshotDecision || ""),
    auditSnapshotStatus: String(row.auditSnapshotStatus || ""),
    snapshotPurpose: String(row.snapshotPurpose || ""),
    snapshotTimestamp: String(row.snapshotTimestamp || ""),
    auditReviewerNotes: String(row.auditReviewerNotes || ""),
    rejectionReason: row.rejectionReason == null ? null : String(row.rejectionReason),
    finalChainDigestJson: parseJson<Record<string, unknown>>(row.finalChainDigestJson, {}),
    reviewerTrailDigestJson: parseJson<Record<string, unknown>>(row.reviewerTrailDigestJson, {}),
    immutableEvidenceSummaryJson: parseJson<Record<string, unknown>>(row.immutableEvidenceSummaryJson, {}),
    evidenceIndexJson: parseJson<Record<string, unknown>>(row.evidenceIndexJson, {}),
    safetyNotes: parseJson<string[]>(row.safetyNotesJson, []),
    signedAuditSnapshotHash: String(row.signedAuditSnapshotHash || ""),
    retentionJobScheduled: toBoolean(row.retentionJobScheduled),
    deletionOrPurgeAllowed: toBoolean(row.deletionOrPurgeAllowed),
    archiveFileCreated: toBoolean(row.archiveFileCreated),
    artifactBytesIncluded: toBoolean(row.artifactBytesIncluded),
    artifactExecutionAllowed: toBoolean(row.artifactExecutionAllowed),
    artifactAutoActivationAllowed: toBoolean(row.artifactAutoActivationAllowed),
    modelExecutionAllowed: toBoolean(row.modelExecutionAllowed),
    inferenceEndpointExposed: toBoolean(row.inferenceEndpointExposed),
    productionIntegrationAllowed: toBoolean(row.productionIntegrationAllowed),
    canMutateBusinessRecords: toBoolean(row.canMutateBusinessRecords),
    createdByUserId: row.createdByUserId as string | number | null,
    auditReviewerDisplayName: row.auditReviewerDisplayName == null ? null : String(row.auditReviewerDisplayName),
    createdAt: String(row.createdAt || ""),
  };
};



export const mapLatestAuditSnapshotGovernanceSignoffRow = (row: Record<string, unknown> | undefined): OfflineArtifactAuditSnapshotGovernanceSignoffRecord | null => {
  if (!row) return null;
  return {
    id: Number(row.id),
    auditSnapshotId: Number(row.auditSnapshotId),
    finalizationId: Number(row.finalizationId),
    retentionGovernanceArchiveId: Number(row.retentionGovernanceArchiveId),
    retentionGovernanceReviewId: Number(row.retentionGovernanceReviewId),
    retentionPolicyEvidenceId: Number(row.retentionPolicyEvidenceId),
    archivePackId: Number(row.archivePackId),
    signoffId: Number(row.signoffId),
    binderId: Number(row.binderId),
    artifactId: Number(row.artifactId),
    artifactSha256: String(row.artifactSha256 || ""),
    modelKey: String(row.modelKey || ""),
    modelVersion: String(row.modelVersion || ""),
    signedAuditSnapshotHash: String(row.signedAuditSnapshotHash || ""),
    signoffDecision: String(row.signoffDecision || ""),
    signoffStatus: String(row.signoffStatus || ""),
    signoffPurpose: String(row.signoffPurpose || ""),
    auditReviewerSignoffNotes: String(row.auditReviewerSignoffNotes || ""),
    exceptionNotes: row.exceptionNotes == null ? null : String(row.exceptionNotes),
    rejectionReason: row.rejectionReason == null ? null : String(row.rejectionReason),
    snapshotAcceptanceJson: parseJson<Record<string, unknown>>(row.snapshotAcceptanceJson, {}),
    evidenceConfidenceJson: parseJson<Record<string, unknown>>(row.evidenceConfidenceJson, {}),
    exceptionNotesJson: parseJson<Record<string, unknown>>(row.exceptionNotesJson, {}),
    safetyNotes: parseJson<string[]>(row.safetyNotesJson, []),
    signedAuditSnapshotGovernanceHash: String(row.signedAuditSnapshotGovernanceHash || ""),
    retentionJobScheduled: toBoolean(row.retentionJobScheduled),
    deletionOrPurgeAllowed: toBoolean(row.deletionOrPurgeAllowed),
    archiveFileCreated: toBoolean(row.archiveFileCreated),
    artifactBytesIncluded: toBoolean(row.artifactBytesIncluded),
    artifactExecutionAllowed: toBoolean(row.artifactExecutionAllowed),
    artifactAutoActivationAllowed: toBoolean(row.artifactAutoActivationAllowed),
    modelExecutionAllowed: toBoolean(row.modelExecutionAllowed),
    inferenceEndpointExposed: toBoolean(row.inferenceEndpointExposed),
    productionIntegrationAllowed: toBoolean(row.productionIntegrationAllowed),
    canMutateBusinessRecords: toBoolean(row.canMutateBusinessRecords),
    createdByUserId: row.createdByUserId as string | number | null,
    governanceSignerDisplayName: row.governanceSignerDisplayName == null ? null : String(row.governanceSignerDisplayName),
    createdAt: String(row.createdAt || ""),
  };
};

export const mapLatestAuditSnapshotGovernanceArchiveRow = (row: Record<string, unknown> | undefined): OfflineArtifactAuditSnapshotGovernanceArchiveRecord | null => {
  if (!row) return null;
  return {
    id: Number(row.id),
    auditSnapshotGovernanceSignoffId: Number(row.auditSnapshotGovernanceSignoffId),
    auditSnapshotId: Number(row.auditSnapshotId),
    finalizationId: Number(row.finalizationId),
    retentionGovernanceArchiveId: Number(row.retentionGovernanceArchiveId),
    retentionGovernanceReviewId: Number(row.retentionGovernanceReviewId),
    retentionPolicyEvidenceId: Number(row.retentionPolicyEvidenceId),
    archivePackId: Number(row.archivePackId),
    signoffId: Number(row.signoffId),
    binderId: Number(row.binderId),
    artifactId: Number(row.artifactId),
    artifactSha256: String(row.artifactSha256 || ""),
    modelKey: String(row.modelKey || ""),
    modelVersion: String(row.modelVersion || ""),
    signedAuditSnapshotGovernanceHash: String(row.signedAuditSnapshotGovernanceHash || ""),
    archiveDecision: String(row.archiveDecision || ""),
    archiveStatus: String(row.archiveStatus || ""),
    archivePurpose: String(row.archivePurpose || ""),
    archivistNotes: String(row.archivistNotes || ""),
    rejectionReason: row.rejectionReason == null ? null : String(row.rejectionReason),
    governanceArchiveManifestJson: parseJson<Record<string, unknown>>(row.governanceArchiveManifestJson, {}),
    signerTrailJson: parseJson<Record<string, unknown>>(row.signerTrailJson, {}),
    exceptionSummaryJson: parseJson<Record<string, unknown>>(row.exceptionSummaryJson, {}),
    evidenceConfidenceDigestJson: parseJson<Record<string, unknown>>(row.evidenceConfidenceDigestJson, {}),
    safetyNotes: parseJson<string[]>(row.safetyNotesJson, []),
    signedAuditGovernanceArchiveHash: String(row.signedAuditGovernanceArchiveHash || ""),
    retentionJobScheduled: toBoolean(row.retentionJobScheduled),
    deletionOrPurgeAllowed: toBoolean(row.deletionOrPurgeAllowed),
    archiveFileCreated: toBoolean(row.archiveFileCreated),
    artifactBytesIncluded: toBoolean(row.artifactBytesIncluded),
    artifactExecutionAllowed: toBoolean(row.artifactExecutionAllowed),
    artifactAutoActivationAllowed: toBoolean(row.artifactAutoActivationAllowed),
    modelExecutionAllowed: toBoolean(row.modelExecutionAllowed),
    inferenceEndpointExposed: toBoolean(row.inferenceEndpointExposed),
    productionIntegrationAllowed: toBoolean(row.productionIntegrationAllowed),
    canMutateBusinessRecords: toBoolean(row.canMutateBusinessRecords),
    createdByUserId: row.createdByUserId as string | number | null,
    archivistDisplayName: row.archivistDisplayName == null ? null : String(row.archivistDisplayName),
    createdAt: String(row.createdAt || ""),
  };
};

export const offlineArtifactSelect = `
  SELECT id,
         artifact_name AS artifactName,
         artifact_kind AS artifactKind,
         model_key AS modelKey,
         model_version AS modelVersion,
         source,
         declared_format AS declaredFormat,
         declared_purpose AS declaredPurpose,
         related_model_import_id AS relatedModelImportId,
         sha256,
         size_bytes AS sizeBytes,
         metadata_json AS metadataJson,
         artifact_payload_json AS artifactPayloadJson,
         validation_messages_json AS validationMessagesJson,
         safety_notes_json AS safetyNotesJson,
         intake_status AS intakeStatus,
         quarantine_status AS quarantineStatus,
         artifact_execution_allowed AS artifactExecutionAllowed,
         artifact_auto_activation_allowed AS artifactAutoActivationAllowed,
         model_execution_allowed AS modelExecutionAllowed,
         inference_endpoint_exposed AS inferenceEndpointExposed,
         production_integration_allowed AS productionIntegrationAllowed,
         can_mutate_business_records AS canMutateBusinessRecords,
         created_at AS createdAt,
         created_by_user_id AS createdByUserId,
         updated_at AS updatedAt
  FROM ml_offline_artifacts
`;

