import React from 'react';
import PartnerDetailHeaderSection from './PartnerDetailHeaderSection';
import PartnerPhoneCapitalSection from './PartnerPhoneCapitalSection';
import PartnerOverviewKpiSection from './PartnerOverviewKpiSection';
import PartnerAccountingBreakdownSection from './PartnerAccountingBreakdownSection';
import PartnerSettlementWorkspaceSection from './PartnerSettlementSubmitUiIntegrationSection';
import PartnerTelegramConversationSection, { type PartnerTelegramConversationContext } from './PartnerTelegramConversationSection';
import PartnerLedgerWorkspaceSection, { type PartnerLedgerWorkspaceContext } from './PartnerLedgerWorkspaceSection';
import PartnerPurchaseHistorySection, { type PartnerPurchaseHistoryContext } from './PartnerPurchaseHistorySection';
import PartnerDetailModalStack, { type PartnerDetailModalStackContext } from './PartnerDetailModalStack';
import { PeopleDetailPageShell, PeopleDetailSurface } from '@/components/people/PeopleDetailFoundation';

type Props = {
  ctx: PartnerTelegramConversationContext &
    PartnerLedgerWorkspaceContext &
    PartnerPurchaseHistoryContext &
    PartnerDetailModalStackContext;
};

const PartnerDetailRender: React.FC<Props> = ({ ctx }) => {
  const {
    BULK_SETTLEMENT_LAST_NOTE_KEY,
    Button,
    FinancialProgressBar,
    FormErrorSummary,
    MessageComposerModal,
    Modal,
    ModalActions,
    ModalField,
    Notification,
    PARTNER_TYPES,
    PriceInput,
    ShamsiDatePicker,
    TelegramLinkModal,
    activeBatchLedgerMetrics,
    activeLedgerBatchId,
    amount,
    applyBulkSettlementNoteTemplate,
    assetKey,
    balance,
    bulkSettlementAmount,
    bulkSettlementAmountValue,
    bulkSettlementBatchId,
    bulkSettlementDistribution,
    bulkSettlementIdSet,
    bulkSettlementNote,
    bulkSettlementNoteTemplates,
    bulkSettlementPriority,
    closedSaleFiles,
    credit,
    current,
    currentUser,
    customerInstallmentRemainingAmount,
    debit,
    deepLink,
    editFormErrors,
    editingEntry,
    editingPartner,
    el,
    entries,
    entry,
    errors,
    expanded,
    expandedLedgerEntryId,
    expandedPhoneSettlementTimelineId,
    expandedPurchaseHistoryId,
    exportPartnerCapitalRows,
    filteredLedgerEntries,
    filteredSoldPhoneDailyPriceDeltaTotal,
    filteredSoldPhoneDailyPriceRows,
    filteredSoldPhoneDailyPriceTotal,
    filteredSoldPhoneProductSettlementBalanceTotal,
    filteredSoldPhoneProductSettlementPaidTotal,
    formatCurrencyText,
    formatIsoToShamsi,
    formatIsoToShamsiDateTime,
    formatLedgerTransactionDate,
    formatPartnerLedgerCurrency,
    formatPrice,
    fullSettlementAmounts,
    getBalanceLabel,
    getBalanceState,
    getLedgerSystemKind,
    getPartnerCapitalMeta,
    getPurchaseSystemId,
    getSaleClosureMeta,
    groupedLedgerEntries,
    handleBulkSettlementAmountChange,
    handleBulkSettlementClear,
    handleBulkSettlementSelectAll,
    handleBulkSettlementSubmit,
    handleEditInputChange,
    handleEditSubmit,
    handleExportActiveBatchCsv,
    handleFullSettlementPhoneSubmit,
    handleLedgerDelete,
    handleLedgerEdit,
    handleLedgerInputChange,
    handleLedgerSubmit,
    handlePhoneSettlementAmountChange,
    handlePhoneSettlementSubmit,
    handlePrintActiveBatch,
    id,
    identifier,
    imei,
    initialPurchasePrice,
    inputClass,
    isDeletingEntry,
    isEditModalOpen,
    isFullPhoneSettlementModalOpen,
    isSettlementManualConfirmationModalOpen,
    isLedgerColumnPickerOpen,
    isLedgerModalOpen,
    isMessageModalOpen,
    isSubmittingBulkSettlement,
    isSubmittingEdit,
    isSubmittingFullSettlementPhoneId,
    isSubmittingLedger,
    isSubmittingPhoneSettlement,
    item,
    jumpToFirstPartnerTgResult,
    kind,
    lastBulkSettlementNote,
    lastSubmittedBulkSettlementBatchId,
    ledger,
    ledgerColumnPickerButtonRef,
    ledgerColumnPickerPanelRef,
    ledgerDateSelected,
    ledgerDetailLines,
    ledgerDirection,
    ledgerDisplayMode,
    ledgerEmptyState,
    ledgerFormErrors,
    ledgerRange,
    ledgerRecordedAt,
    ledgerSearch,
    ledgerSettlementBatchOptions,
    ledgerSystemFilter,
    ledgerSystemOptions,
    ledgerTableColumnCount,
    ledgerTypeBadge,
    ledgerViewFilter,
    ledgerVisibleColumns,
    name,
    nearBottom,
    newLedgerEntry,
    nextValue,
    note,
    notification,
    num,
    openEditModal,
    openLedgerModal,
    openPartnerQrLinkModal,
    openSoldPhoneSettlementRows,
    openTelegramReport,
    parsePartnerLedgerMeta,
    partnerCapitalReturnedAmount,
    partnerCapitalWaitingAmount,
    partnerRegisteredDateLabel,
    partnerRiskFactors,
    partnerTgConvError,
    partnerTgConvItems,
    partnerTgConvLoading,
    partnerTgDirectionFilter,
    partnerTgFilteredConvItems,
    partnerTgNewSinceScroll,
    partnerTgPreset,
    partnerTgQuickReply,
    partnerTgTimelineRef,
    partnerTypeLabel,
    partnerUnifiedStatusTotals,
    phone,
    phoneId,
    phoneSettlementAmount,
    phoneSettlementBalance,
    phoneSettlementDateSelected,
    phoneSettlementErrors,
    phoneSettlementItem,
    phoneSettlementNote,
    phoneSettlementNoteTemplates,
    phoneSettlementPaidAmount,
    phoneSettlementPaymentsByPhoneId,
    prefillChannels,
    prefillMessageText,
    profile,
    purchaseHistoryBySystemId,
    purchaseHistoryCounts,
    purchaseHistoryFilter,
    purchaseHistoryVisible,
    qty,
    readStoredCurrencyUnit,
    recommendation,
    recordedAt,
    referenceType,
    relatedPurchase,
    renderLedgerTransactionCard,
    renderPhoneSaleSourceLink,
    rows,
    saleId,
    score,
    selectedBulkSettlementBalanceTotal,
    selectedBulkSettlementRows,
    setActiveLedgerBatchId,
    setBulkSettlementAmount,
    setBulkSettlementNote,
    setBulkSettlementPhoneIds,
    setBulkSettlementPriority,
    setEditFormErrors,
    setEditingEntry,
    setEditingPartner,
    setExpandedLedgerEntryId,
    setExpandedPhoneSettlementTimelineId,
    setExpandedPurchaseHistoryId,
    setFullSettlementAmounts,
    setIsEditModalOpen,
    setIsFullPhoneSettlementModalOpen,
    setIsSettlementManualConfirmationModalOpen,
    setIsLedgerColumnPickerOpen,
    setIsLedgerModalOpen,
    setIsMessageModalOpen,
    setLastBulkSettlementNote,
    setLedgerDateSelected,
    setLedgerDirection,
    setLedgerDisplayMode,
    setLedgerRange,
    setLedgerSearch,
    setLedgerSystemFilter,
    setLedgerViewFilter,
    setLedgerVisibleColumns,
    setNotification,
    setPartnerTgDirectionFilter,
    setPartnerTgNewSinceScroll,
    setPartnerTgQuickReply,
    setPartnerTgSearchQuery,
    setPhoneSettlementAmount,
    setPhoneSettlementDateSelected,
    setPhoneSettlementErrors,
    setPhoneSettlementItem,
    setPhoneSettlementNote,
    setPrefillChannels,
    setPrefillMessageText,
    setPurchaseHistoryFilter,
    setSoldPhoneCapitalSearch,
    setSoldPhoneCapitalSort,
    setSoldPhoneSettlementFilter,
    setTgQrOpen,
    settlementPurchasePrice,
    soldPhoneCapitalSearchRef,
    soldPhoneCapitalSort,
    soldPhoneDailyPriceRows,
    soldPhoneSettlementFilter,
    soldPhoneSettlementFilterCounts,
    soldPhonesCurrentPurchaseAmount,
    soldPhonesCurrentPurchaseBalance,
    soldPhonesInitialPurchaseAmount,
    soldPhonesProductSettlementBalance,
    soldPhonesProductSettlementPaidAmount,
    sourceLabel,
    systemId,
    target,
    text,
    tgBotUsernameMissing,
    tgQrDeepLink,
    tgQrLoading,
    tgQrOpen,
    token,
    tone,
    total,
    totalCredit,
    totalCredits,
    totalDebit,
    totalDebits,
    unallocatedPartnerPaymentAmount,
    unsoldInventoryAmount,
    value,
  } = ctx;

  return (
    <PeopleDetailPageShell
      entity="partner"
      data-ui-partner-detail-page-root="true"
      data-ui-people-page="partner-detail"
    >
      <Notification message={notification} onClose={() => setNotification(null)} />

      <PeopleDetailSurface section="hero" data-ui-people-surface="detail-hero">
        <PartnerDetailHeaderSection ctx={ctx} />
      </PeopleDetailSurface>

      <div className="space-y-4" data-ui-partner-detail-shell="operational-content">
        <PartnerOverviewKpiSection ctx={ctx} />
        <PartnerAccountingBreakdownSection ctx={ctx} />
        <PartnerPhoneCapitalSection ctx={ctx} />
        <PartnerSettlementWorkspaceSection ctx={ctx} />
        <PartnerTelegramConversationSection ctx={ctx} />
        {/* Ledger */}
        <div id="partner-ledger-section" data-ui-people-ledger="partner">
          <PartnerLedgerWorkspaceSection ctx={ctx} />
        </div>
        <PartnerPurchaseHistorySection ctx={ctx} />
        <PartnerDetailModalStack ctx={ctx} />
      </div>
    </PeopleDetailPageShell>
  );
};

export default PartnerDetailRender;
