export type ShadowScoreMetadataStorageStatus = 'pass' | 'warning' | 'fail';

export type ShadowScoreMetadataScoreRole = 'candidate' | 'baseline';

export type ShadowScoreMetadataStorageIssue = {
  code: string;
  message: string;
  path: string;
};

export type ShadowScoreMetadataSafetyPolicy = {
  modelExecutionAllowed: false;
  runtimeInvocationAllowed: false;
  inferenceEndpointExposed: false;
  productionIntegrationAllowed: false;
  decisionAutomationAllowed: false;
  canChangeInventoryOrAccounting: false;
  canChangePricing: false;
  canChangeReports: false;
  canChangeLedger: false;
  canMutateBusinessRecords: false;
  artifactExecutionAllowed: false;
  artifactActivationAllowed: false;
  artifactBytesLoadingAllowed: false;
  rawTrainingCsvLoadingAllowed: false;
  automaticDeletionAllowed: false;
  purgeJobAllowed: false;
};

export type ShadowScoreMetadataFixtureRecord = {
  importRecordId?: string;
  shadowScoreId?: string;
  entityType?: string;
  entityId?: string;
  predictionType?: string;
  horizonDays?: number | null;
  candidateScore?: number | null;
  candidateLabel?: string | null;
  candidateConfidence?: number | null;
  scoreQuality?: string;
  modelKey?: string;
  modelVersion?: string;
  candidatePackageId?: string;
  sourceRowIndex?: number;
  sourceShadowRecordIndex?: number;
  sourceExportRecordHash?: string;
  scoreGeneratedAt?: string;
  exportGeneratedAt?: string;
  importFixtureGeneratedAt?: string;
  storageClass?: string;
  evidenceOnly?: boolean;
  automationAllowed?: boolean;
  businessMutationAllowed?: boolean;
  inventoryMutationAllowed?: boolean;
  accountingMutationAllowed?: boolean;
  pricingMutationAllowed?: boolean;
  ledgerMutationAllowed?: boolean;
  reportMutationAllowed?: boolean;
  artifactActivationAllowed?: boolean;
  modelExecutionAllowed?: boolean;
  inferenceEndpointExposed?: boolean;
  [key: string]: unknown;
};

export type ShadowScoreMetadataFixturePayload = {
  contractVersion?: string;
  fixtureKind?: string;
  fixtureId?: string;
  candidatePackageId?: string;
  scoreRole?: ShadowScoreMetadataScoreRole;
  baselineSource?: string;
  baselineKey?: string;
  baselineVersion?: string;
  baselineGeneratedAt?: string;
  baselinePayloadHash?: string;
  baselineValidationStatus?: string;
  baselinePayload?: unknown;
  modelKey?: string;
  modelVersion?: string;
  predictionType?: string;
  horizonDays?: number | null;
  generatedAt?: string;
  importMode?: string;
  evidenceOnly?: boolean;
  backendInferenceClaim?: string;
  artifactActivationClaim?: string;
  businessMutationClaim?: string;
  offlineExecutionReportHash?: string | null;
  candidateScoreOutputHash?: string | null;
  shadowScoreExportHash?: string | null;
  safetyPolicy?: Partial<ShadowScoreMetadataSafetyPolicy>;
  records?: ShadowScoreMetadataFixtureRecord[];
  warnings?: unknown[];
  errors?: unknown[];
  [key: string]: unknown;
};

export type ShadowScoreMetadataStorageValidationReport = {
  phase: 'Phase 14A';
  validationKind: 'metadata_only_shadow_score_storage_validation';
  status: ShadowScoreMetadataStorageStatus;
  metadataOnly: boolean;
  recordCount: number;
  validatedRecordCount: number;
  forbiddenFieldCount: number;
  warningCount: number;
  errorCount: number;
  warnings: ShadowScoreMetadataStorageIssue[];
  errors: ShadowScoreMetadataStorageIssue[];
  importPayloadHash: string;
  safetyPolicy: ShadowScoreMetadataSafetyPolicy | null;
  safetyFlags: {
    modelExecutionAllowed: false;
    inferenceEndpointExposed: false;
    artifactActivationAllowed: false;
    canMutateBusinessRecords: false;
  };
};

export type ShadowScoreMetadataStorageRecordInput = {
  importFixtureId: string;
  candidatePackageId: string;
  scoreRole?: ShadowScoreMetadataScoreRole;
  baselineSource?: string | null;
  baselineKey?: string | null;
  baselineVersion?: string | null;
  baselineGeneratedAt?: string | null;
  baselinePayloadHash?: string | null;
  baselineValidationStatus?: string | null;
  baselinePayload?: unknown;
  modelKey: string;
  modelVersion: string;
  predictionType: string;
  horizonDays?: number | null;
  entityType: string;
  entityId: string;
  sourceRowIndex: number;
  score?: number | null;
  label?: string | null;
  confidence?: number | null;
  scoreGeneratedAt?: string | null;
  scoreSource?: string | null;
  offlineExecutionReportHash?: string | null;
  candidateScoreOutputHash?: string | null;
  shadowScoreExportHash?: string | null;
  importPayloadHash: string;
  metadataOnly?: boolean | number;
  modelBinaryPresent?: boolean | number;
  rawCsvPresent?: boolean | number;
  inferenceDirectivePresent?: boolean | number;
  activationDirectivePresent?: boolean | number;
  businessMutationDirectivePresent?: boolean | number;
  forbiddenFieldCount?: number | null;
  validationStatus?: string | null;
  validationReport?: unknown;
  scorePayload?: unknown;
  safetyPolicy?: unknown;
  createdByUserId?: number | null;
};

export type StoredShadowScoreMetadataRecord = {
  id: number;
  importFixtureId: string;
  candidatePackageId: string;
  scoreRole?: ShadowScoreMetadataScoreRole;
  baselineSource?: string | null;
  baselineKey?: string | null;
  baselineVersion?: string | null;
  baselineGeneratedAt?: string | null;
  baselinePayloadHash?: string | null;
  baselineValidationStatus?: string | null;
  baselinePayload?: unknown;
  modelKey: string;
  modelVersion: string;
  predictionType: string;
  horizonDays: number | null;
  entityType: string;
  entityId: string;
  sourceRowIndex: number;
  score: number | null;
  label: string | null;
  confidence: number | null;
  scoreGeneratedAt: string | null;
  scoreSource: string;
  offlineExecutionReportHash: string | null;
  candidateScoreOutputHash: string | null;
  shadowScoreExportHash: string | null;
  importPayloadHash: string;
  metadataOnly: boolean;
  modelBinaryPresent: boolean;
  rawCsvPresent: boolean;
  inferenceDirectivePresent: boolean;
  activationDirectivePresent: boolean;
  businessMutationDirectivePresent: boolean;
  forbiddenFieldCount: number;
  validationStatus: string;
  validationReport: unknown;
  scorePayload: unknown;
  safetyPolicy: unknown;
  createdAt: string;
  createdByUserId: number | null;
};

export type ShadowScoreMetadataRecordWriteResult = {
  status: ShadowScoreMetadataStorageStatus;
  inserted: boolean;
  duplicate: boolean;
  rejected: boolean;
  reason: string | null;
  record: StoredShadowScoreMetadataRecord | null;
  validation: ShadowScoreMetadataStorageValidationReport | null;
};

export type ShadowScoreMetadataBatchWriteResult = {
  status: ShadowScoreMetadataStorageStatus;
  requestedCount: number;
  insertedCount: number;
  duplicateCount: number;
  rejectedCount: number;
  records: StoredShadowScoreMetadataRecord[];
  results: ShadowScoreMetadataRecordWriteResult[];
};

export type ShadowScoreMetadataStorageServiceResult = {
  phase: 'Phase 14A';
  storageKind: 'metadata_only_shadow_score_storage_apply';
  status: ShadowScoreMetadataStorageStatus;
  validation: ShadowScoreMetadataStorageValidationReport;
  requestedRecordCount: number;
  normalizedRecordCount: number;
  insertedCount: number;
  duplicateCount: number;
  rejectedCount: number;
  records: StoredShadowScoreMetadataRecord[];
  safetyPolicy: ShadowScoreMetadataSafetyPolicy | null;
  modelExecutionAllowed: false;
  inferenceEndpointExposed: false;
  artifactActivationAllowed: false;
  canMutateBusinessRecords: false;
};
