import { createPredictiveSchema } from "./predictive.schema";
import { createMlDatasetsSchema } from "./mlDatasets.schema";
import { createMlBenchmarksSchema } from "./mlBenchmarks.schema";
import { createMlTrainingPackagesSchema } from "./mlTrainingPackages.schema";
import { createMlCandidateModelPackagesSchema } from "./mlCandidateModelPackages.schema";
import { createMlCandidateEvaluationMetadataImportsSchema } from "./mlCandidateEvaluationMetadataImports.schema";
import { createMlWorkbenchImportResultsSchema } from "./mlWorkbenchImportResults.schema";
import { createMlWorkbenchImportResultAnnotationsSchema } from "./mlWorkbenchImportResultAnnotations.schema";
import { createMlCandidatePackageIntakeBindersSchema } from "./mlCandidatePackageIntakeBinders.schema";
import { createMlCandidatePackageHumanReviewSignoffsSchema } from "./mlCandidatePackageHumanReviewSignoffs.schema";
import { createMlCandidatePackageHumanSignoffArchivePacksSchema } from "./mlCandidatePackageHumanSignoffArchivePacks.schema";
import { createMlCandidatePackageArchiveRetentionReviewBindersSchema } from "./mlCandidatePackageArchiveRetentionReviewBinders.schema";
import { createMlCandidatePackageArchiveRetentionReviewSignoffsSchema } from "./mlCandidatePackageArchiveRetentionReviewSignoffs.schema";
import { createMlCandidatePackageRetentionSignoffArchivePacksSchema } from "./mlCandidatePackageRetentionSignoffArchivePacks.schema";
import { createMlCandidatePackageRetentionArchiveFinalAuditSnapshotsSchema } from "./mlCandidatePackageRetentionArchiveFinalAuditSnapshots.schema";
import { createMlCandidatePackageFinalAuditSnapshotGovernanceSignoffsSchema } from "./mlCandidatePackageFinalAuditSnapshotGovernanceSignoffs.schema";
import { createMlCandidatePackageGovernanceSignoffArchivePacksSchema } from "./mlCandidatePackageGovernanceSignoffArchivePacks.schema";
import { createMlCandidatePackageGovernanceSignoffArchiveFinalizationSummaryPacksSchema } from "./mlCandidatePackageGovernanceSignoffArchiveFinalizationSummaryPacks.schema";
import { createMlModelImportsSchema } from "./mlModelImports.schema";
import { createMlApprovalsSchema } from "./mlApprovals.schema";
import { createMlShadowSchema } from "./mlShadow.schema";
import { createMlOfflinePilotSchema } from "./mlOfflinePilot.schema";
import { createMlProductionReadinessSchema } from "./mlProductionReadiness.schema";
import { createMlSafeInferenceSchema } from "./mlSafeInference.schema";
import { createMlShadowAdapterSchema } from "./mlShadowAdapter.schema";
import { createMlShadowObservationEventStoreSchema } from "./mlShadowObservationEventStore.schema";
import { createMlShadowObservationReviewDecisionLogSchema } from "./mlShadowObservationReviewDecisionLog.schema";
import { createMlShadowObservationBinderReviewSignoffGateSchema } from "./mlShadowObservationBinderReviewSignoffGate.schema";
import { createMlShadowRuntimeSchema } from "./mlShadowRuntime.schema";
import { createMlShadowRuntimeReplaySchema } from "./mlShadowRuntimeReplay.schema";
import { createMlArtifactIntakeSchema } from "./mlArtifactIntake.schema";
import { createMlArtifactQuarantineReviewSchema } from "./mlArtifactQuarantineReview.schema";
import { createMlArtifactReviewBinderSchema } from "./mlArtifactReviewBinder.schema";
import { createMlArtifactReviewBinderGovernanceSignoffSchema } from "./mlArtifactReviewBinderGovernanceSignoff.schema";
import { createMlArtifactGovernanceSignoffArchivePackSchema } from "./mlArtifactGovernanceSignoffArchivePack.schema";
import { createMlArtifactArchivePackRetentionPolicyEvidenceSchema } from "./mlArtifactArchivePackRetentionPolicyEvidence.schema";
import { createMlArtifactRetentionEvidenceGovernanceReviewSchema } from "./mlArtifactRetentionEvidenceGovernanceReview.schema";
import { createMlArtifactRetentionGovernanceReviewArchiveSchema } from "./mlArtifactRetentionGovernanceReviewArchive.schema";
import { createMlArtifactGovernanceArchiveChainFinalizationSchema } from "./mlArtifactGovernanceArchiveChainFinalization.schema";
import { createMlArtifactFinalizationChainAuditSnapshotSchema } from "./mlArtifactFinalizationChainAuditSnapshot.schema";
import { createMlArtifactAuditSnapshotGovernanceSignoffSchema } from "./mlArtifactAuditSnapshotGovernanceSignoff.schema";
import { createMlArtifactAuditSnapshotGovernanceArchiveSchema } from "./mlArtifactAuditSnapshotGovernanceArchive.schema";
import { createMlOfflineArtifactValidationSchema } from "./mlOfflineArtifactValidation.schema";
import { createMlOfflineArtifactValidationReviewQueueSchema } from "./mlOfflineArtifactValidationReviewQueue.schema";
import { createMlOfflineArtifactValidationReviewerAssignmentUxSchema } from "./mlOfflineArtifactValidationReviewerAssignmentUx.schema";
import { createMlOfflineArtifactValidationEvidenceReviewPackSchema } from "./mlOfflineArtifactValidationEvidenceReviewPack.schema";
import { createMlOfflineArtifactValidationEvidenceGapClosureMatrixSchema } from "./mlOfflineArtifactValidationEvidenceGapClosureMatrix.schema";
import { createMlOfflineArtifactValidationEvidenceClosureSignoffPackSchema } from "./mlOfflineArtifactValidationEvidenceClosureSignoffPack.schema";
import { createMlOfflineArtifactValidationFutureShadowEligibilityGateSchema } from "./mlOfflineArtifactValidationFutureShadowEligibilityGate.schema";
import { createMlOfflineArtifactValidationFutureShadowEligibilityReviewBinderSchema } from "./mlOfflineArtifactValidationFutureShadowEligibilityReviewBinder.schema";
import { createMlOfflineArtifactValidationFutureShadowReviewBinderRoutingSummaryPackSchema } from "./mlOfflineArtifactValidationFutureShadowReviewBinderRoutingSummaryPack.schema";
import { createMlOfflineArtifactValidationFutureShadowBoardReviewPacketSchema } from "./mlOfflineArtifactValidationFutureShadowBoardReviewPacket.schema";
import { createMlOfflineArtifactValidationFutureShadowBoardReviewDecisionLogSchema } from "./mlOfflineArtifactValidationFutureShadowBoardReviewDecisionLog.schema";
import { createMlShadowScoreMetadataRecordsSchema } from "./mlShadowScoreMetadataRecords.schema";
import { createMlShadowScoreComparisonSummariesSchema } from "./mlShadowScoreComparisonSummaries.schema";
import { createMlShadowScoreImportApplyReceiptsSchema } from "./mlShadowScoreImportApplyReceipts.schema";
import { createMlShadowScoreImportApplyReceiptExportPackageSnapshotsSchema } from "./mlShadowScoreImportApplyReceiptExportPackageSnapshots.schema";

export const createIntelligenceSchema = async (): Promise<void> => {
  await createPredictiveSchema();
  await createMlDatasetsSchema();
  await createMlBenchmarksSchema();
  await createMlTrainingPackagesSchema();
  await createMlCandidateModelPackagesSchema();
  await createMlCandidateEvaluationMetadataImportsSchema();
  await createMlWorkbenchImportResultsSchema();
  await createMlWorkbenchImportResultAnnotationsSchema();
  await createMlCandidatePackageIntakeBindersSchema();
  await createMlCandidatePackageHumanReviewSignoffsSchema();
  await createMlCandidatePackageHumanSignoffArchivePacksSchema();
  await createMlCandidatePackageArchiveRetentionReviewBindersSchema();
  await createMlCandidatePackageArchiveRetentionReviewSignoffsSchema();
  await createMlCandidatePackageRetentionSignoffArchivePacksSchema();
  await createMlCandidatePackageRetentionArchiveFinalAuditSnapshotsSchema();
  await createMlCandidatePackageFinalAuditSnapshotGovernanceSignoffsSchema();
  await createMlCandidatePackageGovernanceSignoffArchivePacksSchema();
  await createMlCandidatePackageGovernanceSignoffArchiveFinalizationSummaryPacksSchema();
  await createMlModelImportsSchema();
  await createMlApprovalsSchema();
  await createMlShadowSchema();
  await createMlOfflinePilotSchema();
  await createMlProductionReadinessSchema();
  await createMlSafeInferenceSchema();
  await createMlShadowAdapterSchema();
  await createMlShadowObservationEventStoreSchema();
  await createMlShadowObservationReviewDecisionLogSchema();
  await createMlShadowObservationBinderReviewSignoffGateSchema();
  await createMlShadowRuntimeSchema();
  await createMlShadowRuntimeReplaySchema();
  await createMlArtifactIntakeSchema();
  await createMlArtifactQuarantineReviewSchema();
  await createMlArtifactReviewBinderSchema();
  await createMlArtifactReviewBinderGovernanceSignoffSchema();
  await createMlArtifactGovernanceSignoffArchivePackSchema();
  await createMlArtifactArchivePackRetentionPolicyEvidenceSchema();
  await createMlArtifactRetentionEvidenceGovernanceReviewSchema();
  await createMlArtifactRetentionGovernanceReviewArchiveSchema();
  await createMlArtifactGovernanceArchiveChainFinalizationSchema();
  await createMlArtifactFinalizationChainAuditSnapshotSchema();
  await createMlArtifactAuditSnapshotGovernanceSignoffSchema();
  await createMlArtifactAuditSnapshotGovernanceArchiveSchema();
  await createMlOfflineArtifactValidationSchema();
  await createMlOfflineArtifactValidationReviewQueueSchema();
  await createMlOfflineArtifactValidationReviewerAssignmentUxSchema();
  await createMlOfflineArtifactValidationEvidenceReviewPackSchema();
  await createMlOfflineArtifactValidationEvidenceGapClosureMatrixSchema();
  await createMlOfflineArtifactValidationEvidenceClosureSignoffPackSchema();
  await createMlOfflineArtifactValidationFutureShadowEligibilityGateSchema();
  await createMlOfflineArtifactValidationFutureShadowEligibilityReviewBinderSchema();
  await createMlOfflineArtifactValidationFutureShadowReviewBinderRoutingSummaryPackSchema();
  await createMlOfflineArtifactValidationFutureShadowBoardReviewPacketSchema();
  await createMlOfflineArtifactValidationFutureShadowBoardReviewDecisionLogSchema();
  await createMlShadowScoreMetadataRecordsSchema();
  await createMlShadowScoreComparisonSummariesSchema();
  await createMlShadowScoreImportApplyReceiptsSchema();
  await createMlShadowScoreImportApplyReceiptExportPackageSnapshotsSchema();
};
