import { getShadowRuntimeSafetyGate } from "./shadowRuntimeSafety";

const PHASE_LABEL = "Phase 5E — Offline Candidate Output Contract Fixture Pack" as const;
const FIXTURE_PACK_KEY = "shadow_runtime_candidate_output_contract_fixture_pack_v1" as const;

export type CandidateOutputFixtureValidationIssue = {
  field: string;
  message: string;
};

export type CandidateOutputContractFixture = {
  fixtureKey: string;
  fixtureVersion: "v1";
  fixtureOnly: true;
  modelKey: string;
  modelVersion: string;
  predictionType: string;
  entityType: string;
  entityId: string | number | null;
  horizonDays: number | null;
  candidateScore: number | null;
  candidateLabel: string | null;
  candidateConfidence: number | null;
  baselineScore: number | null;
  deltaFromBaseline: number | null;
  rawCandidateOutput: Record<string, unknown> | null;
  explanation: string;
  safetyNotes: string[];
  generatedAt: string;
  modelExecutionAttempted: false;
  modelExecutionAllowed: false;
  inferenceEndpointExposed: false;
  productionIntegrationAllowed: false;
  decisionAutomationAllowed: false;
  businessMutationAllowed: false;
  approvalAllowed: false;
  activationAllowed: false;
  promotionAllowed: false;
  pricingMutationAllowed: false;
  reportMutationAllowed: false;
  ledgerMutationAllowed: false;
};

const FORBIDDEN_OUTPUT_FIELDS = [
  "approved",
  "approvalStatus",
  "activate",
  "activationStatus",
  "promote",
  "promotionStatus",
  "productionDecision",
  "decision",
  "autoDecision",
  "price",
  "newPrice",
  "salePrice",
  "purchasePrice",
  "inventoryMutation",
  "accountingMutation",
  "ledgerMutation",
  "reportMutation",
  "customerMutation",
  "partnerMutation",
] as const;

const buildFixture = (overrides: Partial<CandidateOutputContractFixture>): CandidateOutputContractFixture => ({
  fixtureKey: "inventory_stockout_candidate_output_shape_v1",
  fixtureVersion: "v1",
  fixtureOnly: true,
  modelKey: "external_candidate_fixture_only",
  modelVersion: "fixture-v1",
  predictionType: "inventory_stockout_risk",
  entityType: "product",
  entityId: "fixture-product-001",
  horizonDays: 7,
  candidateScore: 0.42,
  candidateLabel: "candidate_fixture_only",
  candidateConfidence: 0.61,
  baselineScore: 0.38,
  deltaFromBaseline: 0.04,
  rawCandidateOutput: {
    score: 0.42,
    label: "candidate_fixture_only",
    confidence: 0.61,
    source: "offline_contract_fixture",
  },
  explanation: "Offline fixture-only candidate output contract sample. It is not generated by a live model and cannot create a production decision.",
  safetyNotes: [
    "Fixture pack is offline-only.",
    "No real model execution is enabled.",
    "No artifact loading is allowed.",
    "No inference endpoint is exposed.",
    "No approval, activation, promotion, pricing, reporting, ledger, inventory, or accounting mutation is possible.",
  ],
  generatedAt: new Date().toISOString(),
  modelExecutionAttempted: false,
  modelExecutionAllowed: false,
  inferenceEndpointExposed: false,
  productionIntegrationAllowed: false,
  decisionAutomationAllowed: false,
  businessMutationAllowed: false,
  approvalAllowed: false,
  activationAllowed: false,
  promotionAllowed: false,
  pricingMutationAllowed: false,
  reportMutationAllowed: false,
  ledgerMutationAllowed: false,
  ...overrides,
});

export const buildShadowRuntimeCandidateOutputContractFixtures = (): CandidateOutputContractFixture[] => [
  buildFixture({
    fixtureKey: "inventory_stockout_candidate_output_shape_v1",
    predictionType: "inventory_stockout_risk",
    entityType: "product",
    entityId: "fixture-product-001",
    candidateScore: 0.42,
    candidateLabel: "candidate_fixture_only",
    candidateConfidence: 0.61,
    baselineScore: 0.38,
    deltaFromBaseline: 0.04,
  }),
  buildFixture({
    fixtureKey: "phone_sale_probability_candidate_output_shape_v1",
    predictionType: "phone_sale_probability",
    entityType: "phone",
    entityId: "fixture-phone-001",
    horizonDays: 14,
    candidateScore: 0.57,
    candidateLabel: "candidate_fixture_only",
    candidateConfidence: 0.66,
    baselineScore: 0.52,
    deltaFromBaseline: 0.05,
  }),
  buildFixture({
    fixtureKey: "cashflow_risk_candidate_output_shape_v1",
    predictionType: "cashflow_risk",
    entityType: "store",
    entityId: null,
    horizonDays: 30,
    candidateScore: 0.31,
    candidateLabel: "candidate_fixture_only",
    candidateConfidence: 0.58,
    baselineScore: 0.35,
    deltaFromBaseline: -0.04,
  }),
];

const isPlainObject = (value: unknown): value is Record<string, unknown> => Boolean(
  value && typeof value === "object" && !Array.isArray(value),
);

const assertNumberOrNull = (
  value: unknown,
  field: string,
  issues: CandidateOutputFixtureValidationIssue[],
  options: { min?: number; max?: number } = {},
) => {
  if (value == null) return;
  if (typeof value !== "number" || !Number.isFinite(value)) {
    issues.push({ field, message: `${field} must be a finite number or null.` });
    return;
  }
  if (options.min != null && value < options.min) {
    issues.push({ field, message: `${field} must be greater than or equal to ${options.min}.` });
  }
  if (options.max != null && value > options.max) {
    issues.push({ field, message: `${field} must be less than or equal to ${options.max}.` });
  }
};

const assertFalse = (value: unknown, field: string, issues: CandidateOutputFixtureValidationIssue[]) => {
  if (value !== false) {
    issues.push({ field, message: `${field} must remain false in the offline fixture pack.` });
  }
};

export const validateShadowRuntimeCandidateOutputFixture = (candidateOutput: unknown) => {
  const issues: CandidateOutputFixtureValidationIssue[] = [];

  if (!isPlainObject(candidateOutput)) {
    return {
      valid: false,
      status: "invalid" as const,
      issueCount: 1,
      issues: [{ field: "candidateOutput", message: "Candidate output must be a plain object." }],
      normalized: null,
    };
  }

  const requiredTextFields = [
    "fixtureKey",
    "fixtureVersion",
    "modelKey",
    "modelVersion",
    "predictionType",
    "entityType",
    "explanation",
    "generatedAt",
  ];

  requiredTextFields.forEach((field) => {
    if (typeof candidateOutput[field] !== "string" || String(candidateOutput[field]).trim().length === 0) {
      issues.push({ field, message: `${field} is required and must be a non-empty string.` });
    }
  });

  if (candidateOutput.fixtureOnly !== true) {
    issues.push({ field: "fixtureOnly", message: "fixtureOnly must be true so this cannot be mistaken for live model output." });
  }

  assertNumberOrNull(candidateOutput.horizonDays, "horizonDays", issues, { min: 1, max: 365 });
  assertNumberOrNull(candidateOutput.candidateScore, "candidateScore", issues, { min: 0, max: 1 });
  assertNumberOrNull(candidateOutput.candidateConfidence, "candidateConfidence", issues, { min: 0, max: 1 });
  assertNumberOrNull(candidateOutput.baselineScore, "baselineScore", issues, { min: 0, max: 1 });
  assertNumberOrNull(candidateOutput.deltaFromBaseline, "deltaFromBaseline", issues, { min: -1, max: 1 });

  if (candidateOutput.rawCandidateOutput != null && !isPlainObject(candidateOutput.rawCandidateOutput)) {
    issues.push({ field: "rawCandidateOutput", message: "rawCandidateOutput must be a plain object or null." });
  }

  if (!Array.isArray(candidateOutput.safetyNotes) || candidateOutput.safetyNotes.some((note) => typeof note !== "string")) {
    issues.push({ field: "safetyNotes", message: "safetyNotes must be an array of strings." });
  }

  [
    "modelExecutionAttempted",
    "modelExecutionAllowed",
    "inferenceEndpointExposed",
    "productionIntegrationAllowed",
    "decisionAutomationAllowed",
    "businessMutationAllowed",
    "approvalAllowed",
    "activationAllowed",
    "promotionAllowed",
    "pricingMutationAllowed",
    "reportMutationAllowed",
    "ledgerMutationAllowed",
  ].forEach((field) => assertFalse(candidateOutput[field], field, issues));

  FORBIDDEN_OUTPUT_FIELDS.forEach((field) => {
    if (Object.prototype.hasOwnProperty.call(candidateOutput, field)) {
      issues.push({ field, message: `${field} is forbidden in the offline candidate output fixture contract.` });
    }
  });

  return {
    valid: issues.length === 0,
    status: issues.length === 0 ? "valid" as const : "invalid" as const,
    issueCount: issues.length,
    issues,
    normalized: issues.length === 0 ? candidateOutput : null,
  };
};

export const buildShadowRuntimeCandidateOutputFixturePackContract = () => ({
  fixturePackKey: FIXTURE_PACK_KEY,
  fixturePackVersion: "v1",
  phase: PHASE_LABEL,
  generatedAt: new Date().toISOString(),
  purpose: "Offline candidate output contract fixtures for validating the future external model result shape without loading artifacts or running inference.",
  requiredFields: [
    "fixtureKey",
    "fixtureVersion",
    "fixtureOnly",
    "modelKey",
    "modelVersion",
    "predictionType",
    "entityType",
    "entityId",
    "horizonDays",
    "candidateScore",
    "candidateLabel",
    "candidateConfidence",
    "baselineScore",
    "deltaFromBaseline",
    "rawCandidateOutput",
    "explanation",
    "safetyNotes",
    "generatedAt",
  ],
  forbiddenFields: [...FORBIDDEN_OUTPUT_FIELDS],
  allowedBehavior: [
    "Return offline fixture-only candidate output examples.",
    "Validate candidate output shape in memory.",
    "Compare output contract fields against baseline-compatible metadata.",
    "Expose fixture-pack summary for Admin and Manager users.",
  ],
  forbiddenBehavior: [
    "Do not load model artifacts.",
    "Do not execute a real model.",
    "Do not call external runtimes or APIs.",
    "Do not expose an inference endpoint.",
    "Do not approve, activate, promote, or deploy a model candidate.",
    "Do not mutate pricing, reports, ledger, inventory, accounting, sales, repairs, partners, or customers.",
  ],
  safetyGate: getShadowRuntimeSafetyGate(),
});

export const getShadowRuntimeCandidateOutputFixturePackSummary = () => {
  const fixtures = buildShadowRuntimeCandidateOutputContractFixtures();
  const validations = fixtures.map(validateShadowRuntimeCandidateOutputFixture);
  const validFixtureCount = validations.filter((result) => result.valid).length;
  const safetyGate = getShadowRuntimeSafetyGate();
  return {
    generatedAt: new Date().toISOString(),
    currentStatus: PHASE_LABEL,
    fixturePackLabel: "Offline Candidate Output Contract Fixture Pack",
    fixturePackStatus: "Offline / Fixture-only / Read-only",
    modelArtifactLoading: "Blocked",
    modelExecution: "Off",
    productionInference: "Not exposed",
    businessMutation: "Blocked",
    latestSafetyStatus: safetyGate,
    currentShadowRuntimeCandidateOutputFixturePack: {
      status: "offline_fixture_only",
      readinessScorePct: 100,
      fixtureCount: fixtures.length,
      validFixtureCount,
      invalidFixtureCount: fixtures.length - validFixtureCount,
      validationIssueCount: validations.reduce((sum, result) => sum + result.issueCount, 0),
      modelArtifactLoadAllowed: false,
      externalModelCallAllowed: false,
      runtimeInvocationAllowed: safetyGate.runtimeInvocationAllowed,
      modelExecutionAllowed: safetyGate.modelExecutionAllowed,
      inferenceEndpointExposed: safetyGate.inferenceEndpointExposed,
      productionIntegrationAllowed: safetyGate.productionIntegrationAllowed,
      decisionAutomationAllowed: safetyGate.decisionAutomationAllowed,
      canChangeInventoryOrAccounting: safetyGate.canChangeInventoryOrAccounting,
      canChangePricing: safetyGate.canChangePricing,
      canChangeReports: safetyGate.canChangeReports,
      canChangeLedger: safetyGate.canChangeLedger,
      canMutateBusinessRecords: safetyGate.canMutateBusinessRecords,
      explanation: "Offline fixture pack validates the candidate model output contract shape only; it does not run a model or persist a decision.",
      warnings: [
        "Fixtures are synthetic and offline-only.",
        "No real model execution is enabled.",
        "No model artifact is loaded.",
        "No inference endpoint is exposed.",
        "No approval, activation, promotion, pricing, reporting, ledger, inventory, accounting, or business mutation is possible.",
      ],
      blockers: [],
      recommendedNextAction: "Use these fixtures to validate future candidate output envelopes before any artifact loading design is considered.",
    },
    contract: buildShadowRuntimeCandidateOutputFixturePackContract(),
    fixtureValidationResults: validations,
    fixtures,
  };
};
