import type { Express } from "express";
import type { IntelligenceRouteDeps } from "./types";
import { registerPredictiveRoutes } from "./predictive.routes";
import { registerPredictionLogsRoutes } from "./predictionLogs.routes";
import { registerPredictionAccuracyRoutes } from "./predictionAccuracy.routes";
import { registerModelReadinessRoutes } from "./modelReadiness.routes";
import { registerDataQualityRoutes } from "./dataQuality.routes";
import { registerMlDatasetRoutes } from "./mlDataset.routes";
import { registerMlBenchmarkRoutes } from "./mlBenchmark.routes";
import { registerMlTrainingPackageRoutes } from "./mlTrainingPackage.routes";
import { registerMlCandidateModelPackageRoutes } from "./mlCandidateModelPackage.routes";
import { registerMlCandidateEvaluationMetadataImportRoutes } from "./mlCandidateEvaluationMetadataImport.routes";
import { registerMlCandidateEvaluationComparisonDashboardRoutes } from "./mlCandidateEvaluationComparisonDashboard.routes";
import { registerMlWorkbenchImportResultDashboardRoutes } from "./mlWorkbenchImportResultDashboard.routes";
import { registerMlCandidateMetricDrilldownRoutes } from "./mlCandidateMetricDrilldown.routes";
import { registerMlCandidateDatasetSliceDiagnosticsRoutes } from "./mlCandidateDatasetSliceDiagnostics.routes";
import { registerMlCandidateModelCardQualityScoringRoutes } from "./mlCandidateModelCardQualityScoring.routes";
import { registerMlCandidateTrainingPackageQualitySnapshotRoutes } from "./mlCandidateTrainingPackageQualitySnapshot.routes";
import { registerMlCandidateDataDriftBaselineMetadataRoutes } from "./mlCandidateDataDriftBaselineMetadata.routes";
import { registerMlCandidateFeatureContractDriftMetadataRoutes } from "./mlCandidateFeatureContractDriftMetadata.routes";
import { registerMlCandidateThresholdScenarioMetadataRoutes } from "./mlCandidateThresholdScenarioMetadata.routes";
import { registerMlCandidateCalibrationMetadataRoutes } from "./mlCandidateCalibrationMetadata.routes";
import { registerMlCandidateErrorAnalysisMetadataRoutes } from "./mlCandidateErrorAnalysisMetadata.routes";
import { registerMlCandidateRobustnessMetadataRoutes } from "./mlCandidateRobustnessMetadata.routes";
import { registerMlCandidateDeploymentReadinessMetadataRoutes } from "./mlCandidateDeploymentReadinessMetadata.routes";
import { registerMlCandidatePackageIntakeBinderRoutes } from "./mlCandidatePackageIntakeBinder.routes";
import { registerMlCandidatePackageHumanReviewSignoffRoutes } from "./mlCandidatePackageHumanReviewSignoff.routes";
import { registerMlCandidatePackageHumanSignoffArchivePackRoutes } from "./mlCandidatePackageHumanSignoffArchivePack.routes";
import { registerMlCandidatePackageArchiveRetentionReviewBinderRoutes } from "./mlCandidatePackageArchiveRetentionReviewBinder.routes";
import { registerMlCandidatePackageArchiveRetentionReviewSignoffRoutes } from "./mlCandidatePackageArchiveRetentionReviewSignoff.routes";
import { registerMlCandidatePackageRetentionSignoffArchivePackRoutes } from "./mlCandidatePackageRetentionSignoffArchivePack.routes";
import { registerMlCandidatePackageRetentionArchiveFinalAuditSnapshotRoutes } from "./mlCandidatePackageRetentionArchiveFinalAuditSnapshot.routes";
import { registerMlCandidatePackageFinalAuditSnapshotGovernanceSignoffRoutes } from "./mlCandidatePackageFinalAuditSnapshotGovernanceSignoff.routes";
import { registerMlCandidatePackageGovernanceSignoffArchivePackRoutes } from "./mlCandidatePackageGovernanceSignoffArchivePack.routes";
import { registerMlCandidatePackageGovernanceSignoffArchiveFinalizationSummaryPackRoutes } from "./mlCandidatePackageGovernanceSignoffArchiveFinalizationSummaryPack.routes";
import { registerMlApprovalRoutes } from "./mlApproval.routes";
import { registerMlShadowEvaluationRoutes } from "./mlShadowEvaluation.routes";
import { registerMlShadowStabilityRoutes } from "./mlShadowStability.routes";
import { registerMlOfflinePilotRoutes } from "./mlOfflinePilot.routes";
import { registerMlProductionReadinessRoutes } from "./mlProductionReadiness.routes";
import { registerMlModelImportRoutes } from "./mlModelImport.routes";
import { registerMlSafeInferenceRoutes } from "./mlSafeInference.routes";
import { registerMlShadowAdapterRoutes } from "./mlShadowAdapter.routes";
import { registerMlShadowObservationEventStoreRoutes } from "./mlShadowObservationEventStore.routes";
import { registerMlShadowObservationReviewDashboardRoutes } from "./mlShadowObservationReviewDashboard.routes";
import { registerMlShadowObservationReviewDecisionLogRoutes } from "./mlShadowObservationReviewDecisionLog.routes";
import { registerMlShadowObservationDecisionReviewExportBinderRoutes } from "./mlShadowObservationDecisionReviewExportBinder.routes";
import { registerMlShadowObservationBinderReviewSignoffGateRoutes } from "./mlShadowObservationBinderReviewSignoffGate.routes";
import { registerMlShadowObservationSignoffArchivePackRoutes } from "./mlShadowObservationSignoffArchivePack.routes";
import { registerMlShadowObservationArchivePackRetentionPolicyRoutes } from "./mlShadowObservationArchivePackRetentionPolicy.routes";
import { registerMlReadOnlyShadowScoringRuntimeRoutes } from "./mlReadOnlyShadowScoringRuntime.routes";
import { registerMlShadowScoreReviewQueueRoutes } from "./mlShadowScoreReviewQueue.routes";
import { registerMlShadowScoreReviewSignoffWorkflowRoutes } from "./mlShadowScoreReviewSignoffWorkflow.routes";
import { registerMlShadowScoreSignoffEvidencePackRoutes } from "./mlShadowScoreSignoffEvidencePack.routes";
import { registerMlShadowScoreEvidenceRetentionReviewRoutes } from "./mlShadowScoreEvidenceRetentionReview.routes";
import { registerMlShadowScoreRetentionReviewSignoffRoutes } from "./mlShadowScoreRetentionReviewSignoff.routes";
import { registerMlShadowScoreSignoffArchiveBinderRoutes } from "./mlShadowScoreSignoffArchiveBinder.routes";
import { registerMlShadowRuntimeRoutes } from "./mlShadowRuntime.routes";
import { registerMlShadowScoreComparisonSummaryRoutes } from "./mlShadowScoreComparisonSummary.routes";
import { registerMlShadowScoreImportApplyRoutes } from "./mlShadowScoreImportApply.routes";
import { registerMlShadowScoreImportApplyReceiptReadModelRoutes } from './mlShadowScoreImportApplyReceiptReadModel.routes';
import { registerMlShadowScoreImportApplyReceiptExportReadModelRoutes } from './mlShadowScoreImportApplyReceiptExportReadModel.routes';
import { registerMlShadowScoreImportApplyReceiptExportPackageRoutes } from './mlShadowScoreImportApplyReceiptExportPackage.routes';
import { registerMlShadowScoreImportApplyReceiptExportPackageSnapshotReadModelRoutes } from './mlShadowScoreImportApplyReceiptExportPackageSnapshotReadModel.routes';
import { registerMlOfflineArtifactIntakeRoutes } from "./mlOfflineArtifactIntake.routes";
import { registerMlOfflineArtifactValidationRoutes } from "./mlOfflineArtifactValidation.routes";
import { registerMlOfflineArtifactValidationReviewQueueRoutes } from "./mlOfflineArtifactValidationReviewQueue.routes";
import { registerMlOfflineArtifactValidationReviewerAssignmentUxRoutes } from "./mlOfflineArtifactValidationReviewerAssignmentUx.routes";
import { registerMlOfflineArtifactValidationEvidenceReviewPackRoutes } from "./mlOfflineArtifactValidationEvidenceReviewPack.routes";
import { registerMlOfflineArtifactValidationEvidenceGapClosureMatrixRoutes } from "./mlOfflineArtifactValidationEvidenceGapClosureMatrix.routes";
import { registerMlOfflineArtifactValidationEvidenceClosureSignoffPackRoutes } from "./mlOfflineArtifactValidationEvidenceClosureSignoffPack.routes";
import { registerMlOfflineArtifactValidationFutureShadowEligibilityGateRoutes } from "./mlOfflineArtifactValidationFutureShadowEligibilityGate.routes";
import { registerMlOfflineArtifactValidationFutureShadowEligibilityReviewBinderRoutes } from "./mlOfflineArtifactValidationFutureShadowEligibilityReviewBinder.routes";
import { registerMlOfflineArtifactValidationFutureShadowReviewBinderRoutingSummaryPackRoutes } from "./mlOfflineArtifactValidationFutureShadowReviewBinderRoutingSummaryPack.routes";
import { registerMlOfflineArtifactValidationFutureShadowBoardReviewPacketRoutes } from "./mlOfflineArtifactValidationFutureShadowBoardReviewPacket.routes";
import { registerMlOfflineArtifactValidationFutureShadowBoardReviewDecisionLogRoutes } from "./mlOfflineArtifactValidationFutureShadowBoardReviewDecisionLog.routes";
import { registerFinancialBrainRoutes } from "./financial.routes";

export const registerIntelligenceRouteModules = (
  app: Express,
  deps: IntelligenceRouteDeps,
): void => {
  registerPredictiveRoutes(app, deps);
  registerPredictionLogsRoutes(app, deps);
  registerPredictionAccuracyRoutes(app, deps);
  registerModelReadinessRoutes(app, deps);
  registerDataQualityRoutes(app, deps);
  registerMlDatasetRoutes(app, deps);
  registerMlBenchmarkRoutes(app, deps);
  registerMlTrainingPackageRoutes(app, deps);
  registerMlCandidateModelPackageRoutes(app, deps);
  registerMlCandidateEvaluationMetadataImportRoutes(app, deps);
  registerMlCandidateEvaluationComparisonDashboardRoutes(app, deps);
  registerMlWorkbenchImportResultDashboardRoutes(app, deps);
  registerMlCandidateMetricDrilldownRoutes(app, deps);
  registerMlCandidateDatasetSliceDiagnosticsRoutes(app, deps);
  registerMlCandidateModelCardQualityScoringRoutes(app, deps);
  registerMlCandidateTrainingPackageQualitySnapshotRoutes(app, deps);
  registerMlCandidateDataDriftBaselineMetadataRoutes(app, deps);
  registerMlCandidateFeatureContractDriftMetadataRoutes(app, deps);
  registerMlCandidateThresholdScenarioMetadataRoutes(app, deps);
  registerMlCandidateCalibrationMetadataRoutes(app, deps);
  registerMlCandidateErrorAnalysisMetadataRoutes(app, deps);
  registerMlCandidateRobustnessMetadataRoutes(app, deps);
  registerMlCandidateDeploymentReadinessMetadataRoutes(app, deps);
  registerMlCandidatePackageIntakeBinderRoutes(app, deps);
  registerMlCandidatePackageHumanReviewSignoffRoutes(app, deps);
  registerMlCandidatePackageHumanSignoffArchivePackRoutes(app, deps);
  registerMlCandidatePackageArchiveRetentionReviewBinderRoutes(app, deps);
  registerMlCandidatePackageArchiveRetentionReviewSignoffRoutes(app, deps);
  registerMlCandidatePackageRetentionSignoffArchivePackRoutes(app, deps);
  registerMlCandidatePackageRetentionArchiveFinalAuditSnapshotRoutes(app, deps);
  registerMlCandidatePackageFinalAuditSnapshotGovernanceSignoffRoutes(app, deps);
  registerMlCandidatePackageGovernanceSignoffArchivePackRoutes(app, deps);
  registerMlCandidatePackageGovernanceSignoffArchiveFinalizationSummaryPackRoutes(app, deps);
  registerMlApprovalRoutes(app, deps);
  registerMlShadowEvaluationRoutes(app, deps);
  registerMlShadowStabilityRoutes(app, deps);
  registerMlOfflinePilotRoutes(app, deps);
  registerMlProductionReadinessRoutes(app, deps);
  registerMlModelImportRoutes(app, deps);
  registerMlSafeInferenceRoutes(app, deps);
  registerMlShadowAdapterRoutes(app, deps);
  registerMlShadowObservationEventStoreRoutes(app, deps);
  registerMlShadowObservationReviewDashboardRoutes(app, deps);
  registerMlShadowObservationReviewDecisionLogRoutes(app, deps);
  registerMlShadowObservationDecisionReviewExportBinderRoutes(app, deps);
  registerMlShadowObservationBinderReviewSignoffGateRoutes(app, deps);
  registerMlShadowObservationSignoffArchivePackRoutes(app, deps);
  registerMlShadowObservationArchivePackRetentionPolicyRoutes(app, deps);
  registerMlReadOnlyShadowScoringRuntimeRoutes(app, deps);
  registerMlShadowScoreReviewQueueRoutes(app, deps);
  registerMlShadowScoreReviewSignoffWorkflowRoutes(app, deps);
  registerMlShadowScoreSignoffEvidencePackRoutes(app, deps);
  registerMlShadowScoreEvidenceRetentionReviewRoutes(app, deps);
  registerMlShadowScoreRetentionReviewSignoffRoutes(app, deps);
  registerMlShadowScoreSignoffArchiveBinderRoutes(app, deps);
  registerMlShadowRuntimeRoutes(app, deps);
  registerMlShadowScoreComparisonSummaryRoutes(app, deps);
  registerMlShadowScoreImportApplyRoutes(app, deps);
  registerMlShadowScoreImportApplyReceiptReadModelRoutes(app, deps);
  registerMlShadowScoreImportApplyReceiptExportReadModelRoutes(app, deps);
  registerMlShadowScoreImportApplyReceiptExportPackageRoutes(app, deps);
  registerMlShadowScoreImportApplyReceiptExportPackageSnapshotReadModelRoutes(app, deps);
  registerMlOfflineArtifactIntakeRoutes(app, deps);
  registerMlOfflineArtifactValidationRoutes(app, deps);
  registerMlOfflineArtifactValidationReviewerAssignmentUxRoutes(app, deps);
  registerMlOfflineArtifactValidationEvidenceReviewPackRoutes(app, deps);
  registerMlOfflineArtifactValidationEvidenceGapClosureMatrixRoutes(app, deps);
  registerMlOfflineArtifactValidationEvidenceClosureSignoffPackRoutes(app, deps);
  registerMlOfflineArtifactValidationFutureShadowEligibilityGateRoutes(app, deps);
  registerMlOfflineArtifactValidationFutureShadowEligibilityReviewBinderRoutes(app, deps);
  registerMlOfflineArtifactValidationFutureShadowReviewBinderRoutingSummaryPackRoutes(app, deps);
  registerMlOfflineArtifactValidationFutureShadowBoardReviewPacketRoutes(app, deps);
  registerMlOfflineArtifactValidationFutureShadowBoardReviewDecisionLogRoutes(app, deps);
  registerMlOfflineArtifactValidationReviewQueueRoutes(app, deps);
  registerFinancialBrainRoutes(app, deps);
};
