import React from 'react';
import type { SettingsRenderContext } from './SettingsController';

type Props = {
  ctx: SettingsRenderContext;
};

const SettingsWorkspaceSection: React.FC<Props> = ({ ctx }) => {
  const {
    SettingsAccountPanel,
    SettingsBusinessPanel,
    SettingsDataPanel,
    SettingsLocalPanel,
    SettingsModulesPanel,
    SettingsPricingPanel,
    SettingsRemindersPanel,
    SettingsSaveFooter,
    SettingsSmartPanel,
    SettingsSmsPanel,
    SettingsStylePanel,
    SettingsTelegramPanel,
    SettingsUsersPanel,
    accountDisplayName,
    accountInitial,
    accountMetaItems,
    accountPasswordMismatch,
    accountPasswordReady,
    accountPasswordScore,
    accountPasswordVisual,
    accountProfile,
    accountSecurityItems,
    accountProfileDirty,
    profileFirstName,
    profileLastName,
    applyAdvisorStrategy,
    applyCommercialPlan,
    applyTelegramAiSuggestion,
    applyTelegramPreset,
    backupEnabled,
    backupFeedbackIcon,
    backupFeedbackLabel,
    backupFeedbackTone,
    backupList,
    restoreHistory,
    backupModeLabel,
    backupNextRunLabel,
    backupRetention,
    backupScheduleIntervalHours,
    backupScheduleMode,
    backupScheduleTime,
    backupScheduleWeekdays,
    backupSettingsDirty,
    backupStatusClass,
    backupStatusLabel,
    backupSummaryTone,
    backupTimezone,
    buildTelegramAudiencePreset,
    bumpTelegramQuickActionUsage,
    businessAddressSummary,
    businessInfo,
    businessSummaryItems,
    canManageStoreOwnership,
    checkTelegramHealth,
    clearTelegramStudioFilters,
    commercialPlanUiCopy,
    dbFileInputRef,
    deferTelegramTodo,
    exportPricingDecisionLogExcel,
    exportPricingDecisionLogPdf,
    fetchBackups,
    refreshUsersData,
    fetchTelegramRecentChats,
    fieldsetClass,
    fieldsetLegendClass,
    filteredTelegramGroupedDefs,
    filteredUsers,
    focusTelegramAudience,
    formatPricingDatePreview,
    getFeatureRuntimeBadges,
    getRoleLabelFa,
    getTelegramAiAssistantCopy,
    getTelegramAudienceFormatKey,
    getTelegramAudienceKey,
    getTelegramCategoryStatus,
    getTelegramItemStatus,
    getTelegramMiniStatusClasses,
    getTelegramPriorityMeta,
    getTelegramProgressTone,
    getTelegramTodoNextStep,
    handleBackup,
    handleBackupTimeInputBlur,
    handleBackupTimeInputChange,
    handleBusinessInfoChange,
    handleBusinessInfoSubmit,
    handleTelegramSettingsSubmit,
    handleGenerateLocalCertificate,
    handleChangeMyPassword,
    handleSaveMyProfile,
    handleCheckRestore,
    handleCreateBackupNow,
    handleDbFileChange,
    handleDeleteBackupFile,
    handleDownloadBackupFile,
    handleDownloadHostsScript,
    handleDownloadLocalCertificate,
    handleLogoFileChange,
    handleLogoReset,
    handleLogoUpload,
    handleMeAvatarChange,
    handleMeAvatarUpload,
    handleRestoreFromBackup,
    handleSaveBackupSchedule,
    infoChanged,
    inputClass,
    isAdmin,
    isChangingPassword,
    isFeatureSettingEnabled,
    isGeneratingLocalCert,
    isLoadingBackups,
    isRefreshingUsers,
    currentUserId,
    isRestoringDb,
    backupOperationKey,
    restoreProgress,
    isSaving,
    isSavingBackupSchedule,
    isSavingProfile,
    isUploadingAvatar,
    isUploadingLogo,
    jumpToFirstIncompleteTelegramTemplate,
    jumpToTelegramConfigField,
    jumpToTelegramSection,
    jumpToTelegramSetupField,
    jumpToTelegramTemplate,
    labelClass,
    localCertError,
    localCertMessage,
    localDomainValue,
    localHostnameValue,
    localHostsLineValue,
    localSuffixValue,
    meliPatternDefs,
    logoFile,
    logoInputRef,
    logoInputRefClick,
    logoPreview,
    markTelegramTodoDone,
    meAvatarFile,
    meAvatarInputRef,
    meAvatarPreview,
    moduleRuntimeSummary,
    newPassword,
    newPassword2,
    normalizePricingDateInput,
    oldPassword,
    openAddUserModal,
    openDeleteUserModal,
    openEditUserModal,
    openResetPasswordModal,
    openSmsPatternCheck,
    openSmsPatternPreview,
    openTelegramAudiencePanels,
    openTelegramCategories,
    openTelegramItems,
    openTelegramTemplateCheck,
    openUrgentTelegramTodos,
    partnerSetupNeedsAttention,
    partnerShareChipClass,
    partnerShareChipIcon,
    partnerShareStatus,
    pricingDecisionActionFilter,
    pricingDecisionDateFrom,
    pricingDecisionDateTo,
    pricingDecisionDeltaFilter,
    pricingDecisionLog,
    pricingDecisionSearch,
    pricingDataStatus,
    refreshPricingLearningData,
    pricingLearningStats,
    pricingSettings,
    pricingStrategyAdvisor,
    pricingStrategyLabels,
    reactivateTelegramTodo,
    renderTelegramFieldLabel,
    renderTelegramPlainFieldLabel,
    resetPricingLearning,
    resetPricingSettings,
    resetTelegramQuickActionPersonalization,
    resetTelegramTodoAssistant,
    roles,
    runTelegramAdminAction,
    runTelegramDiagnostics,
    scrollToSection,
    sendTelegramQuickCheck,
    setAllTelegramCategories,
    setAllTelegramItems,
    setBackupEnabled,
    setBackupRetention,
    setBackupScheduleIntervalHours,
    setBackupScheduleMode,
    setBackupScheduleWeekdays,
    setBackupTimezone,
    setBusinessInfo,
    setFeatureByKey,
    setNewPassword,
    setNewPassword2,
    setNotification,
    setOldPassword,
    setProfileFirstName,
    setProfileLastName,
    setOpenTelegramItems,
    setPricingDecisionActionFilter,
    setPricingDecisionDateFrom,
    setPricingDecisionDateTo,
    setPricingDecisionDeltaFilter,
    setPricingDecisionSearch,
    setShowAccountPasswordFields,
    setShowTelegramToken,
    openSmsBulkCheck,
    openSmsBulkPanel,
    setTab,
    setTelegramStudioMode,
    setTelegramTemplateFilter,
    setTelegramTemplateSearch,
    setTgQuickMsg,
    setUserRoleFilter,
    setUserSearchQuery,
    settingsSectionCard,
    settingsViewMode,
    showAccountPasswordFields,
    showTelegramToken,
    smsAutomationCount,
    smsConfiguredCount,
    smsCoreReady,
    smsCredentialConfiguredCount,
    smsCredentialReady,
    smsCredentialTotalCount,
    smsInfo,
    smsMissingRequirements,
    smsProviderKey,
    smsProviderMeta,
    smsReadinessPercent,
    smsTotalCount,
    tab,
    telegramAudienceDestinationCount,
    telegramChatIdValue,
    telegramCoachMessage,
    telegramConfigChecks,
    telegramConfigReadiness,
    telegramConfigReadyCount,
    telegramConnectionMode,
    telegramDestinationCount,
    telegramDiagnosticsViewModel,
    telegramEffectiveFilter,
    telegramFieldInsights,
    telegramHasProxy,
    telegramInfo,
    telegramMissingItems,
    telegramPinnedQuickActions,
    telegramProxyValue,
    telegramQuickActionUsageMap,
    telegramReadinessLabel,
    telegramReadinessScore,
    telegramRecentChatsViewModel,
    telegramSetupCoachMessage,
    telegramSetupDone,
    telegramSetupItems,
    telegramSetupPercent,
    telegramSmartActions,
    telegramSpotlightTarget,
    telegramStudioMode,
    telegramTemplateDefs,
    telegramTemplateFilter,
    telegramTemplateSearch,
    telegramTodoDoneMap,
    telegramTodoSummary,
    telegramTodoTopItems,
    telegramTokenValue,
    telegramUsernameValue,
    telegramسراسریCompletionPercent,
    telegramسراسریSummary,
    tgAudienceMeta,
    tgCategoryMeta,
    tgChatLookupHint,
    tgChatLookupLoading,
    tgDiagnostics,
    tgDiagnosticsBusyAction,
    tgDiagnosticsLoading,
    tgHealth,
    tgIsChecking,
    tgIsSendingQuick,
    tgQuickMsg,
    tgRecentChats,
    toggleTelegramAudiencePanel,
    toggleTelegramCategory,
    toggleTelegramItem,
    toggleTelegramQuickActionPin,
    updatePricingSettings,
    userRoleFilter,
    userRoleSummaries,
    userSearchQuery,
    userStatsCards,
    users,
    visibleTelegramItemsCount,
  } = ctx;

  return (
    <>
      <div className="settings-workspace-layout">
        <section className="settings-workspace" data-ui-settings-workspace="true" data-settings-responsive="container" data-settings-active-tab={tab}>
          <div className="settings-content-boundary" data-ui-settings-content-boundary="true">
            <div className="settings-panel-frame" data-ui-settings-panel-frame="true">

          {!isAdmin && tab !== 'account' && (
            <div className="mb-6 rounded-2xl border border-amber-200 bg-amber-50/60 dark:border-amber-800 dark:bg-amber-900/20 p-4">
              <div className="settings-tab-row flex w-full items-start justify-start gap-3 text-right">
                <div className="h-10 w-10 rounded-xl bg-amber-500/15 text-amber-700 dark:text-amber-200 flex items-center justify-center">
                  <i className="fa-solid fa-lock" />
                </div>
                <div className="min-w-0 flex-1 text-right">
                  <div className="font-semibold text-amber-900 dark:text-amber-100">دسترسی محدود</div>
                  <div className="text-xs text-amber-800/80 dark:text-amber-200/80 mt-1">
                    برای امنیت سیستم، این بخش‌ها فقط برای مدیر (Admin) فعال است. شما می‌توانید از تب «حساب کاربری» پروفایل و امنیت حساب خود را مدیریت کنید.
                  </div>
                </div>
                <button
                  type="button"
                  onClick={() => setTab('account')}
                  className="px-3 py-2 text-sm rounded-xl bg-amber-600 text-white hover:brightness-110 transition"
                >
                  رفتن به حساب
                </button>
              </div>
              </div>
          )}


          {tab === 'account' && (
            <SettingsAccountPanel
              meAvatarInputRef={meAvatarInputRef}
              handleMeAvatarChange={handleMeAvatarChange}
              meAvatarPreview={meAvatarPreview}
              accountProfile={accountProfile}
              accountDisplayName={accountDisplayName}
              accountInitial={accountInitial}
              isAdmin={isAdmin}
              getRoleLabelFa={getRoleLabelFa}
              setTab={setTab}
              meAvatarFile={meAvatarFile}
              isUploadingAvatar={isUploadingAvatar}
              handleMeAvatarUpload={handleMeAvatarUpload}
              accountMetaItems={accountMetaItems}
              settingsSectionCard={settingsSectionCard}
              labelClass={labelClass}
              inputClass={inputClass}
              showAccountPasswordFields={showAccountPasswordFields}
              setShowAccountPasswordFields={setShowAccountPasswordFields}
              oldPassword={oldPassword}
              setOldPassword={setOldPassword}
              newPassword={newPassword}
              setNewPassword={setNewPassword}
              newPassword2={newPassword2}
              setNewPassword2={setNewPassword2}
              accountPasswordVisual={accountPasswordVisual}
              accountPasswordScore={accountPasswordScore}
              accountPasswordMismatch={accountPasswordMismatch}
              handleChangeMyPassword={handleChangeMyPassword}
              accountPasswordReady={accountPasswordReady}
              isChangingPassword={isChangingPassword}
              accountSecurityItems={accountSecurityItems}
              profileFirstName={profileFirstName}
              setProfileFirstName={setProfileFirstName}
              profileLastName={profileLastName}
              setProfileLastName={setProfileLastName}
              accountProfileDirty={accountProfileDirty}
              isSavingProfile={isSavingProfile}
              handleSaveMyProfile={handleSaveMyProfile}
            />
          )}


          {tab === 'business' && (
            <SettingsBusinessPanel
              businessInfo={businessInfo}
              businessSummaryItems={businessSummaryItems}
              businessAddressSummary={businessAddressSummary}
              labelClass={labelClass}
              inputClass={inputClass}
              settingsSectionCard={settingsSectionCard}
              logoInputRef={logoInputRef}
              logoPreview={logoPreview}
              logoFile={logoFile}
              isUploadingLogo={isUploadingLogo}
              infoChanged={infoChanged}
              isSaving={isSaving}
              canManageStoreOwnership={canManageStoreOwnership}
              partnerSetupNeedsAttention={partnerSetupNeedsAttention}
              partnerShareChipClass={partnerShareChipClass}
              partnerShareChipIcon={partnerShareChipIcon}
              partnerShareStatus={partnerShareStatus}
              handleBusinessInfoSubmit={handleBusinessInfoSubmit}
              handleBusinessInfoChange={handleBusinessInfoChange}
              handleLogoFileChange={handleLogoFileChange}
              handleLogoUpload={handleLogoUpload}
              handleLogoReset={handleLogoReset}
              logoInputRefClick={logoInputRefClick}
            />
          )}

          {tab === 'modules' && (
            <SettingsModulesPanel
              infoChanged={infoChanged}
              isSaving={isSaving}
              handleBusinessInfoSubmit={handleBusinessInfoSubmit}
              moduleRuntimeSummary={moduleRuntimeSummary}
              commercialPlanUiCopy={commercialPlanUiCopy}
              isFeatureSettingEnabled={isFeatureSettingEnabled}
              applyCommercialPlan={applyCommercialPlan}
              getFeatureRuntimeBadges={getFeatureRuntimeBadges}
              setFeatureByKey={setFeatureByKey}
            />
          )}

          <SettingsLocalPanel
            tab={tab}
            businessInfo={businessInfo}
            labelClass={labelClass}
            inputClass={inputClass}
            localHostnameValue={localHostnameValue}
            localSuffixValue={localSuffixValue}
            localDomainValue={localDomainValue}
            localHostsLineValue={localHostsLineValue}
            localCertMessage={localCertMessage}
            localCertError={localCertError}
            isGeneratingLocalCert={isGeneratingLocalCert}
            infoChanged={infoChanged}
            isSaving={isSaving}
            isAdmin={isAdmin}
            handleGenerateLocalCertificate={handleGenerateLocalCertificate}
            handleDownloadHostsScript={handleDownloadHostsScript}
            handleDownloadLocalCertificate={handleDownloadLocalCertificate}
            handleBusinessInfoChange={handleBusinessInfoChange}
            handleBusinessInfoSubmit={handleBusinessInfoSubmit}
          />

          <SettingsSmsPanel
            tab={tab}
            businessInfo={smsInfo}
            inputClass={inputClass}
            labelClass={labelClass}
            fieldsetClass={fieldsetClass}
            fieldsetLegendClass={fieldsetLegendClass}
            smsCoreReady={smsCoreReady}
            smsProviderMeta={smsProviderMeta}
            smsProviderKey={smsProviderKey}
            smsCredentialReady={smsCredentialReady}
            smsCredentialConfiguredCount={smsCredentialConfiguredCount}
            smsCredentialTotalCount={smsCredentialTotalCount}
            smsConfiguredCount={smsConfiguredCount}
            smsTotalCount={smsTotalCount}
            smsAutomationCount={smsAutomationCount}
            smsReadinessPercent={smsReadinessPercent}
            smsMissingRequirements={smsMissingRequirements}
            infoChanged={infoChanged}
            isSaving={isSaving}
            meliPatternDefs={meliPatternDefs}
            handleBusinessInfoChange={handleBusinessInfoChange}
            handleBusinessInfoSubmit={handleBusinessInfoSubmit}
            scrollToSection={scrollToSection}
            openSmsPatternPreview={openSmsPatternPreview}
            openSmsPatternCheck={openSmsPatternCheck}
            openSmsBulkCheck={openSmsBulkCheck}
            openSmsBulkPanel={openSmsBulkPanel}
          />

          {/* تب تنظیمات تلگرام */}
          <SettingsTelegramPanel
            tab={tab}
            settingsViewMode={settingsViewMode}
            businessInfo={telegramInfo}
            handleBusinessInfoSubmit={handleBusinessInfoSubmit}
            handleTelegramSettingsSubmit={handleTelegramSettingsSubmit}
            handleBusinessInfoChange={handleBusinessInfoChange}
            setBusinessInfo={setBusinessInfo}
            setNotification={setNotification}
            applyTelegramAiSuggestion={applyTelegramAiSuggestion}
            applyTelegramPreset={applyTelegramPreset}
            buildTelegramAudiencePreset={buildTelegramAudiencePreset}
            bumpTelegramQuickActionUsage={bumpTelegramQuickActionUsage}
            checkTelegramHealth={checkTelegramHealth}
            clearTelegramStudioFilters={clearTelegramStudioFilters}
            deferTelegramTodo={deferTelegramTodo}
            fetchTelegramRecentChats={fetchTelegramRecentChats}
            filteredTelegramGroupedDefs={filteredTelegramGroupedDefs}
            focusTelegramAudience={focusTelegramAudience}
            getTelegramAiAssistantCopy={getTelegramAiAssistantCopy}
            getTelegramAudienceFormatKey={getTelegramAudienceFormatKey}
            getTelegramAudienceKey={getTelegramAudienceKey}
            getTelegramCategoryStatus={getTelegramCategoryStatus}
            getTelegramItemStatus={getTelegramItemStatus}
            getTelegramMiniStatusClasses={getTelegramMiniStatusClasses}
            getTelegramPriorityMeta={getTelegramPriorityMeta}
            getTelegramProgressTone={getTelegramProgressTone}
            getTelegramTodoNextStep={getTelegramTodoNextStep}
            inputClass={inputClass}
            jumpToFirstIncompleteTelegramTemplate={jumpToFirstIncompleteTelegramTemplate}
            jumpToTelegramConfigField={jumpToTelegramConfigField}
            jumpToTelegramSection={jumpToTelegramSection}
            jumpToTelegramSetupField={jumpToTelegramSetupField}
            jumpToTelegramTemplate={jumpToTelegramTemplate}
            labelClass={labelClass}
            markTelegramTodoDone={markTelegramTodoDone}
            openSmsPatternCheck={openSmsPatternCheck}
            openTelegramAudiencePanels={openTelegramAudiencePanels}
            openTelegramCategories={openTelegramCategories}
            openTelegramItems={openTelegramItems}
            openTelegramTemplateCheck={openTelegramTemplateCheck}
            openUrgentTelegramTodos={openUrgentTelegramTodos}
            reactivateTelegramTodo={reactivateTelegramTodo}
            renderTelegramFieldLabel={renderTelegramFieldLabel}
            renderTelegramPlainFieldLabel={renderTelegramPlainFieldLabel}
            resetTelegramQuickActionPersonalization={resetTelegramQuickActionPersonalization}
            resetTelegramTodoAssistant={resetTelegramTodoAssistant}
            runTelegramAdminAction={runTelegramAdminAction}
            runTelegramDiagnostics={runTelegramDiagnostics}
            sendTelegramQuickCheck={sendTelegramQuickCheck}
            setAllTelegramCategories={setAllTelegramCategories}
            setAllTelegramItems={setAllTelegramItems}
            setOpenTelegramItems={setOpenTelegramItems}
            setShowTelegramToken={setShowTelegramToken}
            setTelegramStudioMode={setTelegramStudioMode}
            setTelegramTemplateFilter={setTelegramTemplateFilter}
            setTelegramTemplateSearch={setTelegramTemplateSearch}
            setTgQuickMsg={setTgQuickMsg}
            showTelegramToken={showTelegramToken}
            telegramAudienceDestinationCount={telegramAudienceDestinationCount}
            telegramChatIdValue={telegramChatIdValue}
            telegramCoachMessage={telegramCoachMessage}
            telegramConfigChecks={telegramConfigChecks}
            telegramConfigReadiness={telegramConfigReadiness}
            telegramConfigReadyCount={telegramConfigReadyCount}
            telegramConnectionMode={telegramConnectionMode}
            telegramDestinationCount={telegramDestinationCount}
            telegramDiagnosticsViewModel={telegramDiagnosticsViewModel}
            telegramEffectiveFilter={telegramEffectiveFilter}
            telegramFieldInsights={telegramFieldInsights}
            telegramHasProxy={telegramHasProxy}
            telegramMissingItems={telegramMissingItems}
            telegramPinnedQuickActions={telegramPinnedQuickActions}
            telegramProxyValue={telegramProxyValue}
            telegramQuickActionUsageMap={telegramQuickActionUsageMap}
            telegramReadinessLabel={telegramReadinessLabel}
            telegramReadinessScore={telegramReadinessScore}
            telegramRecentChatsViewModel={telegramRecentChatsViewModel}
            telegramSetupCoachMessage={telegramSetupCoachMessage}
            telegramSetupDone={telegramSetupDone}
            telegramSetupItems={telegramSetupItems}
            telegramSetupPercent={telegramSetupPercent}
            telegramSmartActions={telegramSmartActions}
            telegramSpotlightTarget={telegramSpotlightTarget}
            telegramStudioMode={telegramStudioMode}
            telegramTemplateDefs={telegramTemplateDefs}
            telegramTemplateFilter={telegramTemplateFilter}
            telegramTemplateSearch={telegramTemplateSearch}
            telegramTodoDoneMap={telegramTodoDoneMap}
            telegramTodoSummary={telegramTodoSummary}
            telegramTodoTopItems={telegramTodoTopItems}
            telegramTokenValue={telegramTokenValue}
            telegramUsernameValue={telegramUsernameValue}
            telegramسراسریCompletionPercent={telegramسراسریCompletionPercent}
            telegramسراسریSummary={telegramسراسریSummary}
            tgAudienceMeta={tgAudienceMeta}
            tgCategoryMeta={tgCategoryMeta}
            tgChatLookupHint={tgChatLookupHint}
            tgChatLookupLoading={tgChatLookupLoading}
            tgDiagnostics={tgDiagnostics}
            tgDiagnosticsBusyAction={tgDiagnosticsBusyAction}
            tgDiagnosticsLoading={tgDiagnosticsLoading}
            tgHealth={tgHealth}
            tgIsChecking={tgIsChecking}
            tgIsSendingQuick={tgIsSendingQuick}
            tgQuickMsg={tgQuickMsg}
            tgRecentChats={tgRecentChats}
            toggleTelegramAudiencePanel={toggleTelegramAudiencePanel}
            toggleTelegramCategory={toggleTelegramCategory}
            toggleTelegramItem={toggleTelegramItem}
            toggleTelegramQuickActionPin={toggleTelegramQuickActionPin}
            visibleTelegramItemsCount={visibleTelegramItemsCount}
          />

          {tab === 'pricing' && (
            <SettingsPricingPanel
              pricingLearningStats={pricingLearningStats}
              pricingDataStatus={pricingDataStatus}
              refreshPricingLearningData={refreshPricingLearningData}
              resetPricingSettings={resetPricingSettings}
              resetPricingLearning={resetPricingLearning}
              pricingStrategyAdvisor={pricingStrategyAdvisor}
              pricingSettings={pricingSettings}
              pricingStrategyLabels={pricingStrategyLabels}
              applyAdvisorStrategy={applyAdvisorStrategy}
              updatePricingSettings={updatePricingSettings}
              pricingDecisionSearch={pricingDecisionSearch}
              setPricingDecisionSearch={setPricingDecisionSearch}
              pricingDecisionActionFilter={pricingDecisionActionFilter}
              setPricingDecisionActionFilter={setPricingDecisionActionFilter}
              pricingDecisionDeltaFilter={pricingDecisionDeltaFilter}
              setPricingDecisionDeltaFilter={setPricingDecisionDeltaFilter}
              pricingDecisionDateFrom={pricingDecisionDateFrom}
              setPricingDecisionDateFrom={setPricingDecisionDateFrom}
              pricingDecisionDateTo={pricingDecisionDateTo}
              setPricingDecisionDateTo={setPricingDecisionDateTo}
              pricingDecisionLog={pricingDecisionLog}
              exportPricingDecisionLogExcel={exportPricingDecisionLogExcel}
              exportPricingDecisionLogPdf={exportPricingDecisionLogPdf}
              normalizePricingDateInput={normalizePricingDateInput}
              formatPricingDatePreview={formatPricingDatePreview}
            />
          )}

          <SettingsRemindersPanel tab={tab} />

          <SettingsSmartPanel
            tab={tab}
            isFeatureSettingEnabled={isFeatureSettingEnabled}
            setNotification={setNotification}
          />

          <SettingsStylePanel tab={tab} />

          <SettingsUsersPanel
            tab={tab}
            userStatsCards={userStatsCards}
            labelClass={labelClass}
            inputClass={inputClass}
            userSearchQuery={userSearchQuery}
            setUserSearchQuery={setUserSearchQuery}
            userRoleFilter={userRoleFilter}
            setUserRoleFilter={setUserRoleFilter}
            roles={roles}
            users={users}
            filteredUsers={filteredUsers}
            userRoleSummaries={userRoleSummaries}
            openAddUserModal={openAddUserModal}
            refreshUsersData={refreshUsersData}
            isRefreshingUsers={isRefreshingUsers}
            currentUserId={currentUserId}
            getRoleLabelFa={getRoleLabelFa}
            openEditUserModal={openEditUserModal}
            openResetPasswordModal={openResetPasswordModal}
            openDeleteUserModal={openDeleteUserModal}
          />

          <SettingsDataPanel
            tab={tab}
            settingsSectionCard={settingsSectionCard}
            inputClass={inputClass}
            backupModeLabel={backupModeLabel}
            backupScheduleTime={backupScheduleTime}
            backupFeedbackTone={backupFeedbackTone}
            backupFeedbackIcon={backupFeedbackIcon}
            backupFeedbackLabel={backupFeedbackLabel}
            backupStatusClass={backupStatusClass}
            backupEnabled={backupEnabled}
            backupStatusLabel={backupStatusLabel}
            backupSummaryTone={backupSummaryTone}
            backupNextRunLabel={backupNextRunLabel}
            backupList={backupList}
            backupSettingsDirty={backupSettingsDirty}
            backupScheduleMode={backupScheduleMode}
            backupScheduleWeekdays={backupScheduleWeekdays}
            backupScheduleIntervalHours={backupScheduleIntervalHours}
            backupTimezone={backupTimezone}
            backupRetention={backupRetention}
            isSavingBackupSchedule={isSavingBackupSchedule}
            isLoadingBackups={isLoadingBackups}
            isRestoringDb={isRestoringDb}
            backupOperationKey={backupOperationKey}
            restoreProgress={restoreProgress}
            restoreHistory={restoreHistory}
            dbFileInputRef={dbFileInputRef}
            handleBackup={handleBackup}
            handleSaveBackupSchedule={handleSaveBackupSchedule}
            setBackupEnabled={setBackupEnabled}
            setBackupScheduleMode={setBackupScheduleMode}
            handleBackupTimeInputChange={handleBackupTimeInputChange}
            handleBackupTimeInputBlur={handleBackupTimeInputBlur}
            setBackupScheduleWeekdays={setBackupScheduleWeekdays}
            setBackupScheduleIntervalHours={setBackupScheduleIntervalHours}
            setBackupTimezone={setBackupTimezone}
            setBackupRetention={setBackupRetention}
            handleCreateBackupNow={handleCreateBackupNow}
            fetchBackups={fetchBackups}
            handleDownloadBackupFile={handleDownloadBackupFile}
            handleCheckRestore={handleCheckRestore}
            handleRestoreFromBackup={handleRestoreFromBackup}
            handleDeleteBackupFile={handleDeleteBackupFile}
            handleDbFileChange={handleDbFileChange}
          />
            </div>
          </div>

        <SettingsSaveFooter
          tab={tab}
          infoChanged={infoChanged}
          isSaving={isSaving}
          onSave={() => {
            if (tab === 'telegram') {
              void handleTelegramSettingsSubmit();
              return;
            }
            void handleBusinessInfoSubmit();
          }}
        />
	        </section>
      </div>
    </>
  );
};

export default SettingsWorkspaceSection;
