import React from "react";
import { Link, useParams } from "react-router-dom";
import { MiniAppDataState } from "../components/MiniAppDataState";
import { formatCustomerDate, formatToman } from "../format";
import { useMiniAppQuery } from "../hooks/useMiniAppQuery";
import type { StaffCustomerDetail as StaffCustomerDetailData } from "../types";

export const StaffCustomerDetail: React.FC = () => {
  const { id } = useParams();
  const query = useMiniAppQuery<StaffCustomerDetailData>(`/api/miniapp/staff/customers/${id}`);
  if (!query.data) return <MiniAppDataState loading={query.loading} error={query.error} retry={query.retry} />;
  const data = query.data;
  return <div><header className="border-b border-border pb-4"><p className="m-0 text-xs text-mutedText">مشتری #{data.customer.customerId.toLocaleString("fa-IR")}</p><h1 className="mb-0 mt-1 text-xl font-black">{data.customer.fullName}</h1><p className="mb-0 mt-2 text-sm text-mutedText">{data.customer.phoneNumber || "شماره تماس ثبت نشده"}</p></header>
    <section className="py-4"><div className="flex items-start justify-between gap-3"><span className="text-xs text-mutedText">وضعیت حساب</span><strong className={`text-xs ${data.customer.accountState === "debtor" ? "text-danger" : data.customer.accountState === "creditor" ? "text-success" : "text-mutedText"}`}>{data.customer.accountStateLabel}</strong></div><p className="mb-0 mt-2 break-words text-2xl font-black tabular-nums">{formatToman(Math.abs(data.customer.balance))}</p></section>
    <section className="mt-2"><h2 className="m-0 border-b border-border pb-2 text-sm font-black">اقساط</h2><dl className="m-0 grid grid-cols-2 gap-x-4 text-xs"><div className="border-b border-border py-3"><dt className="text-mutedText">قرارداد فعال</dt><dd className="m-0 mt-1 font-black">{data.installments.activeCount.toLocaleString("fa-IR")}</dd></div><div className="border-b border-border py-3"><dt className="text-mutedText">دارای معوق</dt><dd className="m-0 mt-1 font-black text-danger">{data.installments.overdueCount.toLocaleString("fa-IR")}</dd></div></dl>{data.installments.nextDue ? <Link to={`/installments/${data.installments.nextDue.saleId}`} className="mt-3 flex min-h-12 items-center justify-between gap-3 text-foreground no-underline"><span className="text-xs text-mutedText">سررسید بعدی · {formatCustomerDate(data.installments.nextDue.dueDate)}</span><strong className="text-xs tabular-nums">{formatToman(data.installments.nextDue.amount)}</strong></Link> : null}</section>
    <section className="mt-6"><h2 className="m-0 border-b border-border pb-2 text-sm font-black">۵ خرید اخیر</h2>{data.recentPurchases.length ? <ul className="m-0 list-none divide-y divide-border p-0">{data.recentPurchases.map((item) => <li key={`${item.invoiceRef}-${item.date}`} className="py-3"><div className="flex items-start justify-between gap-3"><span className="min-w-0"><strong className="block truncate text-sm">{item.itemSummary}</strong><small className="mt-1 block text-mutedText">{formatCustomerDate(item.date)} · {item.type === "installment" ? "اقساطی" : "فروش"}</small></span><strong className="shrink-0 text-xs tabular-nums">{formatToman(item.total)}</strong></div></li>)}</ul> : <p className="py-6 text-center text-xs text-mutedText">خریدی ثبت نشده است.</p>}</section>
    <section className="mt-6"><h2 className="m-0 border-b border-border pb-2 text-sm font-black">گردش حساب اخیر</h2>{data.recentLedger.length ? <ul className="m-0 list-none divide-y divide-border p-0">{data.recentLedger.map((item, index) => <li key={`${item.date}-${index}`} className="py-3"><div className="flex items-start justify-between gap-3"><span className="min-w-0"><strong className="block text-sm leading-6">{item.description}</strong><small className="mt-1 block text-mutedText">{formatCustomerDate(item.date)}</small></span><span className="shrink-0 text-left text-xs font-bold tabular-nums">{formatToman(item.debit || item.credit)}<small className="mt-1 block font-medium text-mutedText">مانده {formatToman(Math.abs(item.runningBalance))}</small></span></div></li>)}</ul> : <p className="py-6 text-center text-xs text-mutedText">گردش حسابی ثبت نشده است.</p>}</section>
  </div>;
};
