import React from "react";
import { Link, useParams } from "react-router-dom";
import { MiniAppDataState } from "../components/MiniAppDataState";
import { formatCustomerDate, formatToman } from "../format";
import { useMiniAppQuery } from "../hooks/useMiniAppQuery";
import type { StaffInstallmentDetail as StaffInstallmentDetailData } from "../types";

const statusLabel = { paid: "پرداخت‌شده", overdue: "معوق", today: "سررسید امروز", upcoming: "آینده" } as const;
export const StaffInstallmentDetail: React.FC = () => {
  const { id } = useParams();
  const query = useMiniAppQuery<StaffInstallmentDetailData>(`/api/miniapp/staff/installments/${id}`);
  if (!query.data) return <MiniAppDataState loading={query.loading} error={query.error} retry={query.retry} />;
  const sale = query.data;
  return <div><header className="border-b border-border pb-4"><p className="m-0 text-xs text-mutedText">قرارداد #{sale.saleId.toLocaleString("fa-IR")} · {sale.status}</p><h1 className="mb-0 mt-1 text-xl font-black">{sale.itemSummary}</h1><Link to={`/customers/${sale.customer.id}`} className="mt-2 block text-sm font-bold text-primary no-underline">{sale.customer.fullName}</Link><p className="mb-0 mt-1 text-xs text-mutedText">فروش {formatCustomerDate(sale.saleDate)}</p></header>
    <dl className="m-0 grid grid-cols-2 gap-x-4 text-xs"><div className="border-b border-border py-3"><dt className="text-mutedText">مبلغ فروش</dt><dd className="m-0 mt-1 break-words font-black tabular-nums">{formatToman(sale.actualSalePrice)}</dd></div><div className="border-b border-border py-3"><dt className="text-mutedText">پیش‌پرداخت</dt><dd className="m-0 mt-1 break-words font-black tabular-nums">{formatToman(sale.downPayment)}</dd></div><div className="border-b border-border py-3"><dt className="text-mutedText">دریافت‌شده</dt><dd className="m-0 mt-1 break-words font-black tabular-nums text-success">{formatToman(sale.paidAmount)}</dd></div><div className="border-b border-border py-3"><dt className="text-mutedText">مانده</dt><dd className="m-0 mt-1 break-words font-black tabular-nums">{formatToman(sale.remainingAmount)}</dd></div></dl>
    {sale.items.length ? <section className="mt-6"><h2 className="m-0 border-b border-border pb-2 text-sm font-black">اقلام قرارداد</h2><ul className="m-0 list-none divide-y divide-border p-0">{sale.items.map((item, index) => <li key={`${item.description}-${index}`} className="flex items-start justify-between gap-3 py-3 text-sm"><span className="min-w-0">{item.description}<small className="mt-1 block text-mutedText">تعداد {item.quantity.toLocaleString("fa-IR")}</small></span><strong className="shrink-0 text-xs tabular-nums">{formatToman(item.total)}</strong></li>)}</ul></section> : null}
    <section className="mt-6"><h2 className="m-0 border-b border-border pb-2 text-sm font-black">برنامه پرداخت</h2>{sale.paymentTimeline.length ? <ul className="m-0 list-none divide-y divide-border p-0">{sale.paymentTimeline.map((item) => <li key={item.paymentId} className="flex items-start justify-between gap-3 py-4"><span><strong className="block text-sm">قسط {item.installmentNumber.toLocaleString("fa-IR")}</strong><small className="mt-1 block text-mutedText">{formatCustomerDate(item.dueDate)} · <b className={item.status === "overdue" ? "text-danger" : item.status === "paid" ? "text-success" : "text-mutedText"}>{statusLabel[item.status]}</b></small></span><span className="shrink-0 text-left text-xs font-bold tabular-nums">{formatToman(item.amount)}{item.remainingAmount > 0 && item.remainingAmount !== item.amount ? <small className="mt-1 block font-medium text-mutedText">مانده {formatToman(item.remainingAmount)}</small> : null}</span></li>)}</ul> : <p className="py-6 text-center text-xs text-mutedText">برنامه قسطی ثبت نشده است.</p>}</section>
    {sale.checks.length ? <section className="mt-6"><h2 className="m-0 border-b border-border pb-2 text-sm font-black">چک‌ها</h2><ul className="m-0 list-none divide-y divide-border p-0">{sale.checks.map((check) => <li key={check.checkId} className="flex items-start justify-between gap-3 py-3 text-sm"><span><strong className="block">{check.bankName || "چک قرارداد"}</strong><small className="mt-1 block text-mutedText">{formatCustomerDate(check.dueDate)} · {check.status}</small></span><strong className="shrink-0 text-xs tabular-nums">{formatToman(check.amount)}</strong></li>)}</ul></section> : null}
  </div>;
};
