// Compatibility barrel for legacy imports.
// Public API is routed through modular server/db barrels.
// Residual legacyRuntime exports stay explicit while migrated names are supplied by ./index.
export * from "./index";

export {
  ADMIN_ROLE_NAME, DB_PATH,
  DEFAULT_CATEGORIES, LEGACY_LEDGER_BACKFILL_KEY, MANAGER_ROLE_NAME,
  MARKETER_ROLE_NAME, MOBILE_PHONE_CATEGORY_NAME,
  PHONE_PURCHASE_LEDGER_COLLAPSE_KEY, PHONE_PURCHASE_LEDGER_REFERENCE_TYPES,
  PHONE_SETTLEMENT_LEDGER_TYPES_SQL, PHONE_SETTLEMENT_MANUAL_PAID_SQL,
  PHONE_SETTLEMENT_PAID_SQL, PRODUCT_PURCHASE_LEDGER_REFERENCE_TYPES,
  PURCHASE_LEDGER_REFERENCE_TYPE_SET, SALESPERSON_ROLE_NAME,
  SOLD_PHONE_DAILY_BUY_PRICE_SQL, TECHNICIAN_ROLE_NAME, WAREHOUSE_ROLE_NAME,
  _toNumber, addCustomerFollowupToDb,
  addCustomerLedgerEntryInternal, addCustomerLedgerEntryToDb, addCustomerToDb,
  addPartToRepairInDb, addPartnerLedgerEntryInternal,
  addPartnerLedgerEntryToDb, addPartnerToDb, allAsync, allocateAmountAcrossShares,
  applyStoreOwnershipBackfillFromDb, assertInstallmentPaymentAmountIsValid,
  assignStoreOwnershipReviewItemsFromDb, backfillCustomerLedgerReferences,
  backfillLegacyHistoryAndLedgers, buildLegacyAccessoriesReportFromDb,
  buildLegacyComputedSales, buildLegacyPhonesReportFromDb,
  buildLegacySettlementReportFromDb, buildPhonePurchaseDescription,
  buildSaleProfitSnapshotResponse, bumpTelegramLinkRequestAttempt,
  cancelPartnerSettlementTransactionFromDb, closeCustomerFollowupInDb,
  closeDbConnection, createDefaultOwnershipCore, createOwnershipProfileFromDb, createPartnerSettlementTransactionFromDb,
  createProfitShareProfileFromDb, createRepairInDb,
  createStorePartnerFromDb, createTelegramLinkToken,
  deleteCustomerFromDb, deleteCustomerLedgerEntryFromDb,
  deleteInstallmentTransactionCustomerLedger,
  deletePartFromRepairInDb, deletePartnerFromDb, deletePartnerLedgerEntryFromDb,
  ensureDefaultBusinessSettings,
  ensureFts5UnifiedSearch, ensureReportSavedFiltersTable, execAsync,
  fetchLatestPurchaseLedgerRowForReference, finalizeRepairInDb,
  fromShamsiStringToISO, getAllCustomersWithBalanceFromDb,
  getAllPartnersWithBalanceFromDb, getAllRepairsFromDb,
  getAsync,
  getColumnNamesSafe, getCustomerByIdFromDb, getCustomerLedgerInsightsFromDb,
  getDashboardSalesChartData, getDbInstance, getDefaultOwnershipProfileFromDb,
  getDefaultProfitShareProfileFromDb, getInstallmentPaymentDetailsForSms, getInstallmentPaymentLedgerMeta,
  getLedgerForCustomerFromDb, getLedgerForPartnerFromDb,
  getLegacyPartnerCandidatesFromDb, getLegacySaleRowsForReports,
  getLinkedPartnerByChatId, getOrCreateMobilePhoneCategory, getOwnershipLinesByProfileId,
  getPartnerByIdFromDb, getPartnerProfitReportFromDb,
  getPendingTelegramLinkRequestByChatId, getPendingTelegramLinkTokenByChatId,
  getPhoneHistoryEventClass, getProfileItems, getProfitShareLinesByProfileId,
  getPurchasedItemsFromPartnerDb,
  getRepairByIdFromDb,
  getRepairDetailsForSms, getRepairFinancialSummary,
  getRepairsReadyForPickupFromDb, getStoreOwnershipCoverageFromDb, getTelegramLinkTokenByPlainToken,
  hasStoreOwnershipCoreTables, initSearchIndexIfNeeded, initializeDatabaseInternal,
  linkCustomerTelegramById, linkCustomerTelegramByPhone,
  linkPartnerTelegramByPhone, listCustomerFollowupsFromDb, listOwnershipProfilesFromDb, listPartnerSettlementTransactionsFromDb,
  listProfitShareProfilesFromDb, listStoreOwnershipReviewQueueFromDb,
  listStorePartnersFromDb, markTelegramLinkRequestVerified, markTelegramLinkTokenStatus,
  normalizeCheckStatus, normalizeIranPhone, normalizeMoney, normalizePercent,
  normalizePhonePurchaseLedgers, normalizeShareLines, parseLedgerChangeHistory,
  persistSaleProfitSnapshotItem, previewStoreOwnershipBackfillFromDb,
  purgeProfitSnapshotsForSource, rebuildSearchIndexInternal,
  recalcCustomerBalances, recalcCustomerBalancesInternal, recalcPartnerBalances,
  replaceOwnershipProfileItems,
  replaceProfitShareProfileItems, resolveHistoryWindow,
  resolveOwnershipContextByProfileId, resolvePhoneCostBasis,
  resolvePhoneCostBasisAmount, resolvePhoneHistoryActor, runAsync, safeJsonParse,
  safeJsonStringify, saveStoreOwnershipConfigurationFromDb, seedDefaultCategories,
  seedInitialRoles, setCustomerRiskOverrideInDb,
  snapshotInstallmentSaleProfitAllocations, stringifyLedgerChangeHistory,
  summarizeLegacyProfitRows, syncInstallmentTransactionCustomerLedger,
  syncPhoneCostBasisSnapshots, tableExists, toAccountingNumber,
  unlinkPartnerTelegram, updateCustomerFollowupInDb,
  updateCustomerInDb, updateCustomerLedgerEntryInDb, updateCustomerTagsInDb,
  updatePartnerInDb,
  updatePartnerLedgerEntryInDb, updateRepairInDb,
  updateSaleProfitSnapshotSourceStatus, updateStorePartnerFromDb, upsertTelegramLinkRequest
} from "./legacyRuntime";

export type {
  AbcItem, AdjustStockPayload, AgingBucket, AgingReceivableRow, CashflowDay,
  CashflowReport, CheckStatus, CohortRow, CustomerFollowupPayload,
  CustomerLedgerInsights, CustomerPayload, DashboardLayoutsPayload, DeadStockItem,
  ExpenseCategory, ExpensePayload, InstallmentCheckInfo, InstallmentPaymentStatus,
  InstallmentSalePayload, InventoryTurnoverReport, LedgerChangeHistoryEntry,
  LedgerEntryPayload, OldMobilePhonePayload, OverallStatus, PartnerPayload,
  PhoneCostBasisSource, PhoneEntryPayload, PhoneEntryUpdatePayload,
  PhoneHistoryActor, PhoneInventoryEventPayload, ProductPayload, ProfitShareLine,
  PurchaseReceiptItemPayload, PurchaseReceiptPayload, RecurringExpensePayload,
  RecurringExpensePaymentPayload, RepairFinancialSummary, ResolvedOwnershipContext,
  RfmItem, SaleDataPayload, SaleProfitSnapshotItemInput, SavedFilterRow,
  SettingItem, ShareInput, StockCountCreatePayload, TelegramLinkRequestRow,
  TelegramLinkRequestStatus, UpdateProductPayload, UserForDb, UserUpdatePayload
} from "./legacyRuntime";
