// Extracted from ../smartInsightContracts.ts; type-only compatibility surface preserved.
export type MlCandidateModelPackageSummaryPayload = {
  generatedAt?: string;
  currentCandidateModelPackage?: {
    status?: string;
    recommendation?: string;
    readinessScorePct?: number | null;
    importId?: number | null;
    artifactMetadataId?: number | null;
    approvalReviewId?: number | null;
    modelKey?: string | null;
    modelVersion?: string | null;
    artifactChecksumSha256?: string | null;
    modelExecutionAllowed?: boolean;
    runtimeInvocationAllowed?: boolean;
    inferenceEndpointExposed?: boolean;
    productionIntegrationAllowed?: boolean;
    decisionAutomationAllowed?: boolean;
    canChangeInventoryOrAccounting?: boolean;
    blockerCount?: number;
    warningCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastCandidateModelPackages?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlCandidatePackageIntakeBinderSummaryPayload = {
  generatedAt?: string;
  currentCandidatePackageIntakeBinder?: {
    status?: string;
    recommendation?: string;
    readinessScorePct?: number | null;
    packageId?: number | null;
    importId?: number | null;
    modelKey?: string | null;
    modelVersion?: string | null;
    artifactChecksumSha256?: string | null;
    modelExecutionAllowed?: boolean;
    runtimeInvocationAllowed?: boolean;
    inferenceEndpointExposed?: boolean;
    artifactActivationAllowed?: boolean;
    artifactBytesLoadingAllowed?: boolean;
    artifactIntakeCanLoadBytes?: boolean;
    artifactIntakeCanPersistBytes?: boolean;
    quarantineCanExecuteArtifact?: boolean;
    quarantineCanActivateArtifact?: boolean;
    productionIntegrationAllowed?: boolean;
    decisionAutomationAllowed?: boolean;
    canChangeInventoryOrAccounting?: boolean;
    blockerCount?: number;
    warningCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastCandidatePackageIntakeBinders?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlCandidatePackageHumanReviewSignoffSummaryPayload = {
  generatedAt?: string;
  currentCandidatePackageHumanReviewSignoff?: {
    status?: string;
    recommendation?: string;
    readinessScorePct?: number | null;
    binderId?: number | null;
    packageId?: number | null;
    modelKey?: string | null;
    modelVersion?: string | null;
    artifactChecksumSha256?: string | null;
    humanReviewRequired?: boolean;
    humanReviewEvidenceProvided?: boolean;
    signoffIsProductionApproval?: boolean;
    signoffCanLoadPackageBytes?: boolean;
    signoffCanPersistArtifactBytes?: boolean;
    signoffCanExecuteModel?: boolean;
    signoffCanInvokeRuntime?: boolean;
    signoffCanExposeInferenceEndpoint?: boolean;
    signoffCanActivateArtifact?: boolean;
    signoffCanDeployArtifact?: boolean;
    signoffCanProductionScore?: boolean;
    modelExecutionAllowed?: boolean;
    runtimeInvocationAllowed?: boolean;
    inferenceEndpointExposed?: boolean;
    artifactActivationAllowed?: boolean;
    artifactBytesLoadingAllowed?: boolean;
    productionIntegrationAllowed?: boolean;
    decisionAutomationAllowed?: boolean;
    canChangeInventoryOrAccounting?: boolean;
    blockerCount?: number;
    warningCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastCandidatePackageHumanReviewSignoffs?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlCandidatePackageHumanSignoffArchivePackSummaryPayload = {
  generatedAt?: string;
  currentCandidatePackageHumanSignoffArchivePack?: {
    status?: string;
    recommendation?: string;
    readinessScorePct?: number | null;
    signoffId?: number | null;
    packageId?: number | null;
    modelKey?: string | null;
    modelVersion?: string | null;
    artifactChecksumSha256?: string | null;
    signedReviewHash?: string | null;
    archivePackIsProductionApproval?: boolean;
    archivePackCanLoadPackageBytes?: boolean;
    archivePackCanPersistArtifactBytes?: boolean;
    archivePackCanExecuteModel?: boolean;
    archivePackCanInvokeRuntime?: boolean;
    archivePackCanExposeInferenceEndpoint?: boolean;
    archivePackCanActivateArtifact?: boolean;
    archivePackCanDeployArtifact?: boolean;
    archivePackCanProductionScore?: boolean;
    archivePackCanScheduleRetentionJobs?: boolean;
    archivePackCanDeleteOrPurge?: boolean;
    archivePackMetadataOnly?: boolean;
    retentionPolicyLocked?: boolean;
    modelExecutionAllowed?: boolean;
    runtimeInvocationAllowed?: boolean;
    inferenceEndpointExposed?: boolean;
    artifactActivationAllowed?: boolean;
    artifactBytesLoadingAllowed?: boolean;
    productionIntegrationAllowed?: boolean;
    decisionAutomationAllowed?: boolean;
    canChangeInventoryOrAccounting?: boolean;
    blockerCount?: number;
    warningCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastCandidatePackageHumanSignoffArchivePacks?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlCandidatePackageArchiveRetentionReviewBinderSummaryPayload = {
  generatedAt?: string;
  currentCandidatePackageArchiveRetentionReviewBinder?: {
    status?: string;
    recommendation?: string;
    readinessScorePct?: number | null;
    archivePackId?: number | null;
    signedArchiveHash?: string | null;
    signoffId?: number | null;
    packageId?: number | null;
    retentionReviewBinderIsProductionApproval?: boolean;
    retentionReviewBinderCanLoadArchiveBytes?: boolean;
    retentionReviewBinderCanLoadPackageBytes?: boolean;
    retentionReviewBinderCanPersistArtifactBytes?: boolean;
    retentionReviewBinderCanExecuteModel?: boolean;
    retentionReviewBinderCanInvokeRuntime?: boolean;
    retentionReviewBinderCanExposeInferenceEndpoint?: boolean;
    retentionReviewBinderCanActivateArtifact?: boolean;
    retentionReviewBinderCanDeployArtifact?: boolean;
    retentionReviewBinderCanProductionScore?: boolean;
    retentionReviewBinderCanScheduleRetentionJobs?: boolean;
    retentionReviewBinderCanDeleteOrPurge?: boolean;
    retentionReviewBinderMetadataOnly?: boolean;
    retentionPolicyLocked?: boolean;
    retentionExecutionAllowed?: boolean;
    automaticDeletionAllowed?: boolean;
    purgeJobAllowed?: boolean;
    modelExecutionAllowed?: boolean;
    runtimeInvocationAllowed?: boolean;
    inferenceEndpointExposed?: boolean;
    artifactActivationAllowed?: boolean;
    artifactBytesLoadingAllowed?: boolean;
    productionIntegrationAllowed?: boolean;
    decisionAutomationAllowed?: boolean;
    canChangeInventoryOrAccounting?: boolean;
    blockerCount?: number;
    warningCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastCandidatePackageArchiveRetentionReviewBinders?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlCandidatePackageArchiveRetentionReviewSignoffSummaryPayload = {
  generatedAt?: string;
  currentCandidatePackageArchiveRetentionReviewSignoff?: {
    status?: string;
    recommendation?: string;
    readinessScorePct?: number | null;
    retentionReviewBinderId?: number | null;
    signedRetentionReviewBinderHash?: string | null;
    retentionReviewHumanSignoffRequired?: boolean;
    retentionReviewSignoffEvidenceProvided?: boolean;
    retentionReviewSignoffIsProductionApproval?: boolean;
    retentionReviewSignoffCanLoadArchiveBytes?: boolean;
    retentionReviewSignoffCanLoadPackageBytes?: boolean;
    retentionReviewSignoffCanPersistArtifactBytes?: boolean;
    retentionReviewSignoffCanExecuteModel?: boolean;
    retentionReviewSignoffCanExposeInferenceEndpoint?: boolean;
    retentionReviewSignoffCanActivateArtifact?: boolean;
    retentionReviewSignoffCanDeployArtifact?: boolean;
    retentionReviewSignoffCanProductionScore?: boolean;
    retentionReviewSignoffCanScheduleRetentionJobs?: boolean;
    retentionReviewSignoffCanDeleteOrPurge?: boolean;
    retentionReviewSignoffMetadataOnly?: boolean;
    retentionPolicyLocked?: boolean;
    retentionExecutionAllowed?: boolean;
    automaticDeletionAllowed?: boolean;
    purgeJobAllowed?: boolean;
    modelExecutionAllowed?: boolean;
    runtimeInvocationAllowed?: boolean;
    inferenceEndpointExposed?: boolean;
    artifactActivationAllowed?: boolean;
    artifactBytesLoadingAllowed?: boolean;
    productionIntegrationAllowed?: boolean;
    decisionAutomationAllowed?: boolean;
    canChangeInventoryOrAccounting?: boolean;
    blockerCount?: number;
    warningCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastCandidatePackageArchiveRetentionReviewSignoffs?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlCandidatePackageRetentionSignoffArchivePackSummaryPayload = {
  generatedAt?: string;
  currentCandidatePackageRetentionSignoffArchivePack?: {
    status?: string;
    recommendation?: string;
    readinessScorePct?: number | null;
    retentionReviewSignoffId?: number | null;
    signedRetentionReviewSignoffHash?: string | null;
    retentionSignoffArchivePackIsProductionApproval?: boolean;
    retentionSignoffArchivePackCanLoadArchiveBytes?: boolean;
    retentionSignoffArchivePackCanLoadPackageBytes?: boolean;
    retentionSignoffArchivePackCanPersistArtifactBytes?: boolean;
    retentionSignoffArchivePackCanExecuteModel?: boolean;
    retentionSignoffArchivePackCanExposeInferenceEndpoint?: boolean;
    retentionSignoffArchivePackCanActivateArtifact?: boolean;
    retentionSignoffArchivePackCanDeployArtifact?: boolean;
    retentionSignoffArchivePackCanProductionScore?: boolean;
    retentionSignoffArchivePackCanScheduleRetentionJobs?: boolean;
    retentionSignoffArchivePackCanDeleteOrPurge?: boolean;
    retentionSignoffArchivePackMetadataOnly?: boolean;
    retentionPolicyLocked?: boolean;
    retentionExecutionAllowed?: boolean;
    automaticDeletionAllowed?: boolean;
    purgeJobAllowed?: boolean;
    modelExecutionAllowed?: boolean;
    runtimeInvocationAllowed?: boolean;
    inferenceEndpointExposed?: boolean;
    artifactActivationAllowed?: boolean;
    artifactBytesLoadingAllowed?: boolean;
    productionIntegrationAllowed?: boolean;
    decisionAutomationAllowed?: boolean;
    canChangeInventoryOrAccounting?: boolean;
    blockerCount?: number;
    warningCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastCandidatePackageRetentionSignoffArchivePacks?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlCandidatePackageRetentionArchiveFinalAuditSnapshotSummaryPayload = {
  generatedAt?: string;
  currentCandidatePackageRetentionArchiveFinalAuditSnapshot?: {
    status?: string;
    recommendation?: string;
    readinessScorePct?: number | null;
    retentionSignoffArchivePackId?: number | null;
    signedRetentionSignoffArchiveHash?: string | null;
    retentionArchiveFinalAuditSnapshotIsProductionApproval?: boolean;
    retentionArchiveFinalAuditSnapshotCanLoadArchiveBytes?: boolean;
    retentionArchiveFinalAuditSnapshotCanLoadPackageBytes?: boolean;
    retentionArchiveFinalAuditSnapshotCanPersistArtifactBytes?: boolean;
    retentionArchiveFinalAuditSnapshotCanExecuteModel?: boolean;
    retentionArchiveFinalAuditSnapshotCanExposeInferenceEndpoint?: boolean;
    retentionArchiveFinalAuditSnapshotCanActivateArtifact?: boolean;
    retentionArchiveFinalAuditSnapshotCanDeployArtifact?: boolean;
    retentionArchiveFinalAuditSnapshotCanProductionScore?: boolean;
    retentionArchiveFinalAuditSnapshotCanScheduleRetentionJobs?: boolean;
    retentionArchiveFinalAuditSnapshotCanDeleteOrPurge?: boolean;
    retentionArchiveFinalAuditSnapshotMetadataOnly?: boolean;
    retentionPolicyLocked?: boolean;
    finalAuditSnapshotImmutable?: boolean;
    retentionExecutionAllowed?: boolean;
    automaticDeletionAllowed?: boolean;
    purgeJobAllowed?: boolean;
    modelExecutionAllowed?: boolean;
    runtimeInvocationAllowed?: boolean;
    inferenceEndpointExposed?: boolean;
    artifactActivationAllowed?: boolean;
    artifactBytesLoadingAllowed?: boolean;
    productionIntegrationAllowed?: boolean;
    decisionAutomationAllowed?: boolean;
    canChangeInventoryOrAccounting?: boolean;
    blockerCount?: number;
    warningCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastCandidatePackageRetentionArchiveFinalAuditSnapshots?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlCandidatePackageFinalAuditSnapshotGovernanceSignoffSummaryPayload = {
  generatedAt?: string;
  currentCandidatePackageFinalAuditSnapshotGovernanceSignoff?: {
    status?: string;
    recommendation?: string;
    readinessScorePct?: number | null;
    retentionArchiveFinalAuditSnapshotId?: number | null;
    signedRetentionArchiveFinalAuditSnapshotHash?: string | null;
    finalAuditSnapshotGovernanceSignoffEvidenceProvided?: boolean;
    finalAuditSnapshotGovernanceSignoffIsProductionApproval?: boolean;
    finalAuditSnapshotGovernanceSignoffCanLoadSnapshotBytes?: boolean;
    finalAuditSnapshotGovernanceSignoffCanLoadArchiveBytes?: boolean;
    finalAuditSnapshotGovernanceSignoffCanLoadPackageBytes?: boolean;
    finalAuditSnapshotGovernanceSignoffCanPersistArtifactBytes?: boolean;
    finalAuditSnapshotGovernanceSignoffCanExecuteModel?: boolean;
    finalAuditSnapshotGovernanceSignoffCanExposeInferenceEndpoint?: boolean;
    finalAuditSnapshotGovernanceSignoffCanActivateArtifact?: boolean;
    finalAuditSnapshotGovernanceSignoffCanDeployArtifact?: boolean;
    finalAuditSnapshotGovernanceSignoffCanProductionScore?: boolean;
    finalAuditSnapshotGovernanceSignoffCanScheduleRetentionJobs?: boolean;
    finalAuditSnapshotGovernanceSignoffCanDeleteOrPurge?: boolean;
    finalAuditSnapshotGovernanceSignoffMetadataOnly?: boolean;
    retentionPolicyLocked?: boolean;
    finalAuditSnapshotImmutable?: boolean;
    governanceSignoffIsFinalAuditClosure?: boolean;
    retentionExecutionAllowed?: boolean;
    automaticDeletionAllowed?: boolean;
    purgeJobAllowed?: boolean;
    modelExecutionAllowed?: boolean;
    runtimeInvocationAllowed?: boolean;
    inferenceEndpointExposed?: boolean;
    artifactActivationAllowed?: boolean;
    artifactBytesLoadingAllowed?: boolean;
    productionIntegrationAllowed?: boolean;
    decisionAutomationAllowed?: boolean;
    canChangeInventoryOrAccounting?: boolean;
    blockerCount?: number;
    warningCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastCandidatePackageFinalAuditSnapshotGovernanceSignoffs?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlCandidatePackageGovernanceSignoffArchivePackSummaryPayload = {
  generatedAt?: string;
  currentCandidatePackageGovernanceSignoffArchivePack?: {
    status?: string;
    recommendation?: string;
    readinessScorePct?: number | null;
    finalAuditSnapshotGovernanceSignoffId?: number | null;
    signedFinalAuditSnapshotGovernanceSignoffHash?: string | null;
    governanceSignoffArchivePackIsProductionApproval?: boolean;
    governanceSignoffArchivePackCanLoadSignoffBytes?: boolean;
    governanceSignoffArchivePackCanLoadSnapshotBytes?: boolean;
    governanceSignoffArchivePackCanLoadArchiveBytes?: boolean;
    governanceSignoffArchivePackCanLoadPackageBytes?: boolean;
    governanceSignoffArchivePackCanPersistArtifactBytes?: boolean;
    governanceSignoffArchivePackCanExecuteModel?: boolean;
    governanceSignoffArchivePackCanExposeInferenceEndpoint?: boolean;
    governanceSignoffArchivePackCanActivateArtifact?: boolean;
    governanceSignoffArchivePackCanDeployArtifact?: boolean;
    governanceSignoffArchivePackCanProductionScore?: boolean;
    governanceSignoffArchivePackCanScheduleRetentionJobs?: boolean;
    governanceSignoffArchivePackCanDeleteOrPurge?: boolean;
    governanceSignoffArchivePackMetadataOnly?: boolean;
    retentionPolicyLocked?: boolean;
    finalAuditSnapshotImmutable?: boolean;
    governanceSignoffIsFinalAuditClosure?: boolean;
    retentionExecutionAllowed?: boolean;
    automaticDeletionAllowed?: boolean;
    purgeJobAllowed?: boolean;
    modelExecutionAllowed?: boolean;
    runtimeInvocationAllowed?: boolean;
    inferenceEndpointExposed?: boolean;
    artifactActivationAllowed?: boolean;
    artifactBytesLoadingAllowed?: boolean;
    productionIntegrationAllowed?: boolean;
    decisionAutomationAllowed?: boolean;
    canChangeInventoryOrAccounting?: boolean;
    blockerCount?: number;
    warningCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastCandidatePackageGovernanceSignoffArchivePacks?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlCandidatePackageGovernanceSignoffArchiveFinalizationSummaryPackSummaryPayload = {
  generatedAt?: string;
  currentCandidatePackageGovernanceSignoffArchiveFinalizationSummaryPack?: {
    status?: string;
    recommendation?: string;
    readinessScorePct?: number | null;
    finalAuditSnapshotGovernanceSignoffId?: number | null;
    signedFinalAuditSnapshotGovernanceSignoffHash?: string | null;
    governanceSignoffArchiveFinalizationSummaryPackIsProductionApproval?: boolean;
    governanceSignoffArchiveFinalizationSummaryPackCanLoadSignoffBytes?: boolean;
    governanceSignoffArchiveFinalizationSummaryPackCanLoadSnapshotBytes?: boolean;
    governanceSignoffArchiveFinalizationSummaryPackCanLoadArchiveBytes?: boolean;
    governanceSignoffArchiveFinalizationSummaryPackCanLoadPackageBytes?: boolean;
    governanceSignoffArchiveFinalizationSummaryPackCanPersistArtifactBytes?: boolean;
    governanceSignoffArchiveFinalizationSummaryPackCanExecuteModel?: boolean;
    governanceSignoffArchiveFinalizationSummaryPackCanExposeInferenceEndpoint?: boolean;
    governanceSignoffArchiveFinalizationSummaryPackCanActivateArtifact?: boolean;
    governanceSignoffArchiveFinalizationSummaryPackCanDeployArtifact?: boolean;
    governanceSignoffArchiveFinalizationSummaryPackCanProductionScore?: boolean;
    governanceSignoffArchiveFinalizationSummaryPackCanScheduleRetentionJobs?: boolean;
    governanceSignoffArchiveFinalizationSummaryPackCanDeleteOrPurge?: boolean;
    governanceSignoffArchiveFinalizationSummaryPackMetadataOnly?: boolean;
    retentionPolicyLocked?: boolean;
    finalAuditSnapshotImmutable?: boolean;
    governanceSignoffIsFinalAuditClosure?: boolean;
    retentionExecutionAllowed?: boolean;
    automaticDeletionAllowed?: boolean;
    purgeJobAllowed?: boolean;
    modelExecutionAllowed?: boolean;
    runtimeInvocationAllowed?: boolean;
    inferenceEndpointExposed?: boolean;
    artifactActivationAllowed?: boolean;
    artifactBytesLoadingAllowed?: boolean;
    productionIntegrationAllowed?: boolean;
    decisionAutomationAllowed?: boolean;
    canChangeInventoryOrAccounting?: boolean;
    blockerCount?: number;
    warningCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastCandidatePackageGovernanceSignoffArchiveFinalizationSummaryPacks?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
