// Extracted from ../smartInsightContracts.ts; type-only compatibility surface preserved.
export type MlOfflineArtifactIntakeSummaryPayload = {
  totalArtifacts?: number;
  quarantinedArtifacts?: number;
  rejectedArtifacts?: number;
  needsReviewArtifacts?: number;
  approvedForShadowReviewArtifacts?: number;
  archivedArtifacts?: number;
  duplicateHashCount?: number;
  reviewRecords?: number;
  pendingReviewRecords?: number;
  approvedReviewRecords?: number;
  rejectedReviewRecords?: number;
  signedReviewEvidenceRecords?: number;
  binderReadinessRecords?: number;
  signedBinderManifestRecords?: number;
  governanceSignoffRecords?: number;
  pendingGovernanceSignoffRecords?: number;
  approvedGovernanceSignoffRecords?: number;
  rejectedGovernanceSignoffRecords?: number;
  signedGovernanceSignoffRecords?: number;
  archivePackReadinessRecords?: number;
  signedArchivePackManifestRecords?: number;
  pendingArchivePackRecords?: number;
  rejectedArchivePackRecords?: number;
  retentionPolicyEvidenceRecords?: number;
  preparedRetentionPolicyEvidenceRecords?: number;
  pendingRetentionPolicyEvidenceRecords?: number;
  rejectedRetentionPolicyEvidenceRecords?: number;
  signedRetentionPolicyEvidenceRecords?: number;
  retentionGovernanceReviewRecords?: number;
  approvedRetentionGovernanceReviewRecords?: number;
  pendingRetentionGovernanceReviewRecords?: number;
  rejectedRetentionGovernanceReviewRecords?: number;
  signedRetentionGovernanceReviewRecords?: number;
  retentionGovernanceArchiveRecords?: number;
  preparedRetentionGovernanceArchiveRecords?: number;
  pendingRetentionGovernanceArchiveRecords?: number;
  rejectedRetentionGovernanceArchiveRecords?: number;
  signedRetentionGovernanceArchiveRecords?: number;
  finalizationRecords?: number;
  preparedFinalizationRecords?: number;
  pendingFinalizationRecords?: number;
  rejectedFinalizationRecords?: number;
  signedFinalizationReadinessRecords?: number;
  auditSnapshotRecords?: number;
  preparedAuditSnapshotRecords?: number;
  pendingAuditSnapshotRecords?: number;
  rejectedAuditSnapshotRecords?: number;
  signedAuditSnapshotRecords?: number;
  auditSnapshotGovernanceSignoffRecords?: number;
  acceptedAuditSnapshotGovernanceSignoffRecords?: number;
  pendingAuditSnapshotGovernanceSignoffRecords?: number;
  rejectedAuditSnapshotGovernanceSignoffRecords?: number;
  signedAuditSnapshotGovernanceSignoffRecords?: number;
  auditSnapshotGovernanceArchiveRecords?: number;
  preparedAuditSnapshotGovernanceArchiveRecords?: number;
  pendingAuditSnapshotGovernanceArchiveRecords?: number;
  rejectedAuditSnapshotGovernanceArchiveRecords?: number;
  signedAuditSnapshotGovernanceArchiveRecords?: number;

  validationReviewerAssignmentUx?: {
    phase?: string;
    filterControls?: {
      statuses?: string[];
      priorities?: string[];
      reviewerScopes?: string[];
      [key: string]: unknown;
    };
    activeFilters?: {
      status?: string;
      priority?: string;
      assignedReviewerId?: string | number;
      limit?: number;
      [key: string]: unknown;
    };
    visibleItems?: Array<Record<string, unknown>>;
    totalVisibleItems?: number;
    latestQueueItem?: Record<string, unknown> | null;
    latestAssignmentEvent?: Record<string, unknown> | null;
    evidenceNoteCount?: number;
    assignedVisibleItems?: number;
    unassignedVisibleItems?: number;
    recommendedNextAction?: string;
    safety?: Record<string, unknown>;
    [key: string]: unknown;
  };

  validationEvidenceReviewPackSummary?: {
    totalPacks?: number;
    readyForReviewPacks?: number;
    needsMoreEvidencePacks?: number;
    criticalReviewRequiredPacks?: number;
    closedShadowOnlyPacks?: number;
    quarantineOrRejectRecommendedPacks?: number;
    lowConfidencePacks?: number;
    mediumConfidencePacks?: number;
    highConfidencePacks?: number;
    unresolvedEvidenceGapCount?: number;
    recommendedNextAction?: string;
    latestPack?: {
      id?: number | string;
      queueItemId?: number | string;
      validationResultId?: number | string;
      artifactId?: number | string;
      artifactHash?: string | null;
      packStatus?: string;
      evidenceConfidence?: string;
      evidenceNoteCount?: number;
      assignmentEventCount?: number;
      reviewerNoteCount?: number;
      unresolvedEvidenceGapCount?: number;
      recommendedReviewerAction?: string;
      signedEvidenceReviewPackHash?: string;
      safety?: Record<string, unknown>;
      [key: string]: unknown;
    } | null;
    safety?: Record<string, unknown>;
    [key: string]: unknown;
  };


  validationEvidenceGapClosureMatrixSummary?: {
    totalMatrices?: number;
    noGapsDetectedMatrices?: number;
    closureReadyMatrices?: number;
    partialClosureMatrices?: number;
    needsMoreEvidenceMatrices?: number;
    criticalGapOpenMatrices?: number;
    totalOpenGapCount?: number;
    totalCriticalOpenGapCount?: number;
    totalHighOpenGapCount?: number;
    averageClosureReadinessPct?: number;
    recommendedNextAction?: string;
    latestMatrix?: {
      id?: number | string;
      evidenceReviewPackId?: number | string;
      queueItemId?: number | string;
      validationResultId?: number | string;
      artifactId?: number | string;
      artifactHash?: string | null;
      matrixStatus?: string;
      closureReadinessPct?: number;
      totalGapCount?: number;
      openGapCount?: number;
      closedGapCount?: number;
      blockedGapCount?: number;
      criticalOpenGapCount?: number;
      highOpenGapCount?: number;
      evidenceConfidence?: string;
      recommendedClosureAction?: string;
      signedEvidenceGapClosureMatrixHash?: string;
      safety?: Record<string, unknown>;
      [key: string]: unknown;
    } | null;
    safety?: Record<string, unknown>;
    [key: string]: unknown;
  };
  validationEvidenceClosureSignoffPackSummary?: {
    totalSignoffPacks?: number;
    readyForHumanSignoffPacks?: number;
    signedForFutureShadowOnlyPacks?: number;
    needsMoreEvidencePacks?: number;
    blockedByOpenGapPacks?: number;
    rejectedForArtifactTrustPacks?: number;
    averageSignoffReadinessPct?: number;
    totalChecklistFailCount?: number;
    recommendedNextAction?: string;
    latestSignoffPack?: {
      id?: number | string;
      evidenceGapClosureMatrixId?: number | string;
      evidenceReviewPackId?: number | string;
      queueItemId?: number | string;
      validationResultId?: number | string;
      artifactId?: number | string;
      artifactHash?: string | null;
      signoffPackStatus?: string;
      reviewerDecision?: string;
      signoffReadinessPct?: number;
      checklistPassCount?: number;
      checklistWarningCount?: number;
      checklistFailCount?: number;
      evidenceConfidence?: string;
      recommendedSignoffAction?: string;
      signedEvidenceClosureReviewerSignoffPackHash?: string;
      safety?: Record<string, unknown>;
      [key: string]: unknown;
    } | null;
    safety?: Record<string, unknown>;
    [key: string]: unknown;
  };

  validationFutureShadowEligibilityGateSummary?: {
    totalEligibilityGates?: number;
    eligibleForFutureShadowReviewGates?: number;
    notReadyNeedsMoreEvidenceGates?: number;
    blockedBySignoffGates?: number;
    rejectedForArtifactTrustGates?: number;
    safetyGateBlockedGates?: number;
    averageEligibilityReadinessPct?: number;
    totalBlockerCount?: number;
    totalCriticalBlockerCount?: number;
    recommendedNextAction?: string;
    latestEligibilityGate?: {
      id?: number | string;
      evidenceClosureSignoffPackId?: number | string;
      evidenceGapClosureMatrixId?: number | string;
      evidenceReviewPackId?: number | string;
      queueItemId?: number | string;
      validationResultId?: number | string;
      artifactId?: number | string;
      artifactHash?: string | null;
      gateStatus?: string;
      eligibilityDecision?: string;
      eligibilityReadinessPct?: number;
      blockerCount?: number;
      criticalBlockerCount?: number;
      warningCount?: number;
      evidenceConfidence?: string;
      reviewerDecision?: string;
      signoffPackStatus?: string;
      recommendedEligibilityAction?: string;
      signedFutureShadowEligibilityGateHash?: string;
      safety?: Record<string, unknown>;
      [key: string]: unknown;
    } | null;
    safety?: Record<string, unknown>;
    [key: string]: unknown;
  };



  validationFutureShadowReviewBinderRoutingSummaryPackSummary?: {
    totalRoutingSummaryPacks?: number;
    readyForFutureShadowBoardPacks?: number;
    needsBinderClosurePacks?: number;
    blockedByBinderPacks?: number;
    rejectedForArtifactTrustPacks?: number;
    safetyBlockedPacks?: number;
    averageRoutingReadinessPct?: number;
    totalFailedSectionCount?: number;
    criticalRouteCount?: number;
    highRouteCount?: number;
    recommendedNextAction?: string;
    latestRoutingSummaryPack?: {
      id?: number | string;
      futureShadowEligibilityReviewBinderId?: number | string;
      futureShadowEligibilityGateId?: number | string;
      evidenceClosureSignoffPackId?: number | string;
      evidenceGapClosureMatrixId?: number | string;
      evidenceReviewPackId?: number | string;
      queueItemId?: number | string;
      validationResultId?: number | string;
      artifactId?: number | string;
      artifactHash?: string | null;
      routingPackStatus?: string;
      routingDecision?: string;
      routingReadinessPct?: number;
      routePriority?: string;
      routeLane?: string;
      sectionCount?: number;
      passedSectionCount?: number;
      warningSectionCount?: number;
      failedSectionCount?: number;
      evidenceConfidence?: string;
      binderDecision?: string;
      binderStatus?: string;
      recommendedRoutingAction?: string;
      signedFutureShadowReviewBinderRoutingSummaryPackHash?: string;
      safety?: Record<string, unknown>;
      [key: string]: unknown;
    } | null;
    safety?: Record<string, unknown>;
    [key: string]: unknown;
  };


  validationFutureShadowBoardReviewPacketSummary?: {
    totalBoardReviewPackets?: number;
    readyForFutureShadowBoardReviewPackets?: number;
    needsRoutingClosurePackets?: number;
    blockedByRoutingPackets?: number;
    rejectedForArtifactTrustPackets?: number;
    safetyBlockedPackets?: number;
    averageBoardPacketReadinessPct?: number;
    totalFailedSectionCount?: number;
    criticalBoardReviewCount?: number;
    highBoardReviewCount?: number;
    recommendedNextAction?: string;
    latestBoardReviewPacket?: {
      id?: number | string;
      futureShadowReviewBinderRoutingSummaryPackId?: number | string;
      futureShadowEligibilityReviewBinderId?: number | string;
      futureShadowEligibilityGateId?: number | string;
      evidenceClosureSignoffPackId?: number | string;
      evidenceGapClosureMatrixId?: number | string;
      evidenceReviewPackId?: number | string;
      queueItemId?: number | string;
      validationResultId?: number | string;
      artifactId?: number | string;
      artifactHash?: string | null;
      boardPacketStatus?: string;
      boardPacketDecision?: string;
      boardPacketReadinessPct?: number;
      boardReviewPriority?: string;
      boardReviewLane?: string;
      sectionCount?: number;
      passedSectionCount?: number;
      warningSectionCount?: number;
      failedSectionCount?: number;
      evidenceConfidence?: string;
      routingDecision?: string;
      routingPackStatus?: string;
      routeLane?: string;
      recommendedBoardAction?: string;
      signedFutureShadowBoardReviewPacketHash?: string;
      safety?: Record<string, unknown>;
      [key: string]: unknown;
    } | null;
    safety?: Record<string, unknown>;
    [key: string]: unknown;
  };
  validationFutureShadowBoardReviewDecisionLogSummary?: {
    totalDecisionLogs?: number;
    acceptedForFutureShadowReviewOnlyDecisionLogs?: number;
    needsBoardPacketClosureDecisionLogs?: number;
    blockedByPacketDecisionLogs?: number;
    rejectedForArtifactTrustDecisionLogs?: number;
    safetyBlockedDecisionLogs?: number;
    averageDecisionLogReadinessPct?: number;
    totalFailedSectionCount?: number;
    criticalDecisionLogCount?: number;
    highDecisionLogCount?: number;
    recommendedNextAction?: string;
    latestDecisionLog?: {
      id?: number | string;
      futureShadowBoardReviewPacketId?: number | string;
      futureShadowReviewBinderRoutingSummaryPackId?: number | string;
      futureShadowEligibilityReviewBinderId?: number | string;
      futureShadowEligibilityGateId?: number | string;
      evidenceClosureSignoffPackId?: number | string;
      evidenceGapClosureMatrixId?: number | string;
      evidenceReviewPackId?: number | string;
      queueItemId?: number | string;
      validationResultId?: number | string;
      artifactId?: number | string;
      artifactHash?: string | null;
      decisionLogStatus?: string;
      boardDecision?: string;
      boardDecisionReason?: string;
      decisionLogReadinessPct?: number;
      boardReviewPriority?: string;
      boardDecisionLane?: string;
      sectionCount?: number;
      passedSectionCount?: number;
      warningSectionCount?: number;
      failedSectionCount?: number;
      evidenceConfidence?: string;
      boardPacketDecision?: string;
      boardPacketStatus?: string;
      boardReviewLane?: string;
      recommendedDecisionAction?: string;
      signedFutureShadowBoardReviewDecisionLogHash?: string;
      safety?: Record<string, unknown>;
      [key: string]: unknown;
    } | null;
    safety?: Record<string, unknown>;
    [key: string]: unknown;
  };
  validationFutureShadowEligibilityReviewBinderSummary?: {
    totalReviewBinders?: number;
    readyForFutureShadowReviewBinders?: number;
    needsEligibilityClosureBinders?: number;
    blockedByEligibilityGateBinders?: number;
    rejectedForArtifactTrustBinders?: number;
    safetyBlockedBinders?: number;
    averageBinderReadinessPct?: number;
    totalFailedSectionCount?: number;
    recommendedNextAction?: string;
    latestReviewBinder?: {
      id?: number | string;
      futureShadowEligibilityGateId?: number | string;
      evidenceClosureSignoffPackId?: number | string;
      evidenceGapClosureMatrixId?: number | string;
      evidenceReviewPackId?: number | string;
      queueItemId?: number | string;
      validationResultId?: number | string;
      artifactId?: number | string;
      artifactHash?: string | null;
      binderStatus?: string;
      binderDecision?: string;
      binderReadinessPct?: number;
      sectionCount?: number;
      passedSectionCount?: number;
      warningSectionCount?: number;
      failedSectionCount?: number;
      evidenceConfidence?: string;
      eligibilityDecision?: string;
      gateStatus?: string;
      recommendedBinderAction?: string;
      signedFutureShadowEligibilityReviewBinderHash?: string;
      safety?: Record<string, unknown>;
      [key: string]: unknown;
    } | null;
    safety?: Record<string, unknown>;
    [key: string]: unknown;
  };
  validationReviewQueueSummary?: {
    totalQueueItems?: number;
    openItems?: number;
    assignedItems?: number;
    evidenceRequestedItems?: number;
    deferredItems?: number;
    closedShadowOnlyItems?: number;
    quarantineRecommendedItems?: number;
    rejectRecommendedItems?: number;
    criticalPriorityItems?: number;
    highPriorityItems?: number;
    mediumPriorityItems?: number;
    lowPriorityItems?: number;
    pendingHumanReviewItems?: number;
    latestQueueItem?: {
      id?: number | string;
      validationResultId?: number | string;
      artifactId?: number | string;
      artifactHash?: string | null;
      validationStatus?: string;
      trustScore?: number;
      trustLabel?: string;
      driftRisk?: string;
      reviewPriority?: string;
      queueStatus?: string;
      criticalFindingCount?: number;
      highFindingCount?: number;
      missingEvidenceCount?: number;
      reviewerDecision?: string;
      assignedReviewerId?: string | number | null;
      finalReviewerDecision?: string;
      safety?: Record<string, unknown>;
      [key: string]: unknown;
    } | null;
    safety?: Record<string, unknown>;
    [key: string]: unknown;
  };
  validationSummary?: {
    totalValidationResults?: number;
    passResults?: number;
    warningResults?: number;
    failResults?: number;
    quarantinedResults?: number;
    insufficientMetadataResults?: number;
    criticalFindingResults?: number;
    highFindingResults?: number;
    missingEvidenceResults?: number;
    averageTrustScore?: number;
    latestValidation?: {
      id?: number | string;
      artifactId?: number | string;
      artifactHash?: string | null;
      artifactKind?: string | null;
      schemaVersion?: string | null;
      modelFamily?: string | null;
      validationStatus?: string;
      trustScore?: number;
      trustLabel?: string;
      driftRisk?: string;
      compatibility?: {
        featureContract?: { status?: string; [key: string]: unknown };
        outputContract?: { status?: string; [key: string]: unknown };
        [key: string]: unknown;
      };
      finalReviewSnapshot?: {
        finalReviewerDecision?: string;
        archiveCompletenessStatus?: string;
        exceptionClosureStatus?: string;
        evidenceConfidenceAccepted?: boolean;
        signedAuditGovernanceFinalReviewHash?: string | null;
        notes?: string[];
        [key: string]: unknown;
      };
      safety?: Record<string, unknown>;
      [key: string]: unknown;
    } | null;
    safety?: Record<string, unknown>;
    [key: string]: unknown;
  };
  latestArtifact?: {
    id?: number | string;
    artifactName?: string;
    artifactKind?: string;
    modelKey?: string;
    modelVersion?: string;
    sha256?: string;
    intakeStatus?: string;
    quarantineStatus?: string;
    createdAt?: string;
    [key: string]: unknown;
  } | null;
  latestReview?: {
    id?: number | string;
    artifactId?: number | string;
    reviewDecision?: string;
    reviewStatus?: string;
    signedReviewHash?: string;
    createdAt?: string;
    [key: string]: unknown;
  } | null;
  latestBinder?: {
    id?: number | string;
    artifactId?: number | string;
    binderStatus?: string;
    signedBinderHash?: string;
    exportFileCreated?: boolean;
    artifactBytesIncluded?: boolean;
    createdAt?: string;
    [key: string]: unknown;
  } | null;
  latestGovernanceSignoff?: {
    id?: number | string;
    binderId?: number | string;
    artifactId?: number | string;
    signoffDecision?: string;
    signoffStatus?: string;
    signedGovernanceHash?: string;
    exportFileCreated?: boolean;
    artifactBytesIncluded?: boolean;
    binderActivationAllowed?: boolean;
    createdAt?: string;
    [key: string]: unknown;
  } | null;
  latestArchivePack?: {
    id?: number | string;
    signoffId?: number | string;
    binderId?: number | string;
    artifactId?: number | string;
    archivePackDecision?: string;
    archivePackStatus?: string;
    signedArchivePackHash?: string;
    archiveFileCreated?: boolean;
    artifactBytesIncluded?: boolean;
    retentionJobScheduled?: boolean;
    deletionOrPurgeAllowed?: boolean;
    createdAt?: string;
    [key: string]: unknown;
  } | null;
  latestRetentionPolicyEvidence?: {
    id?: number | string;
    archivePackId?: number | string;
    artifactId?: number | string;
    retentionDecision?: string;
    retentionStatus?: string;
    signedRetentionPolicyHash?: string;
    retentionJobScheduled?: boolean;
    deletionOrPurgeAllowed?: boolean;
    archiveFileCreated?: boolean;
    artifactBytesIncluded?: boolean;
    createdAt?: string;
    [key: string]: unknown;
  } | null;
  latestRetentionGovernanceReview?: {
    id?: number | string;
    retentionPolicyEvidenceId?: number | string;
    artifactId?: number | string;
    governanceReviewDecision?: string;
    governanceReviewStatus?: string;
    signedRetentionGovernanceHash?: string;
    retentionJobScheduled?: boolean;
    deletionOrPurgeAllowed?: boolean;
    archiveFileCreated?: boolean;
    artifactBytesIncluded?: boolean;
    createdAt?: string;
    [key: string]: unknown;
  } | null;
  latestRetentionGovernanceArchive?: {
    id?: number | string;
    retentionGovernanceReviewId?: number | string;
    artifactId?: number | string;
    archiveDecision?: string;
    archiveStatus?: string;
    signedArchiveReadinessHash?: string;
    retentionJobScheduled?: boolean;
    deletionOrPurgeAllowed?: boolean;
    archiveFileCreated?: boolean;
    artifactBytesIncluded?: boolean;
    createdAt?: string;
    [key: string]: unknown;
  } | null;
  latestFinalization?: {
    id?: number | string;
    retentionGovernanceArchiveId?: number | string;
    artifactId?: number | string;
    finalizationDecision?: string;
    finalizationStatus?: string;
    signedFinalizationReadinessHash?: string;
    retentionJobScheduled?: boolean;
    deletionOrPurgeAllowed?: boolean;
    archiveFileCreated?: boolean;
    artifactBytesIncluded?: boolean;
    createdAt?: string;
    [key: string]: unknown;
  } | null;
  latestAuditSnapshot?: {
    id?: number | string;
    finalizationId?: number | string;
    artifactId?: number | string;
    auditSnapshotDecision?: string;
    auditSnapshotStatus?: string;
    snapshotTimestamp?: string;
    signedAuditSnapshotHash?: string;
    retentionJobScheduled?: boolean;
    deletionOrPurgeAllowed?: boolean;
    archiveFileCreated?: boolean;
    artifactBytesIncluded?: boolean;
    createdAt?: string;
    [key: string]: unknown;
  } | null;
  latestAuditSnapshotGovernanceSignoff?: {
    id?: number | string;
    auditSnapshotId?: number | string;
    artifactId?: number | string;
    signoffDecision?: string;
    signoffStatus?: string;
    signedAuditSnapshotGovernanceHash?: string;
    retentionJobScheduled?: boolean;
    deletionOrPurgeAllowed?: boolean;
    archiveFileCreated?: boolean;
    artifactBytesIncluded?: boolean;
    createdAt?: string;
    [key: string]: unknown;
  } | null;
  latestAuditSnapshotGovernanceArchive?: {
    id?: number | string;
    auditSnapshotGovernanceSignoffId?: number | string;
    artifactId?: number | string;
    archiveDecision?: string;
    archiveStatus?: string;
    signedAuditGovernanceArchiveHash?: string;
    retentionJobScheduled?: boolean;
    deletionOrPurgeAllowed?: boolean;
    archiveFileCreated?: boolean;
    artifactBytesIncluded?: boolean;
    createdAt?: string;
    [key: string]: unknown;
  } | null;
  safetyStatus?: {
    artifactExecutionAllowed?: boolean;
    artifactAutoActivationAllowed?: boolean;
    artifactQuarantineRequired?: boolean;
    runtimeInvocationAllowed?: boolean;
    modelExecutionAllowed?: boolean;
    inferenceEndpointExposed?: boolean;
    productionIntegrationAllowed?: boolean;
    decisionAutomationAllowed?: boolean;
    canChangeInventoryOrAccounting?: boolean;
    canChangePricing?: boolean;
    canChangeReports?: boolean;
    canChangeLedger?: boolean;
    canMutateBusinessRecords?: boolean;
    quarantineReviewCanExecuteArtifact?: boolean;
    quarantineReviewCanActivateArtifact?: boolean;
    quarantineReviewCanReleaseToProduction?: boolean;
    quarantineReviewCanMutateBusinessRecords?: boolean;
    quarantineReviewRequiresHumanEvidence?: boolean;
    quarantineReviewStatusMetadataOnly?: boolean;
    binderReadinessCanExportArtifactBytes?: boolean;
    binderReadinessCanExecuteArtifact?: boolean;
    binderReadinessCanActivateArtifact?: boolean;
    binderReadinessCanReleaseToProduction?: boolean;
    binderReadinessCanMutateBusinessRecords?: boolean;
    binderReadinessMetadataOnly?: boolean;
    binderGovernanceSignoffCanExportFiles?: boolean;
    binderGovernanceSignoffCanExecuteArtifact?: boolean;
    binderGovernanceSignoffCanActivateArtifact?: boolean;
    binderGovernanceSignoffCanReleaseToProduction?: boolean;
    binderGovernanceSignoffCanMutateBusinessRecords?: boolean;
    binderGovernanceSignoffMetadataOnly?: boolean;
    binderGovernanceSignoffRequiresHumanApproval?: boolean;
    archivePackReadinessCanCreateFiles?: boolean;
    archivePackReadinessCanIncludeArtifactBytes?: boolean;
    archivePackReadinessCanExecuteArtifact?: boolean;
    archivePackReadinessCanActivateArtifact?: boolean;
    archivePackReadinessCanReleaseToProduction?: boolean;
    archivePackReadinessCanMutateBusinessRecords?: boolean;
    archivePackReadinessCanScheduleRetentionJobs?: boolean;
    archivePackReadinessCanDeleteOrPurge?: boolean;
    archivePackReadinessMetadataOnly?: boolean;
    archivePackReadinessRetentionReady?: boolean;
    [key: string]: unknown;
  };
  execution?: string;
  autoActivation?: string;
  productionInference?: string;
  artifactIntakeMode?: string;
  noBusinessMutation?: boolean;
  [key: string]: unknown;
};
