// Extracted from ../smartInsightContracts.ts; type-only compatibility surface preserved.
import type { MlopsReadinessPayload } from './mlWorkbenchContracts';
import type { PredictiveEnginePayload } from './predictiveContracts';

export type InsightSeverity = 'low' | 'medium' | 'high' | 'critical' | string;
export type SeverityVisualMeta = {
  label: string;
  icon: string;
  badge: string;
  border: string;
  text?: string;
  bg?: string;
  tone?: string;
  dot: string;
  soft: string;
  [key: string]: unknown;
};
export type SeverityMetaMap = Record<string, SeverityVisualMeta>;
export type DecisionStatusKey = 'open' | 'accepted' | 'rejected' | 'dismissed' | 'closed' | string;
export type DecisionStatusMeta = {
  key: string;
  label: string;
};
export type DecisionActionState = {
  isActing: boolean;
  isAccepted: boolean;
  icon: string;
  label: string;
};
export type DecisionMemoryPatch = {
  userDecision?: 'accepted' | 'rejected' | string;
  status?: DecisionStatusKey;
  outcome?: 'positive' | 'negative' | string;
  [key: string]: unknown;
};
export type MoneyFormatter = (value: unknown) => string;
export type PercentFormatter = (value: unknown) => string;
export type NumberFormatter = (value: unknown) => number;
export type ShamsiFormatter = (value: unknown) => string;
export type LocalizedNumberParser = (value: unknown) => number;
export type SmartInsightAction = {
  label: string;
  icon?: string;
  to?: string;
  [key: string]: unknown;
};
export type SmartInsightDecision = {
  decisionLabel?: string;
  statusLabel?: string;
  outcomeLabel?: string;
  occurrenceCount?: number;
  [key: string]: unknown;
};
export type SmartInsightLike = {
  id: string;
  type: string;
  category?: string;
  severity: InsightSeverity;
  score?: number;
  confidence?: number;
  title: string;
  summary: string;
  icon?: string;
  tone?: string;
  reasons: string[];
  actions: SmartInsightAction[];
  decision?: SmartInsightDecision;
  target?: unknown;
  metrics: SmartInsightMetric[];
  actionLabel?: string;
  impactLabel?: string;
  to?: string;
  priority?: number;
  [key: string]: unknown;
};
export type UpdateDecisionMemory = (
  insight: SmartInsightLike,
  patch: DecisionMemoryPatch
) => Promise<void> | void;
export type GetDecisionStatusMeta = (decision?: SmartInsightDecision) => DecisionStatusMeta;
export type GetDecisionActionState = (insight: SmartInsightLike) => DecisionActionState;
export type ReportFormatters = {
  money: MoneyFormatter;
  percent: PercentFormatter;
  num: NumberFormatter;
  shamsi: ShamsiFormatter;
};
export type PricingMoneyFormatter = MoneyFormatter;
export type SmartInsightSummary = {
  totalInsights?: number;
  criticalCount?: number;
  highCount?: number;
  mediumCount?: number;
  lowCount?: number;
  [key: string]: unknown;
};
export type SmartInsightLearning = {
  level?: string;
  label?: string;
  description?: string;
  confidence?: number;
  status?: string;
  signals?: SmartInsightSignal[];
  [key: string]: unknown;
};
export type SmartInsightSignal = {
  label?: string;
  value?: unknown;
  [key: string]: unknown;
};
export type SmartInsightScoreComponent = {
  key: string;
  label: string;
  value: number;
  weight: number;
  evidence: string;
};
export type SmartInsightExecutiveBrain = {
  score?: number | null;
  scoreAvailable?: boolean;
  scoreBasis?: 'live_store_data' | string;
  scoreComponents?: SmartInsightScoreComponent[];
  scoreEvidence?: {
    basis?: string;
    ordersCount?: number;
    insightCount?: number;
    acceptedDecisions?: number;
  };
  tone?: string;
  command?: string;
  narrative?: string;
  status?: string;
  statusLabel?: string;
  confidence?: number;
  actions?: SmartInsightLike[];
  nextBestActions?: SmartInsightLike[];
  [key: string]: unknown;
};
export type SmartInsightPayload = {
  dailyBrief?: string[];
  todayActions?: TodayActionItem[];
  predictiveEngine?: PredictiveEnginePayload;
  mlopsReadiness?: MlopsReadinessPayload;
  executiveBrain?: SmartInsightExecutiveBrain;
  learning?: SmartInsightLearning;
  summary?: SmartInsightSummary & { decisionMemory?: DecisionMemoryOverviewState };
  insights?: SmartInsightLike[];
  hiddenProfit?: HiddenProfitOpportunity[];
  suspiciousAudit?: SuspiciousAuditLike[];
  customerIntelligence?: CustomerIntelligenceCard[];
  pricingRecommendations?: PricingRecommendationRow[];
  salesAgentLeads?: SalesAgentLeadRow[];
  profitEngine?: SmartInsightProfitEnginePayload;
  generatedAt?: string;
  [key: string]: unknown;
};
export type ProfitSummaryLike = {
  grossSales?: number;
  realProfit?: number;
  recognizedProfit?: number;
  profitAtRisk?: number;
  marginPct?: number;
  qualityScore?: number;
  [key: string]: unknown;
};
export type SuspiciousAuditLike = {
  id?: string;
  title?: string;
  severity?: InsightSeverity;
  riskScore?: number;
  [key: string]: unknown;
};
export type AlertSelectionState = {
  filter: string;
  selectedId: string | null;
};
export type UnknownRecord = Record<string, unknown>;
export type SmartInsightMetric = {
  label: string;
  value: string | number;
  icon?: string;
  tone?: string;
  [key: string]: unknown;
};
export type SmartInsightTarget = UnknownRecord | null | undefined;
export type SmartInsightActionPatch = DecisionMemoryPatch;
export type InsightModalPayload = SmartInsightPayload & UnknownRecord;
export type AlertReason = string | {
  label?: string;
  text?: string;
  value?: unknown;
  [key: string]: unknown;
};
export type AlertMetric = {
  label?: string;
  value?: unknown;
  icon?: string;
  tone?: string;
  [key: string]: unknown;
};
export type AlertAction = SmartInsightAction;
export type AlertDecision = SmartInsightDecision;
export type AlertManagementSource = 'insight' | 'predictive' | 'today_action' | string;
export type SmartInsightRawPayload = UnknownRecord;
export type InsightCategoryType = string;
export type SmartInsightTypeLabels = Record<string, string>;
export type SmartInsightSeverityFilter = 'all' | 'low' | 'medium' | 'high' | 'critical' | string;
export type SmartInsightActiveTypeFilter = 'all' | string;
export type ProfitSignalMode = 'real_profit' | 'profit_quality';
export type ProfitSignalRow = {
  label?: string;
  value?: unknown;
  amount?: number;
  percent?: number;
  tone?: string;
  icon?: string;
  [key: string]: unknown;
};
export type ProfitSignalReason = {
  label?: string;
  text?: string;
  value?: unknown;
  [key: string]: unknown;
};
export type ProfitSignalMetric = SmartInsightMetric;
export type ProfitRiskInvoice = {
  orderId?: string | number;
  customerName: string;
  label?: string;
  transactionDate?: string;
  riskScore?: number;
  to?: string;
  [key: string]: unknown;
};
export type BoardKpiItem = {
  key?: string | number;
  label?: string;
  value?: unknown;
  icon?: string;
  tone?: string;
  delta?: unknown;
  deltaTone?: string;
  trend?: number[];
  [key: string]: unknown;
};
export type BoardFocusArea = {
  key?: string | number;
  label?: string;
  value?: unknown;
  icon?: string;
  tone?: string;
  [key: string]: unknown;
};
export type ExecutiveActionGuide = {
  title?: string;
  description?: string;
  label?: string;
  metric?: string;
  icon?: string;
  [key: string]: unknown;
};
export type ExecutiveActionOutcomeGuideFactory = (action?: Partial<SmartInsightLike> | Record<string, unknown>) => ExecutiveActionGuide;
export type SparklinePointFactory = (trend?: number[]) => string;
export type LearningToneFactory = (level: unknown) => string;
export type PricingRecommendationRow = {
  productId?: string | number;
  productName: string;
  currentPrice?: number;
  purchasePrice?: number;
  safeMinPrice?: number;
  optimalPrice?: number;
  aggressivePrice?: number;
  marginPct?: number;
  elasticityScore?: number;
  sold7?: number;
  sold30?: number;
  daysToStockout?: number;
  expectedProfitDelta?: number;
  expectedVolumeDelta?: number;
  confidence?: number;
  risk?: string;
  action?: string;
  [key: string]: unknown;
};
export type CustomerRiskRow = {
  customerId?: string | number;
  title?: string;
  recommendation?: string;
  expectedImpact?: string;
  customerName: string;
  phoneNumber?: string;
  segment?: string;
  segments?: string[];
  riskScore?: number;
  profitScore?: number;
  totalSpend?: number;
  estimatedProfit?: number;
  discountRate?: number;
  creditRate?: number;
  daysSinceLast?: number;
  lastPurchaseAt?: string;
  lastPurchaseLabel?: string;
  action?: string;
  [key: string]: unknown;
};
export type ModalReason = {
  label?: string;
  text?: string;
  value?: unknown;
  [key: string]: unknown;
};
export type ModalMetric = SmartInsightMetric;
export type SalesAgentLeadRow = {
  id: string;
  title: string;
  status?: string;
  intentLabel?: string;
  recommendedChannel?: string;
  expectedImpact?: string;
  ctaLabel?: string;
  action?: string;
  opportunityValue?: number;
  totalSpend?: number;
  lastInteractionAt?: string;
  updatedAt?: string;
  customerId?: string | number;
  customerName: string;
  phoneNumber?: string;
  priority?: number;
  segment?: string;
  message?: string;
  lastPurchaseAt?: string;
  expectedProfit?: number;
  [key: string]: unknown;
};
export type HiddenProfitRow = {
  productId?: string | number;
  title?: string;
  metric?: string;
  reason?: string;
  [key: string]: unknown;
};
export type HiddenProfitOpportunity = {
  id?: string;
  subtitle?: string;
  riskScore?: number;
  title?: string;
  label?: string;
  impact?: number;
  confidence?: number;
  action?: string;
  rows?: HiddenProfitRow[];
  metrics?: SmartInsightMetric[];
  [key: string]: unknown;
};
export type CollectionRiskRow = {
  customerId?: string | number;
  outstandingAmount?: number;
  dueInDays?: number;
  lastActionAt?: string;
  kanbanStageLabel?: string;
  nextFollowupDate?: string;
  sourceType?: string;
  orderId?: string | number;
  touchedToday?: boolean;
  label?: string;
  customerName: string;
  phoneNumber?: string;
  overdueAmount?: number;
  dueAmount?: number;
  dueDate?: string;
  overdueDays?: number;
  lastFollowUpAt?: string;
  nextFollowUpAt?: string;
  riskScore?: number;
  followUpLabel?: string;
  action?: string;
  to?: string;
  [key: string]: unknown;
};
export type StockReorderRow = {
  productId?: string | number;
  title?: string;
  subtitle?: string;
  productName?: string;
  sku?: string;
  stock?: number;
  currentStock?: number;
  minStock?: number;
  sold14?: number;
  daysToStockout?: number;
  suggestedQty?: number;
  estimatedProfit14?: number;
  reorderValue?: number;
  confidence?: number;
  action?: string;
  to?: string;
  [key: string]: unknown;
};
export type InvoiceAuditRow = {
  invoiceId?: string | number;
  subtitle?: string;
  riskyItems?: unknown[];
  reasons?: unknown[];
  metrics?: InvoiceAuditIndicator[];
  orderId?: string | number;
  title?: string;
  customerName?: string;
  riskScore?: number;
  severity?: InsightSeverity;
  amount?: number;
  profitImpact?: number;
  suspiciousItems?: unknown[];
  indicators?: unknown[];
  to?: string;
  [key: string]: unknown;
};
export type InvoiceAuditIndicator = {
  label?: string;
  value?: unknown;
  icon?: string;
  tone?: string;
  [key: string]: unknown;
};
export type SuspiciousAuditCard = InvoiceAuditRow & {
  id?: string;
  title?: string;
  invoiceId?: string | number;
  riskyItems?: unknown[];
  reasons?: unknown[];
  metrics?: InvoiceAuditIndicator[];
};
export type SalesPerformanceMetric = {
  label?: string;
  value?: unknown;
  delta?: number;
  trend?: 'up' | 'down' | 'flat' | string;
  icon?: string;
  tone?: string;
  [key: string]: unknown;
};
export type SalesPerformanceRow = {
  label?: string;
  current?: number;
  previous?: number;
  change?: number;
  confidence?: number;
  [key: string]: unknown;
};
export type CustomerIntelligenceCard = CustomerRiskRow & {
  lifetimeValue?: number;
  purchaseCount?: number;
  recommendation?: string;
};
export type DecisionMemoryRow = {
  id?: string;
  type?: string;
  title?: string;
  status?: string;
  statusLabel?: string;
  outcome?: string;
  outcomeLabel?: string;
  userDecision?: string;
  decisionLabel?: string;
  occurrenceCount?: number;
  lastSeenAt?: string;
  [key: string]: unknown;
};
export type RepetitionOverviewRow = DecisionMemoryRow & {
  type?: string;
  category?: string;
  title?: string;
  occurrenceCount?: number;
  lastSeenAt?: string;
  confidence?: number;
  [key: string]: unknown;
};
export type DecisionMemoryOverviewState = {
  accepted?: number;
  rejected?: number;
  dismissed?: number;
  pending?: number;
  repeated?: number;
  total?: number;
  [key: string]: unknown;
};
export type SideKpisOverviewData = {
  activeInsightCount?: number;
  criticalCount?: number;
  profitQuality?: unknown;
  suspiciousAuditCount?: number;
  [key: string]: unknown;
};
export type TodayActionItem = {
  id?: string;
  insightId?: string;
  title?: string;
  summary?: string;
  label?: string;
  action?: string;
  actionLabel?: string;
  icon?: string;
  to?: string;
  linkedInsightId?: string;
  confidence?: number;
  priority?: number;
  severity?: InsightSeverity;
  type?: string;
  decision?: SmartInsightDecision;
  [key: string]: unknown;
};
export type RealProfitRiskInvoice = ProfitRiskInvoice & {
  invoiceId?: string | number;
  profitAtRisk?: number;
  amount?: number;
  riskLabel?: string;
};
export type RealProfitQualityTone = string;
export type DailyBriefItem = string;
export type MlOfflinePilotReadinessSummaryPayload = {
  generatedAt?: string;
  currentOfflinePilotReadiness?: {
    status?: string;
    importId?: number | null;
    modelKey?: string | null;
    modelVersion?: string | null;
    ownerApproved?: boolean;
    offlinePilotReady?: boolean;
    stabilityEvaluationsConsidered?: number;
    minimumEvaluations?: number;
    avgDeltaF1Pct?: number | null;
    avgDeltaBalancedAccuracyPct?: number | null;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastOfflinePilotChecks?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlOfflinePilotDecisionSummaryPayload = {
  generatedAt?: string;
  currentDecisionBoard?: {
    boardStatus?: string;
    boardDecision?: string | null;
    importId?: number | null;
    modelKey?: string | null;
    modelVersion?: string | null;
    offlinePilotReady?: boolean;
    reviewBoardMemberCount?: number;
    avgDeltaF1Pct?: number | null;
    avgDeltaBalancedAccuracyPct?: number | null;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastDecisionReviews?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlOfflinePilotReviewPackSummaryPayload = {
  generatedAt?: string;
  currentReviewPack?: {
    status?: string;
    importId?: number | null;
    modelKey?: string | null;
    modelVersion?: string | null;
    boardDecision?: string | null;
    boardStatus?: string | null;
    offlinePilotStatus?: string | null;
    stabilityStatus?: string | null;
    shadowEvaluationsCount?: number;
    avgDeltaF1Pct?: number | null;
    avgDeltaBalancedAccuracyPct?: number | null;
    rollbackStatus?: string;
    recommendation?: string;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastReviewPacks?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlOfflinePilotKpiDashboardSummaryPayload = {
  generatedAt?: string;
  currentKpiDashboard?: {
    status?: string;
    importId?: number | null;
    modelKey?: string | null;
    modelVersion?: string | null;
    pilotReadinessPct?: number;
    shadowEvaluationsCount?: number;
    avgDeltaF1Pct?: number | null;
    avgDeltaBalancedAccuracyPct?: number | null;
    rollbackStatus?: string;
    boardDecision?: string | null;
    boardStatus?: string | null;
    recommendation?: string | null;
    riskItemCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  kpiCards?: Array<Record<string, unknown>>;
  lastReviewExports?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlOfflinePilotCloseoutSummaryPayload = {
  generatedAt?: string;
  currentCloseout?: {
    closeoutStatus?: string;
    importId?: number | null;
    modelKey?: string | null;
    modelVersion?: string | null;
    dashboardStatus?: string | null;
    recommendation?: string | null;
    rollbackStatus?: string;
    pilotReadinessPct?: number | null;
    shadowEvaluationsCount?: number;
    avgDeltaF1Pct?: number | null;
    avgDeltaBalancedAccuracyPct?: number | null;
    productionReadinessPreconditionsMet?: boolean;
    ownerSignoff?: boolean;
    ownerName?: string | null;
    productionReadinessOwner?: string | null;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastCloseouts?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlProductionReadinessDesignSummaryPayload = {
  generatedAt?: string;
  currentDesign?: {
    designStatus?: string;
    importId?: number | null;
    modelKey?: string | null;
    modelVersion?: string | null;
    closeoutStatus?: string | null;
    closeoutId?: number | null;
    rollbackStatus?: string;
    recommendation?: string | null;
    productionReadinessDesignPreconditionsMet?: boolean;
    architectureOwner?: string | null;
    securityReviewOwner?: string | null;
    monitoringOwner?: string | null;
    rollbackOwner?: string | null;
    manualOverrideOwner?: string | null;
    productionReadinessOwner?: string | null;
    safetyGates?: Array<{ key?: string; label?: string; status?: string; message?: string; [key: string]: unknown }>;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastDesignSpecs?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlProductionReadinessBacklogSummaryPayload = {
  generatedAt?: string;
  currentBacklog?: {
    backlogStatus?: string;
    releaseGateStatus?: string;
    importId?: number | null;
    designSpecId?: number | null;
    modelKey?: string | null;
    modelVersion?: string | null;
    designStatus?: string | null;
    recommendation?: string | null;
    ownerMatrixComplete?: boolean;
    riskRegisterStatus?: string;
    totalBacklogItems?: number;
    readyBacklogItems?: number;
    openBlockerCount?: number;
    highRiskCount?: number;
    architectureOwner?: string | null;
    productOwner?: string | null;
    engineeringOwner?: string | null;
    qaOwner?: string | null;
    securityOwner?: string | null;
    monitoringOwner?: string | null;
    rollbackOwner?: string | null;
    riskOwner?: string | null;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastBacklogs?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlProductionReleaseGateSimulationSummaryPayload = {
  generatedAt?: string;
  currentSimulation?: {
    simulationStatus?: string;
    simulatedReleaseGateStatus?: string;
    importId?: number | null;
    backlogId?: number | null;
    designSpecId?: number | null;
    modelKey?: string | null;
    modelVersion?: string | null;
    backlogStatus?: string | null;
    backlogReleaseGateStatus?: string | null;
    recommendation?: string | null;
    readinessScorePct?: number;
    ownerMatrixComplete?: boolean;
    riskRegisterStatus?: string;
    releaseGateChecklistStatus?: string;
    blockerCount?: number;
    warningCount?: number;
    passCount?: number;
    totalGateCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastSimulations?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlProductionImplementationCharterSummaryPayload = {
  generatedAt?: string;
  currentCharter?: {
    charterStatus?: string;
    importId?: number | null;
    simulationId?: number | null;
    backlogId?: number | null;
    modelKey?: string | null;
    modelVersion?: string | null;
    simulationStatus?: string | null;
    simulatedReleaseGateStatus?: string | null;
    recommendation?: string | null;
    readinessScorePct?: number;
    scopeBoundaryStatus?: string;
    ownerMatrixStatus?: string;
    goNoGoStatus?: string;
    blockerCount?: number;
    warningCount?: number;
    passCount?: number;
    totalGateCount?: number;
    signoffOwner?: string | null;
    executiveSponsor?: string | null;
    productOwner?: string | null;
    engineeringOwner?: string | null;
    qaOwner?: string | null;
    securityOwner?: string | null;
    monitoringOwner?: string | null;
    rollbackOwner?: string | null;
    changeManager?: string | null;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastCharters?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlProductionImplementationWorkOrderSummaryPayload = {
  generatedAt?: string;
  currentWorkOrder?: {
    workOrderStatus?: string;
    importId?: number | null;
    charterId?: number | null;
    modelKey?: string | null;
    modelVersion?: string | null;
    charterStatus?: string | null;
    charterGoNoGoStatus?: string | null;
    recommendation?: string | null;
    readinessScorePct?: number;
    workOrderScopeStatus?: string;
    ownerMatrixStatus?: string;
    releaseHandoffStatus?: string;
    epicCount?: number;
    taskCount?: number;
    acceptanceCriteriaCount?: number;
    qaChecklistCount?: number;
    rolloutChecklistCount?: number;
    rolloutBlockedCount?: number;
    blockerCount?: number;
    warningCount?: number;
    passCount?: number;
    totalGateCount?: number;
    productOwner?: string | null;
    engineeringOwner?: string | null;
    qaOwner?: string | null;
    securityOwner?: string | null;
    monitoringOwner?: string | null;
    rollbackOwner?: string | null;
    changeManager?: string | null;
    releaseManager?: string | null;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastWorkOrders?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlProductionImplementationDryRunPlanSummaryPayload = {
  generatedAt?: string;
  currentDryRunPlan?: {
    dryRunStatus?: string;
    recommendation?: string;
    readinessScorePct?: number | null;
    dependencySequenceStatus?: string;
    milestonePlanStatus?: string;
    dependencyCount?: number;
    milestoneCount?: number;
    dryRunTaskCount?: number;
    blockerCount?: number;
    warningCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastDryRunPlans?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlProductionDryRunExecutionSummaryPayload = {
  generatedAt?: string;
  currentExecution?: {
    executionStatus?: string;
    recommendation?: string;
    readinessScorePct?: number | null;
    evidenceBinderStatus?: string;
    signoffStatus?: string;
    evidenceItemCount?: number;
    acceptedEvidenceCount?: number;
    signoffCount?: number;
    unresolvedBlockerCount?: number;
    blockerCount?: number;
    warningCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastExecutionLogs?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlProductionDryRunCloseoutMemoSummaryPayload = {
  generatedAt?: string;
  currentCloseoutMemo?: {
    closeoutStatus?: string;
    finalRecommendation?: string;
    recommendation?: string;
    readinessScorePct?: number | null;
    evidenceItemCount?: number;
    acceptedEvidenceCount?: number;
    signoffCount?: number;
    unresolvedBlockerCount?: number;
    riskCount?: number;
    blockerCount?: number;
    warningCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastCloseoutMemos?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlProductionGovernanceSignoffSummaryPayload = {
  generatedAt?: string;
  currentGovernanceSignoff?: {
    governanceStatus?: string;
    implementationEntryDecision?: string;
    recommendation?: string;
    phase2Closed?: boolean;
    readinessScorePct?: number | null;
    governanceSignoffStatus?: string;
    boardQuorumStatus?: string;
    implementationEntryStatus?: string;
    blockerCount?: number;
    warningCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastGovernanceDecisions?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlDisabledShadowAdapterShellSummaryPayload = {
  currentDisabledShadowAdapterShell?: {
    shellStatus?: string;
    readinessScorePct?: number;
    featureFlagKey?: string;
    featureFlagDefault?: boolean;
    shellEnabled?: boolean;
    runtimeInvocationAllowed?: boolean;
    modelExecutionAllowed?: boolean;
    inferenceEndpointExposed?: boolean;
    productionIntegrationAllowed?: boolean;
    noOpAdapterOnly?: boolean;
    auditHookEnabled?: boolean;
    blockerCount?: number;
    warningCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastDisabledShadowAdapterShells?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type MlDisabledShadowRuntimeHarnessSummaryPayload = {
  currentDisabledShadowRuntimeHarness?: {
    harnessStatus?: string;
    readinessScorePct?: number;
    featureFlagKey?: string;
    featureFlagDefault?: boolean;
    harnessEnabled?: boolean;
    runtimeInvocationAllowed?: boolean;
    modelExecutionAllowed?: boolean;
    inferenceEndpointExposed?: boolean;
    productionIntegrationAllowed?: boolean;
    noOpHarnessOnly?: boolean;
    baselineOnlySourceOfTruth?: boolean;
    harnessCheckCount?: number;
    mutationGuardCount?: number;
    blockerCount?: number;
    warningCount?: number;
    blockers?: string[];
    warnings?: string[];
    recommendedNextAction?: string;
    [key: string]: unknown;
  };
  lastDisabledShadowRuntimeHarnesses?: Array<Record<string, unknown>>;
  recommendedNextAction?: string;
  [key: string]: unknown;
};
export type SmartInsightProfitEnginePayload = {
  summary?: ProfitSummaryLike;
  riskyInvoices?: RealProfitRiskInvoice[];
  [key: string]: unknown;
};
export type SmartInsightApiResponse = {
  success?: boolean;
  data?: SmartInsightPayload;
  [key: string]: unknown;
};
export type FinancialAuditApiResponse = {
  success?: boolean;
  data?: unknown;
  [key: string]: unknown;
};
export type SmartInsightSelection = SmartInsightLike | TodayActionItem | SuspiciousAuditCard | Record<string, unknown> | null;
export type SmartInsightSetSelected = (value: SmartInsightSelection) => void;
export type SmartInsightPayloadSlices = {
  learning: SmartInsightLearning;
  summary: SmartInsightSummary;
  hiddenProfit: HiddenProfitOpportunity[];
  suspiciousAudit: SuspiciousAuditLike[];
  customerIntelligence: CustomerIntelligenceCard[];
  pricingRecommendations: PricingRecommendationRow[];
  salesAgentLeads: SalesAgentLeadRow[];
  profitEngine: Record<string, unknown>;
  profitSummary: ProfitSummaryLike;
  profitRiskyInvoices: RealProfitRiskInvoice[];
  profitRealizedShare: number;
  profitRiskShare: number;
  profitQualityTone: RealProfitQualityTone;
  customerHighRiskCount: number;
  customerVipCount: number;
  customerAvgRisk: number;
  criticalCount: number;
  executiveBrain: SmartInsightExecutiveBrain;
  executiveTone: string;
  decisionMemory: DecisionMemoryOverviewState;
};
